### ISSUE TITLE
Can’t open channel on mutiny ios

### ISSUE THREAD

**Issue by issanode** [MutinyWallet/mutiny-web#1002]
I installed mutiny iOS app. 
I sent 300k sats on chain. 
Trying to open a 295-298K channel. 
I always get an error message. 
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14891772/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Hey sorry about this, our lsp is having some errors from the recent influx if users. It should hopefully be resolved soon

**Comment by benthecarman** [comment]
Our LSP issues should be resolved now
