### ISSUE TITLE
94k sats stuck in limbo (first TX) - advice please?

### ISSUE THREAD

**Issue by chrisBonGit** [MutinyWallet/mutiny-web#1004]
[mutiny-logsStuck94k.txt](https://github.com/MutinyWallet/mutiny-web/files/14895149/mutiny-logsStuck94k.txt)
Hi, I'm evangelizing for Mutiny and opening up wallets for fiat friends, e.g. if they pay for my meal, I open a wallet and repay them in sats (even if they are BTC sceptics and think they are pre-coiners).
In Feb tis year, I sent 100k sats to one such friend. However, I forgot to account for fees, after which only 94k stats arrived (I don't think you'd added support for Fedi at that time, possibly Fedi wasn't mature enough).
Currently these sats seem stuck in limbo. I can see the TX but they are not available to use or send, nor do they appear in my fiend's balance.
Please could you advise me how to unblock these? Do I need to send another TX for (say) 110k sats to ensure that >= 100k sats arrive?
log file attached.

Much appreciated, 
Chris.

**Comment by benthecarman** [comment]
According to these logs the invoice was only created on 4/1.

We were having some issues with our LSP, they should be resolved now. I would just try again

**Comment by chrisBonGit** [comment]
Thanks for getting back to me.
Attached are two screen shots (after I refreshed to the latest version of Mutiny).
One shows a balance of 10k sats, despite a total transfer in of 104.29ksats. The majortiy, 94.29k sats, was sent on 18th Feb. 
The second screen shot shows the details of that larger TX.
<img width="563" alt="MutinyBalance" src="https://github.com/MutinyWallet/mutiny-web/assets/39036200/8a5d812a-3166-4990-bcd0-16a82b02ed61">
<img width="563" alt="MutinyInvoice94k" src="https://github.com/MutinyWallet/mutiny-web/assets/39036200/045718e5-4dd5-498e-93ad-2d473c518ab7">

**Comment by TonyGiorgio** [comment]
Could you show the balance screen too? It's very strange that 94k show up there but not reflected in the balance.

**Comment by chrisBonGit** [comment]
Sure, the balance is the first screen shot, I expand it below so you can see the wallet icon is selected;

<img width="806" alt="MutinyWalletBalanceWider" src="https://github.com/MutinyWallet/mutiny-web/assets/39036200/b3ee78af-afa7-4b6f-90fb-9a6da3ca86f4">

**Comment by TonyGiorgio** [comment]
No, in the top left profile icon.

**Comment by chrisBonGit** [comment]
Ah, gotcha...
<img width="884" alt="MutinyBalanceInProfile" src="https://github.com/MutinyWallet/mutiny-web/assets/39036200/98130d90-e26c-420e-9be6-d5dace0e6d44">
Just for background infol, the fedi balance was another top up at Bitcoin Atlantis, baselayer/on-chain to fedi (LN payments were failing/timing out for me) ~50ksats, so not connected to this issue.

**Comment by TonyGiorgio** [comment]
This could be the problem from the logs: 

```
ab2a 2024-04-06 22:50:09.678 TRACE [lightning::ln::peer_handler:1632] Received message Warning(WarningMessage { channel_id: ChannelId([3, 33, 172, 181, 139, 197, 225, 223, 251, 49, 166, 174, 207, 123, 42, 126, 223, 177, 233, 186, 121, 50, 255, 50, 184, 6, 75, 208, 143, 95, 237, 32]), data: "bad reestablish revocation_number: 0 vs 3" }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
ab2a 2024-04-06 22:50:09.678 DEBUG [lightning::ln::peer_handler:1653] Got warning message from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0: bad reestablish revocation_number: 0 vs 3
```

**Comment by chrisBonGit** [comment]
Thanks for spending your time look at this. Do you have an npub I can zap?
I'm afraid I'm not sure what I can do with the information you have shared above. I think the transaction was from a Breez wallet to this Mutiny Wallet, should I share the above with them.

**Comment by TonyGiorgio** [comment]
could you screen shot the channel view in the settings? we might need to close the channel from the LSP side.

**Comment by chrisBonGit** [comment]
Sure...
<img width="1074" alt="MutinyChannelScrnShot" src="https://github.com/MutinyWallet/mutiny-web/assets/39036200/81c8f22c-a105-41b7-96ef-a5f8f297c1c4">

**Comment by chrisBonGit** [comment]
Oh no - Sorry, my bad - that's from the wrong wallet. 
Below is the screenshot from my friend's wallet (shows no channels)
<img width="1074" alt="MutinyChannelScrnShot_YBH" src="https://github.com/MutinyWallet/mutiny-web/assets/39036200/b433ac6d-9da5-4f1f-8bc7-618c7f66d834">

**Comment by chrisBonGit** [comment]
> This is difficult to follow along. Is this your wallet or your friends wallet? What's the issue on which device?

Sorry about the confusion:
I've gone back through my replies and removed 2 screen shots that were from my walllet, instead of my friends (I've explicitly shown where I've removed / updated images)

The issue for this ticket is that the 94.29ksats transferred to my friend's wallet is stuck in limbo somehow. I can see it as an inbound transaction, but the wallet balance was never updated by that amount. Hence, you can see two inbound TXs (the other for 10ksats) but the total balance is only 10k sats.
