### ISSUE TITLE
Failed to create a channel

### ISSUE THREAD

**Issue by mjdNjhNJ** [MutinyWallet/mutiny-web#1009]
I'm unable to swap on-chain to LN. After few minutes request ends with "Failed to create a channel".

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14906163/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
I'm seeing a lot of disconnections with the LSP, could you restart the wallet and try again? Also, can you confirm that you're not running mutiny on multiple devices at the same time?

**Comment by mjdNjhNJ** [comment]
@TonyGiorgio I have tried restarting the wallet and problem still persists. Mutiny is running only on the phone.

**Comment by mjdNjhNJ** [comment]
Issue resolved in version 0.6.3.
