### ISSUE TITLE
More informative "sent" and "received" screens

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#101]
Could show fees paid, could show tags.

Also, for on-chain it shouldn't say "sent" it should say "Payment initiated" or something like that

Also also for on-chain, explain what the mempool link is for maybe? Also isn't mempool link bad for privacy?

<img width="497" alt="Screenshot 2023-05-11 at 3 02 54 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/1995ef4e-c69b-4a8d-bcb3-350596693862">

<img width="623" alt="Screenshot 2023-05-11 at 3 17 35 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/0b5eb1ec-94f4-44c6-bfe3-9c1f6096d8d5">

**Comment by TonyGiorgio** [comment]
For the users that care enough about that info, they can click into that in the recent activity to view it in the modal. So personally I wouldnt worry too much about it.

**Comment by futurepaul** [comment]
fixed this awhile ago
