### ISSUE TITLE
Zaps to Lightning Address not showing up anywhere.

### ISSUE THREAD

**Issue by nostrI21** [MutinyWallet/mutiny-web#1012]
I test zapped myself three times and it showed up nowhere in Mutiny Wallet. I have restarted app multiple times too. Federation balance is still showing 0 and Lightning balance did not go up either. Not sure what happened.

Issue Reported here 
https://primal.net/e/note1dutkt3pqa3v4gkrzvepekrz52r3eae45d50r6enqkyfx06rnp29qhx2jeu

**Comment by TonyGiorgio** [comment]
Could you upload logs? It's in the emergency toolkit.

**Comment by nostrI21** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14908879/mutiny-logs.txt)
Here is my latest logs. Thanks for the help.

**Comment by nostrI21** [comment]
Also my explanation on the top was not explained properly they do show up in my receives section its just my balances did not show any changes. Federation balance shows 0 and lightning balance did not go up.
![media-cache (5)](https://github.com/MutinyWallet/mutiny-web/assets/166430419/0b2992ae-4156-4e8c-8b27-1162bb344323)
![media-cache (4)](https://github.com/MutinyWallet/mutiny-web/assets/166430419/209c7a9b-5aca-457c-8390-deda71c7f7c6)

**Comment by TonyGiorgio** [comment]
It does look like there are issues sometimes, we're investigating. Sorry about this but hopefully we have something soon. Will make sure you get these zaps too, thank you for testing this out and letting us know.

**Comment by benthecarman** [comment]
Fix for this is going out, sorry about the issue!
