### ISSUE TITLE
QR code scanner is not good

### ISSUE THREAD

**Issue by f321x** [MutinyWallet/mutiny-web#1018]
When trying to scan a qr code like in the attached screenshot the mutiny (native android and pwa) qr code scanner is so bad that I'm unable to redeem the lnurlw qr code. 
Other qr code scanners like the Binary Eye App or Blink Wallet can recognize the QR code instantly. 

This makes me unfortunately unable to recommend Mutiny to the users of the ATM.
Getting the QR Reader on a level like the Binary Eye scanner would vastly improve UX as this is a core feature of a wallet.

![Screenshot_20240409-075112](https://github.com/MutinyWallet/mutiny-web/assets/51097237/3129b867-121b-4572-b744-a4c2d0eda715)

Tested Phone: Google Pixel 6a GrapheneOS

**Comment by TonyGiorgio** [comment]
I scanned it just fine on my pixel with graphene. We're quite happy with ours and not looking to switch.

**Comment by f321x** [comment]
Maybe the library is ok and there is a bug with the Pixel 6a and Mutiny, but see the videos below, it's barely usable:

Binary Eye QR Code scanner:
https://github.com/MutinyWallet/mutiny-web/assets/51097237/d17468b0-7bf2-45c6-99c2-dd2f96c8c8f5

Mutiny Wallet native installed:
https://github.com/MutinyWallet/mutiny-web/assets/51097237/e06b6810-5463-4fb0-a650-1bb6e2f349b0

**Comment by benthecarman** [comment]
For the native app we use the phone's native qr scanner, maybe you need to update the OS or something?

**Comment by f321x** [comment]
I'm just using the newest version of GrapheneOS for the Pixel 6a, but the experience is the same when using the PWA

**Comment by f321x** [comment]
Here is a video of the PWA qr scanner in Vanadium (GrapheneOS Chromium based browser). It's even worse than the native app and doesn't scan at all.


https://github.com/MutinyWallet/mutiny-web/assets/51097237/c8417a4a-5a33-4d2e-844e-011e077e6bad


I also had the same experience with the PWA on some Huawei or Samsung phone of a friend, so I don't think its phone specific.

**Comment by TonyGiorgio** [comment]
We use an OS integrated ML-based qr code library and it has not been a problem for anyone until you bring this up with that ATM. I suggest using something that's bigger than an extremely dense half an inch QR code.

**Comment by f321x** [comment]
I was just wondering because it's working so much better with other apps, see video above. So the reason must be in Mutiny

**Comment by j0hncc** [comment]
> I was just wondering because it's working so much better with other apps, see video above. So the reason must be in Mutiny

I agree with you.  Sometimes I have to use a different wallet which scans the invoice fine, when the Mutiny wallet will not.
