### ISSUE TITLE
Receive amount never went through 

### ISSUE THREAD

**Issue by villainvortex** [MutinyWallet/mutiny-web#1019]
Prior to update , I’ve been able to send and receive bitcoin from cashapp. Yesterday I sent 100,000 sats from cashapp to my mutiny wallet and it never came in. I contacted cashapp and it shows pending. They then I turn told me to contact mutiny because it’s an error on your end. As of now those 100,000 sats are just stuck somewhere waiting on mutiny to receive them.[
![IMG_1291](https://github.com/MutinyWallet/mutiny-web/assets/166512868/842b7bf3-9b58-4e19-9d76-3d02b2e005e3)
](url)

**Comment by villainvortex** [comment]
How to upload the logs ? I'm attaching two screenshots to last transactions. ![image](https://github.com/MutinyWallet/mutiny-web/assets/166512868/56f909a4-cbd8-4647-b469-6ff3431a0124)
![image](https://github.com/MutinyWallet/mutiny-web/assets/166512868/38995df6-dacd-499d-b348-fc28d5f354de)

**Comment by benthecarman** [comment]
in the emergency kit there is a download logs button. if you could attach that file here

**Comment by villainvortex** [comment]
There is no receive of the 100,000 sats from cashapp which is still stuck in the unknown land while trying to send to my mutiny wallet. Yes it's insignificant amount, but to have it occur after an update doesn't sit well in trying to learn the wallet and its functions.

**Comment by villainvortex** [comment]
> in the emergency kit there is a download logs button. if you could attach that file here

Thank you. I found that and uploading now.

**Comment by villainvortex** [comment]
> in the emergency kit there is a download logs button. if you could attach that file here

How to attach via mobile because when I download it on iOS to files, it doesn't upload here.

**Comment by benthecarman** [comment]
You can click the photo icon and select it from your files

**Comment by villainvortex** [comment]
> You can click the photo icon and select it from your files 

I thought that too originally and tried that and it didn't work. 

![image](https://github.com/MutinyWallet/mutiny-web/assets/166512868/748d478e-0da9-4251-8418-82ba258ee58b)

![image](https://github.com/MutinyWallet/mutiny-web/assets/166512868/fd073bc4-1334-4a98-810f-619c29ad7bfa)

**Comment by benthecarman** [comment]
can you just email them to team@mutinywallet.com then

**Comment by villainvortex** [comment]
Yes just emailed them. Thank you.

**Comment by benthecarman** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14924513/mutiny-logs.txt)

**Comment by benthecarman** [comment]
I am seeing a lot of connection errors in your logs, might be that your node can't connect to the LSP to receive the payment.

**Comment by villainvortex** [comment]
> I am seeing a lot of connection errors in your logs, might be that your node can't connect to the LSP to receive the payment.
> 
> 
> 
> 

1. What does that mean, and 2. Is it a fix for it I can do via mobile?

**Comment by benthecarman** [comment]
I would make sure you have a stable wifi connection and not on a spotty internet.

**Comment by villainvortex** [comment]
I've only sent while connected to wifi. That's why I'm puzzled that I was able to send and receive before, and after the update it gets lost in transit. When home, all devices are connected to stable wifi. Disappointed because the BTC community raved about this wallet and after this experience it's not pleasant one.

**Comment by TonyGiorgio** [comment]
Lightning payment failures and stuck transactions happen. It'll show back up on the cashapp side after a few days when it switches from pending to failed, nothing we can do about it.
