### ISSUE TITLE
No route found payments and receive from Strike App

### ISSUE THREAD

**Issue by skellam** [MutinyWallet/mutiny-web#1027]
Unable to route or receive payments from Strike App to Mutiny wallet.  iPhone Pro Max 14,  iOs 17.4.1, Mutiny 0.6.3.  Restarted phone but issue has been persistent.

**Comment by TonyGiorgio** [comment]
The strike issue is on their end. I thought you were mentioning you were having camera issues as well. Is that still the case after the restart?

**Comment by skellam** [comment]
Sorry, misunderstood you.   I opened new issue.  thanks
