### ISSUE TITLE
Scan button not bringing up live video for QR capture

### ISSUE THREAD

**Issue by skellam** [MutinyWallet/mutiny-web#1028]
iPhone Pro Max 14, iOs 17.4.1, Mutiny 0.6.3. Restarted phone but issue has been persistent.   Not able to scan QR codes.
![8cc4981b-f7d5-4843-b2a7-664ecb9ae9ab](https://github.com/MutinyWallet/mutiny-web/assets/20101372/300a925b-3317-4275-bdb2-c3d90d233bfd)

**Comment by benthecarman** [comment]
Did you not give the app camera permissions?

**Comment by TonyGiorgio** [comment]
Try uninstalling and install again? After making sure you have your seed words backed up. Or turning off permission in the settings and turning on again.

**Comment by skellam** [comment]
I clicked on button to approve video permissions.
Then when the screen was black I clicked on the tab where there was a red video cam icon and it asked me if I wanted to stop recording so it seemed to me like it has permission

**Comment by benthecarman** [comment]
that only appears if you're on a video call or something AFAIK, possible some other app already had control of the camera

**Comment by skellam** [comment]
Ok, i completely uninstalled the app and went to the website on safari and recreated the mutiny wallet icon on my home screen.  Imported the wallet and nostr profile and got the wallet up and running.  Clicked on the scan icon and same problem.  Blank screen with video recording icon on the upper tab.   I looked at safari setting and video access is granted.  I opened my camera app to check and see if video camera is working and it was.  No other app is using the camera.

**Comment by skellam** [comment]
I deleted the PWA version and installed the TestFlight version and it works fine and brings up the camera for scanning.   Must be an issue with the way the PWA accesses the camera.

**Comment by TonyGiorgio** [comment]
> I deleted the PWA version and installed the TestFlight version and it works fine and brings up the camera for scanning. Must be an issue with the way the PWA accesses the camera.

Yes, all PWA's are more prone to an internal iOS bug with the camera not loading. Restart usually fixes it, weird that it's not.
