### ISSUE TITLE
Activity aesthetic tweaks

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#104]
Tag icon instead of hamburger:
<img width="558" alt="Screenshot 2023-05-11 at 3 32 17 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/b7672614-7222-4bde-9b56-154d9bd64802">

Pending in yellow?
<img width="553" alt="Screenshot 2023-05-11 at 3 32 10 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/5cd8e882-b275-40c5-b552-9c6f9538e8c2">

**Comment by TonyGiorgio** [comment]
Not sure if pending has to be yellow. Maybe italics? Just something minor to make it easy to distinguish.

**Comment by futurepaul** [comment]
hamburger is gone
