### ISSUE TITLE
Incorrect balance after adding nostr profile

### ISSUE THREAD

**Issue by avbpodcast** [MutinyWallet/mutiny-web#1051]
A balance of 4000 sats, was changed to 1059 sats. 
Even after a full restore on a clean browser, it stayed at 1059 sats.

Steps to reproduce: on mutiny plus account I've first added a nostr profile I already had (with balances on it on 0xchat echash)
Then I added a fedimint of bitocin madeira with 4 sats on it
The profile then switched from my mutiny.plus address to the 0xchat address' linked blink wallet
After that, my balances were changed from 4000 I had on mutiny to 1049.

I disconnected both fedimint and nostr profile.
then restored my mutiny wallet on other machine
the balance was still wrong.

(logs available pm me on nostr: npub1sec6degc3ae7warveuxaz6dlffnc2sutwtqjr7pmll7sf7ypjngsd4p0l7

**Comment by TonyGiorgio** [comment]
If you change federations, your funds from the other federation do not carry over. We also don't support changing federations with the mutiny plus address yet.

**Comment by avbpodcast** [comment]
Hi there, AVBpodcast aka @deadeyes here, after your comment, I'll submit the logs here.
I'll love testing the wallet as a dumb user. If you need any more info, please let me know and I'll provide it.
[mutiny-logs_14424.txt](https://github.com/MutinyWallet/mutiny-web/files/14970016/mutiny-logs_14424.txt)

**Comment by Veezywqp1** [comment]
> Hi there, AVBpodcast aka @deadeyes here, after your comment, I'll submit the logs here.
> I'll love testing the wallet as a dumb user. If you need any more info, please let me know and I'll provide it.
> [mutiny-logs_14424.txt](https://github.com/MutinyWallet/mutiny-web/files/14970016/mutiny-logs_14424.txt)



> Hi there, AVBpodcast aka @deadeyes here, after your comment, I'll submit the logs here.
> I'll love testing the wallet as a dumb user. If you need any more info, please let me know and I'll provide it.
> [mutiny-logs_14424.txt](https://github.com/MutinyWallet/mutiny-web/files/14970016/mutiny-logs_14424.txt)

Thanks I don’t know what I’m doing
