### ISSUE TITLE
5€ fee on 28€ swap from mint to LN self custody

### ISSUE THREAD

**Issue by avbpodcast** [MutinyWallet/mutiny-web#1055]
I hade 100€ in a mint balance.
Swapped 28 to LN
got a 5€ fee
Doesn't feel right ... at all.
![notright](https://github.com/MutinyWallet/mutiny-web/assets/146881913/15ac0352-d135-4fbe-9e5f-019b5c1fe36f)

**Comment by TonyGiorgio** [comment]
That's the cost of transacting on chain. We display the fee before you swap and ask you to confirm it.

**Comment by avbpodcast** [comment]
Yes, and I agreed to the high fee. That's not the issue.
The issue is that a bunch of sats from a mint to self-custodial lighting needs to be this high? 
Also: new people won't know the difference (the balances are also separate in the settings details, but added up in the first screen totals. Which confuses me... if I pay 180000 sats and I have 186000, I still can't pay, b/c 30000 is in some mint.
This is pure chaos.

**Comment by futurepaul** [comment]
We'll keep working to communicate this better. There's a pretty big jump in cost and personal responsibility, and related knowledge about how things work, when going from fedimint to self-custodial. The reason for the high fee, for instance, is based on the current mempool: https://mempool.space/
