### ISSUE TITLE
Mutiny+ lightning address not useable

### ISSUE THREAD

**Issue by GitHubxSuperKai** [MutinyWallet/mutiny-web#1058]
Not able to send sats to my Mutiny+ lighting address.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14973616/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
What's your address?

**Comment by GitHubxSuperKai** [comment]
superkai@mutiny.plus

**Comment by TonyGiorgio** [comment]
Where are you sending from? There's a known issue with some custodians that cannot pay federations and the issue is on their side. I just zapped you just fine.

**Comment by GitHubxSuperKai** [comment]
I'm using Strike for testing. The error message is 'unable to find payment route'. I guess it's an issue with the custodian then. Confirmed that I got your zap to federation. 

Although, I did some testing yesterday zapping to self custody/lighting channel and it didn't work as well. Same error message. Could this be the same issue?

**Comment by TonyGiorgio** [comment]
Yes it's a strike issue and they are looking into it.

> zapping to self custody/lighting channel

What do you mean by this? How are you trying to "zap to self custody?"

**Comment by GitHubxSuperKai** [comment]
I have a lightning channel setup in Mutiny prior to joining a federation. I left the federation yesterday to test if it was an issue with that and I was having the same issue using Strike. At this point, I'm with you it's a Strike issue since I was able to fund the wallet about a week ago just fine.

I'm good to close out this ticket. Thanks for looking into the issue, Tony.

**Comment by TonyGiorgio** [comment]
I see, yeah that makes sense, had to make sure that's what you were doing to test it.

One thing to check is whether or not your channel is online. We've also been having issues with our LSP, so the self custodial channel could be on our side.

**Comment by GitHubxSuperKai** [comment]
It was online for sure. I'll play around with it more and see if I can narrow down the issue.

**Comment by GitHubxSuperKai** [comment]
FWIW, I tried to zap you back @ tony@mutiny.plus and it's not going through 😞 
[mutiny-logs (1).txt](https://github.com/MutinyWallet/mutiny-web/files/14985422/mutiny-logs.1.txt)
