### ISSUE TITLE
wallet fails to load - android apk 0.6.3 and 0.6.4

### ISSUE THREAD

**Issue by umk0m1qk** [MutinyWallet/mutiny-web#1059]
Was running 0.6.3. Today on launch the app failed to load. Stuck on "Loading: Setup." Force closed app and relaunched - no change. Restarted phone - no change. Checked Obtainium and noted update available to 0.6.4. Installed update. Relaunched - no change. Load is stuck at same point. Tried to download logs - receive error "Failed to read data from storage." Pixel 6a running latest GrapheneOS

![IMG_20240415_082236](https://github.com/MutinyWallet/mutiny-web/assets/158820607/e62098af-0f0c-4eff-b3f9-e754986fc089)

**Comment by TonyGiorgio** [comment]
Try restoring from seed words.

**Comment by umk0m1qk** [comment]
That worked only after a complete uninstall & reinstall of the app. Initially, the seed recovery would just hang and spin. So glad I wasn't force closed this time. Thanks!

**Comment by TonyGiorgio** [comment]
Sorry about that. If you have any specifics about your setup, channels, fedimint, etc. that might have caused this, or the last thing you remember doing, it would be helpful since we don't have the logs here.

**Comment by umk0m1qk** [comment]
Exact same thing just happened again on first launch after update to 0.6.5. Will not complete load, and log download does not work.

When this happened the first time, I had one open lightning channel, no fedimint, no address. Since then I added a fedimint, but couldn't figure out how to use it. Fedimint showed 0 ecash. So latest setup is 1 open channel, fedimint, no address. As far as I know, there were no pending zaps at the time of both app freezes.

**Comment by TonyGiorgio** [comment]
And logs still won't download? Can you try a restore from seed again and see if they do?

**Comment by umk0m1qk** [comment]
Reinstalled app and restored again from seed. Here are the logs post restore.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15051771/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Are you on the latest version? We made a few updates last week. I'm not seeing any errors in your logs, are you still having issues after you reinstalled?

**Comment by umk0m1qk** [comment]
Currently running 0.6.7. So far no load issues.
