### ISSUE TITLE
Backup Reveal Words Verification 

### ISSUE THREAD

**Issue by alltheseas** [MutinyWallet/mutiny-web#1060]
Add verify, dont trust spot check with three random numbered seed words to current flow. 
Remove first, and third checks: "I wrote down the words". "I'm not lying to get this over with".

![image](https://github.com/MutinyWallet/mutiny-web/assets/64376233/4005a941-e185-4900-9188-8ea5d366869c)

**Comment by alltheseas** [comment]
e.g. Verify words

3: fish
5: tuna
12: yeti

if correct -> proceed
if incorrect -> revert to seed words display screen

**Comment by TonyGiorgio** [comment]
No, these are terrible and a pain in the ass.
