### ISSUE TITLE
Onchain balance not showing.

### ISSUE THREAD

**Issue by timvak** [MutinyWallet/mutiny-web#1065]
Hey Mutiny team.

Great wallet and love the new upgrades!

Got one small problem tho, my onchain balance doesnt show anymore. Ive tried resync but the nothing happens and i get the dangit screen, after reload no change.

Is this fixable or do i need to use the emergency kit?

Thanks in advance.

![IMG_20240416_171214](https://github.com/MutinyWallet/mutiny-web/assets/71341469/19bb1347-1e82-49ad-b652-0ec12975e8ea)
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14999144/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Can you provide logs?

**Comment by benthecarman** [comment]
Have you tried restoring from seed

**Comment by timvak** [comment]
No not yet, wanted to check with you guys befor going that route. Might looze the + subscription and channel in the proces..

Is backing up and reinstall the way to go?

**Comment by timvak** [comment]
K wil try 🤞brb

**Comment by timvak** [comment]
No luck.

after resync same as before..

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15000647/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Can you walk through what exactly the steps you are doing? Is the recursive error showing when you open the wallet or when you do the on-chain rescan?

**Comment by timvak** [comment]
Open wallet > see no onchain balance > go to admin page > press resync wallet > wait for 5 min+ > nothing happens > < out of settings > here i got the "dangit" page multiple times but not this time. The seed refresh might have fixed that. Still no onchain balance tho?

Any ideas?

**Comment by TonyGiorgio** [comment]
You might want to check sparrow to see if your funds are even there.

**Comment by timvak** [comment]
What script type is mutiny wallet?

**Comment by benthecarman** [comment]
taproot

https://github.com/MutinyWallet/mutiny-web/wiki/Recovery

**Comment by timvak** [comment]
funds are not there...

I had an issue with a channel fc, i had contact with Tony about this but the onchain balance was showing in the wallet so i didnt see a big problem. Now in sparrow i see the remaining >800k sats never came back.. im on voltage lsp...

**Comment by benthecarman** [comment]
Okay that makes it more clear. Seems like your force close was swept by the LSP.

https://mempool.space/tx/e3da3b0a111516cd61133268004e6cdad3fdd2e3416e5845c22fdd25628da6dc

If you can provide an on-chain address we can try to get it back for you

**Comment by timvak** [comment]
Shall i mail Tony an adress dont like posting adresses in public.

just to be clear, i can just generate a on chain receiver adress i mutiny richt? Thats where i want it to go ;)

**Comment by benthecarman** [comment]
> Shall i mail Tony an adress dont like posting adresses in public.

yeah just send it to team@mutinywallet.com

> just to be clear, i can just generate a on chain receiver adress i mutiny right? Thats where i want it to go ;)

yes

**Comment by TonyGiorgio** [comment]
Transaction has been sent.

**Comment by timvak** [comment]
All is good thanks for the great support 👍
