### ISSUE TITLE
Wallet stuck on loading screen after fedimint swap to lightning 

### ISSUE THREAD

**Issue by markskram** [MutinyWallet/mutiny-web#1071]
After making a swap from Bitcoin Atlantis fedimint to Lightning, my app is stuck in the Setup step. Didn’t realize that I was still running the older version when I did the swap. Updating to 1.6.5 (1543) did not fix the issue, still persists. 

This isn’t my video, but it’s what I’m seeing. 
https://video.nostr.build/850f6c4292c0474bc27c445652a557c4bf3d8253cf4f2ab988add625969c8137.mp4

**Comment by TonyGiorgio** [comment]
I've been trying to reproduce this but haven't been able to. Since it's hard to get logs in this state, something that would be useful is if you could open up mutiny on the web, load up the seed words, and open the browser console while it loads. The logs there could indicate the problem.
