### ISSUE TITLE
Wallet stuck on "Mutiny may be running on another device"

### ISSUE THREAD

**Issue by Yonle** [MutinyWallet/mutiny-web#1085]
Version: Web (https://app.mutinywallet.com)

Even after closing Mutiny on Firefox Desktop for a hour, My wallet is stuck in this screen for hours even with no browser or devices running mutiny.
![Screenshot_20240420-173005](https://github.com/MutinyWallet/mutiny-web/assets/63401712/8667ecc3-db65-4cb5-a6a6-e48c925e8f26)

**Comment by Yonle** [comment]
Device lock?
```
86e9 2024-04-20 12:49:43.083 TRACE [mutiny_core:843] Checking device lock
86e9 2024-04-20 12:49:43.085 INFO  [mutiny_core:845] Current device lock: DeviceLock { time: 1713674819, device: "0af584b4-7ed9-47a8-8316-bdcd85f53006" }
e9c9 2024-04-20 12:53:50.617 TRACE [mutiny_core:843] Checking device lock
e9c9 2024-04-20 12:53:50.621 INFO  [mutiny_core:845] Current device lock: DeviceLock { time: 1713674819, device: "0af584b4-7ed9-47a8-8316-bdcd85f53006" }
5b19 2024-04-20 12:54:23.408 TRACE [mutiny_core:843] Checking device lock
5b19 2024-04-20 12:54:23.411 INFO  [mutiny_core:845] Current device lock: DeviceLock { time: 1713674819, device: "0af584b4-7ed9-47a8-8316-bdcd85f53006" }
3e65 2024-04-20 12:55:04.578 TRACE [mutiny_core:843] Checking device lock
3e65 2024-04-20 12:55:04.578 INFO  [mutiny_core:845] Current device lock: DeviceLock { time: 1713674819, device: "0af584b4-7ed9-47a8-8316-bdcd85f53006" }
```

**Comment by Yonle** [comment]
Looks like i know why now.

My computer date being inaccurate, And Mutiny is comparing via Timestamp.
```
> (new Date(1713674819*1000)).toLocaleString("ia")
'21-04-2024 11:46:59'
```

**Comment by Yonle** [comment]
Changing phone date / time fixes this.

I may suggest to have a feature to check an date from system with the server (You could check it via `Date` HTTP header and turn it into timestamp).

**Comment by benthecarman** [comment]
Everything is done off of your device's clock. Did you recently change timezones or something?

**Comment by Yonle** [comment]
Well. It was about me launching mutiny wallet on incorrect computer date.

**Comment by TonyGiorgio** [comment]
System clock is important to get correct. Not fixing.
