### ISSUE TITLE
NWC (Nostr Wallet Connect) suddenly does not work

### ISSUE THREAD

**Issue by Yonle** [MutinyWallet/mutiny-web#1086]
https://github.com/MutinyWallet/mutiny-web/assets/63401712/b250d4cc-7000-4c73-a859-22341042ddbe

NWS is previously working in Mutiny Wallet version 0.6.6, But it stops working lately at 0.6.7.

I've tried the following:
- Relogin
- Recreated wallet connection
- Using another client to use NWC

None of them working.

For log, This was emitted everytime:
```
a0c2 2024-04-21 12:21:31.999 TRACE [lightning_background_processor:693] Calling OnionMessageHandler's timer_tick_occurred                                                                                 
a0c2 2024-04-21 12:21:32.470 TRACE [mutiny_core::federation:380] Getting activity                    
a0c2 2024-04-21 12:21:32.546 TRACE [mutiny_core::federation:429] About to go through 0 operations    
a0c2 2024-04-21 12:21:32.546 TRACE [mutiny_core::federation:451] Going through 0 pending invoices to extract status                                                                                       
a0c2 2024-04-21 12:21:34.094 TRACE [mutiny_core::federation:380] Getting activity                    
a0c2 2024-04-21 12:21:34.130 TRACE [mutiny_core::federation:429] About to go through 0 operations    
a0c2 2024-04-21 12:21:34.130 TRACE [mutiny_core::federation:451] Going through 0 pending invoices to extract status
```

**Comment by benthecarman** [comment]
Can you submit your whole log file

**Comment by Yonle** [comment]
![mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15055581/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Your log file only has like 5 minutes of activity? This isn't useful, did you strip it all out? 

Make sure your NWC string is in amethyst correctly matches what your current wallet connection string is in mutiny. Amethyst has a habit of not persisting settings.

**Comment by Yonle** [comment]
Good day.

> Your log file only has like 5 minutes of activity? This isn't useful, did you strip it all out? 

Yes. However i've checked the log before i started trimming out.

> Make sure your NWC string is in amethyst correctly matches what your current wallet connection string is in mutiny. Amethyst has a habit of not persisting settings.

Yes. Already ensured that the configuration matches to the one that mutiny provided.

Not only i could not zap with Amethyst, but i could not do with Primal too.

**Comment by Yonle** [comment]
Closing as this seems having to do with Amethyst itself being not persistent on configuration. Thanks for mentioning it. Strange that it just worked recently both on Amethyst and Primal.

**Comment by TonyGiorgio** [comment]
https://github.com/vitorpamplona/amethyst/issues/580
