### ISSUE TITLE
More Nuanced Fedi Mint Discovery

### ISSUE THREAD

**Issue by Mynima** [MutinyWallet/mutiny-web#1087]
Hi Mutineers,

Great work and keep shipping the updates, fantastic application. 

This is more some food for thought/enhancement ideas around the use of Nostr as a discoverability layer for interacting with Fedi mints, or in fact any other similar WoT-like algorithm for surfacing "trusted opinions" (undefined, loose term) providers from a users friend +/- follower list. You may already be doing something like this or have come up with a better solution so please by all means close this if it isn't relevant.

While you were on CD with Odell I impressed with the exploration/implementation of Nostr as a layer to help user find "recommended" or "trusted" mints. On the surface it sounds like perhaps you've develop some methodology of looking at the users friend list (as well as some way of filtering out pure garbage). However, I wonder if, with the existing NIPs, we may be able to do something slight more accurate or nuanced that would allow for some interesting scoring/rating methodologies to emerge.

First off not everyone that someone follows will be trusted, "_keep your friends close but enemies closer_". So in that respect the user would ideally need a way to filter/reduce their current list of people they follow to surface better signal from this information (also it puts the "who do I trust?" question in the hands of the user. After taking a look at the available NIPs I wondered if NIP-51 (lists) and more specifically kind:30000 would be a possible solution for this. 

To leverage this a user could create/maintain a new list (standard naming would be great here for interoperability with other apps, e.g. CashU mints) that is a subset of their following list as a means for differentiating between 'someone who is followed and who's opinion carries weight' and 'just someone who is followed'. As a user would actively be involved in the decision of who to add to this sub-list it also means the mints algorithm is less reliant on assumptions. It also opens up an interesting way of adding tiered grading or extended degrees of separation for scoring mints and makes it bespoke to the user (as well as allows them to transfer/replicate this scoring system in other applications).

Imagine you were scoring a mint you could look at in terms of layers of signal (highest to lowest):
- Recommend by someone in my "trusted opinions" list
- Recommend by someone in the "trusted opinions" list of someone in my "trusted opinions" list
- Recommend by someone in my following list 

You could easily capture each level and apply weighting to each count to arrive at an overall score for a mint that is based on a users direct Web-of-TrustedOpinions (WoTO). There is also nothing stopping the algorithm from also incorporating other things that you may have been using already like; uptime of the mint, mint user base, general public reviews etc.

It would be nice to somehow untangle the "I follow this person because I'm just interested in what they have to say, or they make really good memes" and "I trust when this person recommends something to me". This is something people already do naturally and I believe you tap into that by showing the picture of the users in your friends list who have recommended a mint. However, as time goes on it would be nice to put more control in the users hands when figured out which mints to show them at the top of their list and this is a simple way to do it. It also doesn't stop the existing mechanism from being a default fall back which allows for backwards compatibility for users who didn't bother setting up a WoTO list.

Anyway, have a look, see what you think. Cheers!

**Comment by TonyGiorgio** [comment]
Yes, appreciate it. Though this is best discussed at the [NIP level](https://github.com/nostr-protocol/nips/pull/1110), though yeah I disagree with changing it or using that. We've spent 2 months in Madeira talking to two dozen nostr devs and something like this was the best approach. 

There's all kinds of WoT things that _could_ be done, but nobody has applied anything meaningful in nostr yet and this wasn't going to be the first thing. These are _explicit_ recommendations, not passive, so it's up to the user to visually look whether or not they would trust that user's recommendations of a mint.

**Comment by Mynima** [comment]
Appreciate the feedback from you both. Will def keep an eye on what happens at the NIP level and maybe move some comments/thoughts there. I think as we start to build out more services that integrate Nostr this will item will keep becoming more and more important so perhaps it is revisited in the future. 

Fully agree with Tony that there is still the natural ‘in the moment’ decision for the user for them to personally assess their ‘trust’ thresholds which currently is the best we can ask for. It is the user’s choice which is the most critical thing.

As I said before, keep up the great work and keep shipping!
