### ISSUE TITLE
Figure out what the hell is happening with lightning channel labels

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#109]
I didn't add any of these tags

<img width="558" alt="Screenshot 2023-05-12 at 10 06 46 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/ffb2c0d7-708e-439b-a9ea-52140e00d48e">

also clog up the tag editor

<img width="601" alt="Screenshot 2023-05-12 at 10 07 38 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/1a08bbb5-d35b-442e-bd9e-c9ff96a8f02d">

**Comment by benthecarman** [comment]
Oh it adds a label when you open a channel. Can probably clean that up

**Comment by TonyGiorgio** [comment]
This can be closed right? I don't think I've seen this anymore, unless it's actually from a channel utxo.
