### ISSUE TITLE
Wallet is asking for me to set up a new lightning channel even though I have inbound liquidity

### ISSUE THREAD

**Issue by bendegedit** [MutinyWallet/mutiny-web#1094]
I have over 150,000 sats inbound liquidity, but I am being asked to add over 50,000 sats liquidity for a <5000 receive payment. Could someone explain why? Thank you.

**Comment by TonyGiorgio** [comment]
Upload logs

**Comment by bendegedit** [comment]
It is a general question, but here you go. [mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15098554/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Inbound capacity is an estimate but it's largely dependent on mempool fees and the reserves necessary to transact. Mempool fees were high last week but they are better now. Try again, and if you're having issues still, ensure the channel is online, because I see some disconnections too.

**Comment by bendegedit** [comment]
Hi Tony, thanks for your reply. My question was a general one borne out of a lack of technical knowledge, rather than a specific one about my issues, which resolved themselves when the mempool calmed down - as they always do. Rephrasing the question, as long as the appropriate channels between nodes have already been opened and there is ample in-bound liquidity in the channel, why would on-chain fees be a factor? I'm almost definitely missing something, but perhaps you could share a link to a resource I could read so I don't come off as such a rube? Thanks again!

**Comment by bendegedit** [comment]
Thank you Tony. Much appreciated. I did not fully grok the dynamic resizing of the reserves in response to the fee market before.
