### ISSUE TITLE
The buttons on payment result pages do not go home

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#1096]
Both successful or failed/pending payments do not go home like users would expect. They seem to go to the "search" page which is how they start off with in a "paste invoice" flow.

**Comment by futurepaul** [comment]
Doesn't go anywhere or doesn't go home? It's meant to take them back if there's a "back" to go to (like search or chat). The language should be fixed to reflect it in that case.

**Comment by TonyGiorgio** [comment]
I've noticed this for successful payments too. The nice button also goes back to the invoice pasting screen.

**Comment by markskram** [comment]
Note: When you receive a payment, the Nice button does take you home. It's only on the send side.
