### ISSUE TITLE
Very high memory usage & lost balance in fedimint

### ISSUE THREAD

**Issue by Yonle** [MutinyWallet/mutiny-web#1098]
Lost lot of sats and Mutiny just kept crashes in my phone during transaction due to out of memory, leading to numbers of sats being lost.

When opened in desktop, The balance only recovers at the small amount, but then also reveals that the memory usage is very big.
![Chromium tab on mutiny with developer tools showing console logs](https://image.nostr.build/921c6a1d89d45fa57b038a7bfacc410049897f1a04de1343607776c513fa5d1f.png)
_This is from 799 sats to this amount._

**Comment by TonyGiorgio** [comment]
@futurepaul what's the URL for the emergency page that doesn't load the node and other things?

**Comment by Yonle** [comment]
Could only get this for now. Will look forward for more logs again
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15138426/mutiny-logs.txt)

**Comment by Yonle** [comment]
[mutiny-logs (20).txt](https://github.com/MutinyWallet/mutiny-web/files/15138458/mutiny-logs.20.txt)

**Comment by Yonle** [comment]
I guess me losing my balance and the payment freezes because mutiny still tries to send sats with insufficient amount of sats for the fee. Still that should never happen but it ended up happening and ended up badly

**Comment by Yonle** [comment]
Checking the pending invoice gives 0 information about fees. it only slows 0

**Comment by Yonle** [comment]
```
refetching activity
index-DY19UVd9.js:123 ERROR mutiny-core/src/logging.rs:1372f33 2024-04-27 14:34:33.586 ERROR [mutiny_core::networking::socket:69] got an error reading event: Peer Sent Invalid Data
t.wbg.__wbg_error_8cf137381b3af25f @ index-DY19UVd9.js:123
6index-DY19UVd9.js:123 refetching activity
index-DY19UVd9.js:123 ERROR mutiny-core/src/logging.rs:1372f33 2024-04-27 14:35:18.069 ERROR [mutiny_core::networking::socket:69] got an error reading event: Peer Sent Invalid Data
t.wbg.__wbg_error_8cf137381b3af25f @ index-DY19UVd9.js:123
index-DY19UVd9.js:123 ERROR mutiny-core/src/logging.rs:1372f33 2024-04-27 14:35:34.597 ERROR [mutiny_core::networking::socket:69] got an error reading event: Peer Sent Invalid Data
t.wbg.__wbg_error_8cf137381b3af25f @ index-DY19UVd9.js:123
index-DY19UVd9.js:123 ERROR mutiny-core/src/logging.rs:1372f33 2024-04-27 14:35:34.606 ERROR [mutiny_core::networking::socket:69] got an error reading event: Peer Sent Invalid Data
t.wbg.__wbg_error_8cf137381b3af25f @ index-DY19UVd9.js:123

```
In console log

**Comment by Yonle** [comment]
[mutiny-logs (41).txt](https://github.com/MutinyWallet/mutiny-web/files/15138511/mutiny-logs.41.txt)

**Comment by futurepaul** [comment]
> @futurepaul what's the URL for the emergency page that doesn't load the node and other things?

app.mutinywallet.com/settings/emergencykit

**Comment by Yonle** [comment]
[at this point, my mutiny wallet is practically unusable in my phone]

**Comment by Yonle** [comment]
This issue is either caused by misbehaving fedimint federation or something messed up in mutiny-node.

So usually, When payment is failed, Mutiny then will restore the balance to your wallet. But if you keep doing it over and over again, which then randomly crashes at the pending stage, Mutiny will not restore your balance for some weird reasons.

That part is where weird things happen. As you try to zap without preserving atleast 1% of your balance (even with fedimint), Sometime fee checking just fails and gives 0 to mutiny. When that happens, You could basically try to send the entire balance of your wallet. But that will make another big disaster, which is what happend to me.

Once the second bug happens, The Fedimint federation that you joined will basically says "no" to every single [send] requests that you want to, and the balance will somewhat recover, except it wasn't and will consume A LOT of memory without reasons, which then leading to crash due to out of memory.

If you try to open again, Your balance will looks like it was cutted. Your previous sats invoice that pending or failed will never restored to your balance again. If only you try to send sats again, The memory usage will go spike up to 110% and then crashes your app or browser, again.

Trying to open again will make it refresh the balance. But still you will not be able to do anything with it as every single payment attempts that you try will simply gives pending result while the memory usage goes spuking up.

If that happens, congratulations. The only way out is to get out from the federation and use on-chain or other federation.

**Comment by TonyGiorgio** [comment]
Try the new version released yesterday and upload logs again if that doesn't work. It's possible it's just due to a stuck payment and it'll resolve itself when it times out.

**Comment by Yonle** [comment]
> Try the new version released yesterday and upload logs again if that doesn't work. It's possible it's just due to a stuck payment and it'll resolve itself when it times out.

Noticed same slowdown at startup as previous version did. Will report further

**Comment by Yonle** [comment]
Some pending invoices are succesfully sent.

**Comment by Yonle** [comment]
Memory usage still goes high to 1 GB which is unusual. Will check on mutiny-logs tomorrow as i am away from laptop

**Comment by Yonle** [comment]
On Android app, 0.6.8, app got killed due to OOM during `Loading: Setup`. Unable to get logs.

**Comment by Yonle** [comment]
### Notable note
Memory usage and startup duration dropped when defederated. Trying to join to the same federation again will lead to the same problem with the memory usage and startup duration

**Comment by Yonle** [comment]
Memory usage is in 900 MB after startup
![image](https://github.com/MutinyWallet/mutiny-web/assets/63401712/3a11989d-acfc-41f4-9802-5f6599720a7b)
Then drops to 600 MB after this
![image](https://github.com/MutinyWallet/mutiny-web/assets/63401712/121b74b9-3d00-4eae-bb86-04155c5237dc)

**Comment by Yonle** [comment]
Pressing [Download Logs] instantly spikes the memory usage to 3.2 GB.

**Comment by Yonle** [comment]
[Uploading mutiny-logs (45).txt…]()

**Comment by Yonle** [comment]
[mutiny-logs (45).txt](https://github.com/MutinyWallet/mutiny-web/files/15148465/mutiny-logs.45.txt)

**Comment by Yonle** [comment]
Chrome freezes. No result even after waiting for minutes for chrome to resolve.
![Screenshot from 2024-04-29 19-03-46](https://github.com/MutinyWallet/mutiny-web/assets/63401712/84cfc321-329a-4d6c-b11c-ad9ca6966e40)

Force stopping the chrome:
![image](https://github.com/MutinyWallet/mutiny-web/assets/63401712/c37c74e0-216f-4272-a0d2-0d8dbbfcfdeb)

**Comment by TonyGiorgio** [comment]
We'll take a look at the logs this week to see if we can find anything. Thank you for providing that.

**Comment by TonyGiorgio** [comment]
Every now and then I see connection issues when it starts up. I also see some times where the nodes and everything shuts down. Are you manually stopping the node by chance?

It also seems like it occasionally works? I still see some times where invoices are created or attempted to be paid. I'm unsure if you're seeing issues every single time you start up, or if it's occasionally working, because the logs indicate that it occasionally works.

**Comment by TonyGiorgio** [comment]
Could you describe your network setup? Are you using tor, what are you internet speeds, location, etc? All of this seems connectivity related. If it can't save to remote storage, or connect to the federations, all of this will cause issues.

**Comment by Yonle** [comment]
> Every now and then I see connection issues when it starts up. I also see some times where the nodes and everything shuts down. Are you manually stopping the node by chance?
> 
> It also seems like it occasionally works? I still see some times where invoices are created or attempted to be paid. I'm unsure if you're seeing issues every single time you start up, or if it's occasionally working, because the logs indicate that it occasionally works.

Well. This is happening because the browser lags. Trying with firefox won't give the networking issue. But will took a very long loading time.

**Comment by Yonle** [comment]
> Could you describe your network setup? Are you using tor, what are you internet speeds, location, etc? All of this seems connectivity related. If it can't save to remote storage, or connect to the federations, all of this will cause issues.

I am not using tor. Just an normal mobile internet that are stable. Average speed is 1.5 MB/s. Location is Indonesia.

**Comment by TonyGiorgio** [comment]
> Average speed is 1.5 MB/s

That's not very quick, there's probably around 30 or so mb's that is required, so it makes sense that it takes awhile to load. Everything in the logs indicates that various components that are taking awhile to load are related to things being pulled down from the network. There's nothing we can do to make that any smaller or quicker.

If you want to go into the "performance" tab in your browser dev console and record the a performance profile and upload it once it goes through the setup phase, we can confirm this, but I continue to suspect that it's internet related and there's nothing we can do.

**Comment by Yonle** [comment]
> > Average speed is 1.5 MB/s
> 
> That's not very quick, there's probably around 30 or so mb's that is required, so it makes sense that it takes awhile to load. Everything in the logs indicates that various components that are taking awhile to load are related to things being pulled down from the network. There's nothing we can do to make that any smaller or quicker.
> 
> If you want to go into the "performance" tab in your browser dev console and record the a performance profile and upload it once it goes through the setup phase, we can confirm this, but I continue to suspect that it's internet related and there's nothing we can do. 

Usually, at this speed it only takes around a minute to load. Still i don't believe this is my internet speed issue at all if the memory usage is that unusual.

Tried opening this in my VPS that has higher speed than me. The tab crashes due to out of memory.

**Comment by Yonle** [comment]
Reconfigured, This happen in VPS.
![Screenshot_20240430-162043.png](https://github.com/MutinyWallet/mutiny-web/assets/63401712/6271bac7-c7a9-452c-a197-3d80268dd3cd)
![Screenshot_20240430-162338.png](https://github.com/MutinyWallet/mutiny-web/assets/63401712/ec4e3eb3-abea-4898-8cbf-9a548081fd7a)
![Screenshot_20240430-162402.png](https://github.com/MutinyWallet/mutiny-web/assets/63401712/e7a2aa64-7e72-4237-b3bb-b80e9c40c6aa)

**Comment by Yonle** [comment]
Performance profiler here.
Note on slowdown and idle due to switched to swap in HDD.

[Trace-20240430T215446.json](https://github.com/MutinyWallet/mutiny-web/files/15166630/Trace-20240430T215446.json)

**Comment by Yonle** [comment]
Any update on this?

**Comment by TonyGiorgio** [comment]
Thanks for the profiler. It seems specific to your device, setup, internet connection, etc. There is not high memory usage coming from Mutiny, it never gets above 38MB of memory. There is also considerable delay from the network requests. Can't help you here.
