### ISSUE TITLE
Swap from fedi button not showing in android

### ISSUE THREAD

**Issue by timvak** [MutinyWallet/mutiny-web#1099]
Hey guys,

im playing with the fedimint feature and want swap from fedi to ln but the swap button is not showing.
Ive got enough inbound liquidity in the existing channel.
And im on the android app. Do you need logs for this?

![IMG_20240427_154716](https://github.com/MutinyWallet/mutiny-web/assets/71341469/7f9f92d8-485b-4b68-8782-a4e1f9ef8fcc)

**Comment by benthecarman** [comment]
You need 100k sats, but this feature is temporarily disabled while we track down a bug with it

**Comment by timvak** [comment]
✅ np ill keep an eye out for the fix thanks for the fast reply
