### ISSUE TITLE
Payments stuck at pending

### ISSUE THREAD

**Issue by cjoshreid** [MutinyWallet/mutiny-web#1107]
any invoice or LNURL I try to pay gets stuck pending. I have attempted to send out to multiple wallets. 

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15142162/mutiny-logs.txt)

**Comment by cjoshreid** [comment]
The payments get withdrawn from my total. Stay pending for a few hours or a day. Then disappear with the balance added back to the total. But I cannot pay an invoice.

**Comment by benthecarman** [comment]
it looks like you disconnecting and reconnecting while trying to make a payment. Try to ensure you have a stable connection and your channels are online
