### ISSUE TITLE
Failed to find route 

### ISSUE THREAD

**Issue by msparks23** [MutinyWallet/mutiny-web#1108]
Trying to pay invoices I get a long wait time then I get this.. 

I have plenty of Sats in the wallet. 

![Screenshot_20240428-084917](https://github.com/MutinyWallet/mutiny-web/assets/28021909/2b7da550-e68b-472d-a04b-a877c3d69c14)

**Comment by benthecarman** [comment]
if you don't provide logs there isn't much we can go off. Payment reliabilty is down right now because our LSP cannot handle the load of all the new users. We recommend trying the fedimint option currently
