### ISSUE TITLE
3 payments lost

### ISSUE THREAD

**Issue by hook7** [MutinyWallet/mutiny-web#1112]
A strange thing happened today on my Mutiny address 3 payments that I sent correctly from another wallet of mine did not arrive.
What can I check?
![Screenshot_20240430-175333](https://github.com/MutinyWallet/mutiny-web/assets/21236725/b313449a-78e9-46f7-affa-5e25939e1cc0)
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15167687/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
I see some of them being claimed: 

```
fc11 2024-04-30 12:38:11.647 INFO  [mutiny_core::hermes:626] Claimed external receive for 21000 msats!
fc11 2024-04-30 12:38:11.652 INFO  [mutiny_core::hermes:614] Received ecash notification for 42000 msats!
fc11 2024-04-30 12:38:14.601 TRACE [lightning_background_processor:693] Calling OnionMessageHandler's timer_tick_occurred
fc11 2024-04-30 12:38:18.136 INFO  [mutiny_core::federation:645] External receive claimed!
fc11 2024-04-30 12:38:19.372 TRACE [mutiny_core::federation:952] start timeout stream futures
fc11 2024-04-30 12:38:19.372 TRACE [mutiny_core::federation:967] Streamed Outcome received: Created
fc11 2024-04-30 12:38:20.450 INFO  [mutiny_core::hermes:626] Claimed external receive for 42000 msats!
fc11 2024-04-30 12:38:21.036 TRACE [mutiny_core::federation:967] Streamed Outcome received: Funded
fc11 2024-04-30 12:38:25.770 TRACE [lightning_background_processor:693] Calling OnionMessageHandler's timer_tick_occurred
fc11 2024-04-30 12:38:33.634 TRACE [lightning_background_processor:693] Calling PeerManager's timer_tick_occurred
fc11 2024-04-30 12:38:33.634 TRACE [lightning::ln::peer_handler:2335] Disconnecting peer with id 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0 due to ping/handshake timeout
fc11 2024-04-30 12:38:33.634 DEBUG [lightning::ln::channelmanager:8854] Marking channels with 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0 disconnected and generating channel_updates.
fc11 2024-04-30 12:38:33.635 TRACE [lightning_background_processor:693] Rebroadcasting monitor's pending claims
fc11 2024-04-30 12:38:33.635 DEBUG [mutiny_core::networking::proxy:107] closed websocket
fc11 2024-04-30 12:38:34.259 TRACE [mutiny_core::federation:967] Streamed Outcome received: Success { preimage: "ab6fbb714237541529598934475b3e4d2b637cfcae0eb59912401e2f242c8adc" }
fc11 2024-04-30 12:38:34.259 TRACE [mutiny_core::federation:971] Streamed Outcome final, returning
fc11 2024-04-30 12:38:34.259 TRACE [mutiny_core::federation:992] Done with stream outcome, status: Succeeded
fc11 2024-04-30 12:38:34.259 DEBUG [mutiny_core::federation:730] Saving updated payment
```

I'm guessing that some of them are not showing up in the UI? Another thing, it looks like the wallet was restarted as some of them are being claimed. Can you confirm that your balance is not correct? Also do you use this wallet on multiple devices?

**Comment by hook7** [comment]
"I guess some of them are not displayed in the user interface."
No indeed they are not displayed

"Another thing, it looks like the wallet has been restarted as some of them have been claimed."
Yes I tried restarting the wallet to see if they appeared in the UI

"Can you confirm that your balance is incorrect?"
Honestly no.
So you mean to tell me that the payments have arrived but due to a UI issue they are not showing up in the list?

"Also, do you use this wallet on multiple devices?"
No only from android app

**Comment by TonyGiorgio** [comment]
> So you mean to tell me that the payments have arrived but due to a UI issue they are not showing up in the list?

Yes, it's possible. Perhaps double check your balance, try again, and see if there's any issue. Another thing you can try is to restore your wallet again. The wallet keeps track of the last payment you received through nostr DMs and if there was an issue there, it might have missed some older ones. But first just try again and leave it opened for a few seconds.

**Comment by hook7** [comment]
OK, problem solved.
With the restore the balance is now correct and the missing payments have appeared.

Thank you very much

**Comment by TonyGiorgio** [comment]
We'll try to fix this easier than having a restore happen. I'll transfer this issue over to our node repo and track it until it's fixed. Thanks for trying that and reporting it.
