### ISSUE TITLE
TOR not working. LAN works

### ISSUE THREAD

**Issue by tulla2020** [MutinyWallet/mutiny-web#1113]
hey guys. just spun up mutiny wallet via start9 server. LAN works flawlessly. TOR takes forever to LOAD...and then when it does...it shows zero sats. i can see my primal NOSTR account, so its me...but no sats. i reloaded wallet, still didnt work.

**Comment by benthecarman** [comment]
Your balance won't show up unless you restore from your backup file on start9.

**Comment by tulla2020** [comment]
ok
