### ISSUE TITLE
Own profile is auto-added as a contact

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#1117]
When I make a new wallet it generates a profile. After clicking around a bit (not exactly sure what triggers it) I end up with myself added as a contact. I've noticed this in the existing mutiny and in the new webworker version.

![Screenshot 2024-05-02 at 2 27 56 PM](https://github.com/MutinyWallet/mutiny-web/assets/543668/a7c5cc15-f4dc-4fde-b263-8fc460e1dffb)

![Screenshot 2024-05-02 at 2 30 30 PM](https://github.com/MutinyWallet/mutiny-web/assets/543668/26e9bc9b-8b45-4464-984c-47d971cc708c)

Seems like a @benthecarman problem

**Comment by TonyGiorgio** [comment]
I've noticed that too and haven't figured out why

**Comment by benthecarman** [comment]
Yeah this makes importing your nsec into other clients better. Should probably just filter it from the top nav
