### ISSUE TITLE
Issues--> "Delete Everything"--> attempt to regenerate wallet from seed

### ISSUE THREAD

**Issue by stevednm** [MutinyWallet/mutiny-web#1119]
Have encountered numerous issues with Mutiny Wallet during this initial trial using the PWA version in Linux with the Firefox, Chromium, Google Chrome and Brave web browsers. Trying to address the issues any way I could think of, seemed to compound them, so decided to try to start fresh. Asked and confirmed in Mutiny Wallet server at Discord that "Danger Zone-->Delete Everything" would not make the situation unrecoverable, if I had the seed words. Clicked "Delete Everything" (in Mutiny Wallet in Firefox browser for Linux). Waited a few minutes, cleared all browser data (cookies, persistent storage, etc.), opened mutinywallet.com website and disabled the browser's "Site protections" in order to make communication between the web browser and the mutinywallet.com website as unrestricted as I could, and attempted to restore wallet from the seed words.

Process failed with error message--
`Failed to load Mutiny
Error: Failed to read data from storage.
Reload`

Reload timed out. Saved Mutiny-logs.txt. Waited several minutes. Closed Firefox, launched Chrome browser, attempted to restore wallet with seed words; same result. Installed Mutiny Wallet (v 0.6.8) for Android on phone; same errors/results.

Mutiny-logs.txt quoted and attached.

> e3da 2024-05-03 15:33:43.625 TRACE [mutiny_core:845] Checking device lock
e3da 2024-05-03 15:33:43.625 INFO  [mutiny_core:847] Current device lock: DeviceLock { time: 1714749143, device: "b80145b9-a0ec-452c-9751-6f13045ca349" }
e3da 2024-05-03 15:33:43.807 TRACE [mutiny_core:850] Device lock set: took 182ms
e3da 2024-05-03 15:33:43.808 INFO  [mutiny_core::nodemanager:330] Building node manager components
e3da 2024-05-03 15:33:43.840 DEBUG [mutiny_core::gossip:181] Previous gossip sync timestamp: 0
e3da 2024-05-03 15:33:43.841 TRACE [mutiny_core::gossip:221] Gossip sync/Scorer initialized in 0ms
e3da 2024-05-03 15:33:43.842 TRACE [mutiny_core::nodemanager:373] Node manager Components built: took 33ms
e3da 2024-05-03 15:33:43.842 DEBUG [mutiny_core::nodemanager:394] Building nodes
e3da 2024-05-03 15:33:43.842 INFO  [mutiny_core::node:357] initializing a new node: Some("ab6fc598-c3a9-0a9c-7865-4821107131e4")
e3da 2024-05-03 15:33:43.864 INFO  [mutiny_core::node:417] creating lsp client
e3da 2024-05-03 15:33:43.865 INFO  [mutiny_core::node:425] lsp config matches saved lsp config
e3da 2024-05-03 15:33:43.865 DEBUG [mutiny_core::ldkstorage:212] Reading channel manager from storage
e3da 2024-05-03 15:33:43.911 INFO  [lightning::ln::channelmanager:10363] Successfully loaded channel 4d40a6dcb74f83eaf39e4adeb9d553f5383d60da93d7944f985e4a0c730b7795 at update_id 15 against monitor at update id 14
e3da 2024-05-03 15:33:43.911 ERROR [lightning::ln::channelmanager:10643] A ChannelMonitor is stale compared to the current ChannelManager! This indicates a potentially-critical violation of the chain::Watch API!
e3da 2024-05-03 15:33:43.911 ERROR [lightning::ln::channelmanager:10644]  The ChannelMonitor for channel 4d40a6dcb74f83eaf39e4adeb9d553f5383d60da93d7944f985e4a0c730b7795 is at update_id 14 with update_id through 14 in-flight
e3da 2024-05-03 15:33:43.911 ERROR [lightning::ln::channelmanager:10646]  but the ChannelManager is at update_id 15.
e3da 2024-05-03 15:33:43.911 ERROR [lightning::ln::channelmanager:10647]  The chain::Watch API *requires* that monitors are persisted durably before returning,
e3da 2024-05-03 15:33:43.911 ERROR [lightning::ln::channelmanager:10648]  client applications must ensure that ChannelMonitor data is always available and the latest to avoid funds loss!
e3da 2024-05-03 15:33:43.911 ERROR [lightning::ln::channelmanager:10649]  Without the latest ChannelMonitor we cannot continue without risking funds.
e3da 2024-05-03 15:33:43.911 ERROR [lightning::ln::channelmanager:10650]  Please ensure the chain::Watch API requirements are met and file a bug report at https://github.com/lightningdevkit/rust-lightning

Will try to troubleshoot with your suggestions. Or, if recovery seems unlikely, perhaps whoever is at the other end of the lightning channel I opened can or will force-close the channel. I originally sent on-chain bitcoin into the Mutiny wallet, then used the swap-for-lightning button in Mutiny, which opened one channel, but with 100% outbound liquidity and 0% inbound.

Thanks.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15202199/mutiny-logs.txt)

**Comment by stevednm** [comment]
Still no luck regenerating the wallet with the seed words, after waiting hours between attempts, using several different browsers. Same errors as on original post above.

It's possible to create a new wallet that has new seed words, but I have not been able to reconstruct or access the old wallet long enough, or at all, in order to try to recover/move funds. If you were able to identify and force-close the lightning channel on the Mutiny Wallet server (or Lightning service provider), would that release the funds back into the BTC blockchain and move them back to the original sender?

Thanks.

**Comment by benthecarman** [comment]
Looks like the same issue as #919

The next LDK release will allow us to custom handle this issue and hopefully recover more gracefully from this

**Comment by benthecarman** [comment]
Hey, I got our recovery tool working again, you can check it out here: [MutinyWallet/mutiny-data-recovery@v0.1.1 (release)](https://github.com/MutinyWallet/mutiny-data-recovery/releases/tag/v0.1.1)

This will force close your channels and allow you to recover your funds on-chain
