### ISSUE TITLE
Tag editor dropdown bugs

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#112]
Should show recents in dropdown list, both on send and receive

Also dropdown needs float over top of the UI somehow, not sure why it does this it didn't always do this

![IMG_1343](https://github.com/MutinyWallet/mutiny-web/assets/543668/9aa9f3be-d889-42c5-8cc9-f4592be5f854)

**Comment by benthecarman** [comment]
we no longer have this
