### ISSUE TITLE
Funds not showing up in Mutiny wallet

### ISSUE THREAD

**Issue by JETOUN** [MutinyWallet/mutiny-web#1121]
Hello, I am new to Mutiny wallet.  I am having trouble seeing the balance that I sent to Mutiny wallet from Aqua.  

Steps.
1. Generated lightning invoice via mutiny wallet browser
lnbc72750n1pnr2klgdqqpp55mu3vegwalu4kcttf3faxv9ypywuu4xdeetgphha79q964s0vzxssp5fv8t0vlv30dxkkqmqf9fe9ks693pyfawcylug0xsvg4zm2fv0caq9qrsgqcqpjnp4qtsrpwfrwcjn4z6kfsaakmh6ycvuszuvxpsy9l5ywpyqlpp4z4jyuxqyz5vqrzjqtwnlnd2z7umeqalwyu0h6596r5r8pdx3d0u37vnxevv3msyv38ksqqqqqqqqqqqzcqqqqqqqqqqqqqqrc7eqlgpudwye65l4xu34may6kfx2ea0jqf2yufn9uhfev8ltp3fuhnuelv292zkstg6qa0nfzvuvrvxr5xqxt5adtrgjvx6lm0q7jghsqqmzygt

2. Sent via Aqua to Mutiny. In Aqua,  the funds decreased (sent) but never showed up in Mutiny.
Transaction ID
e3833f04ce65397e407d08e8b5703d77f1f9a093af4f988bbebf9bb70a40f13c

3. Observed funds not received in Mutiny wallet browser or mobile app.

Note: I tried this two times previously and it was successful (the funds showed up in Mutiny) so I am not quite sure why this time it didn't work. I am using Bitcoin Atlantis Federation.

Any help, I would appreciate very much.

**Comment by TonyGiorgio** [comment]
If it didn't complete then the funds will be sent back on the sender side. Aqua is a liquid wallet, not a lightning wallet. So however the failed transaction process takes place with that wallet, it may take a few days.

If it's been longer than that, reach out to them and ask them for a preimage to provide proof that the payment completed. If no preimage, then the payment didn't take place and they should refund you. If they/you have a preimage, then we can investigate but it just sounds like the payment didn't complete, nothing we can do on our end.
