### ISSUE TITLE
Unable to delete Mutiny+ subscription

### ISSUE THREAD

**Issue by hook7** [MutinyWallet/mutiny-web#1130]
Unable to delete Mutiny+ subscription

I have just realised that although I cancelled my subscription to Mutiny+, the payment was still made without my consent.
Every time I reopen the app the subscription reappears without being able to cancel it.
Basically today the 16000 sats subscription was renewed without my permission.

Furthermore, the subscription was supposed to renew on 10 May, but instead it was automatically renewed today, 8 May

**Comment by TonyGiorgio** [comment]
This will be fixed in the next release, sorry about that.

**Comment by hook7** [comment]
Can I get back the 16,000 sats taken away unintentionally?
Thanks

**Comment by benthecarman** [comment]
do you have a lightning address we can send to?

**Comment by TonyGiorgio** [comment]
I've already handled this.
