### ISSUE TITLE
Bug: Duplicate Private Zaps - Display Issue

### ISSUE THREAD

**Issue by crimsonleaf363** [MutinyWallet/mutiny-web#1140]
**App Version**
0.6.8

**Android Version**
14

**Steps to reproduce**

1. Open Mutiny Wallet
2. Choose a recipient for your zap by entering their address or tapping on their avatar.
3. Enter a zap amount.
4. Enter a zap note.
5. Tap the "Confirm Send" button.
6. After receiving the "Payment sent" message, tap the "Nice" button.
7. Observe the real zap and duplicate are displayed in the wallet interface.

**Expected behaviour**
Only the confirmed zap should be visible in the wallet interface. 

**Additional Notes**

- The duplicate zap disappears when you close and reopen the application.
- Both zaps show identical invoices and preimages.

**Comment by TonyGiorgio** [comment]
Thanks for the report. This is already fixed in a release set to go out soon. Just a visual bug, the payments are not sent twice.
