### ISSUE TITLE
Channel Creation issues

### ISSUE THREAD

**Issue by Cashstachestashcache** [MutinyWallet/mutiny-web#1142]
Is there an upward limit for creating lightning channels (I doubt I hit it if there is one) I was moving funds around from a soon defunct wallet thinking anything about l above 200k would make a new channel? But it was sent to my federation. And when I try to create a new channel by swapping from the federation I get this. 
 https://image.nostr.build/04ba3648450922ae1dd722b93276502e9892dfde6848ff171a015b36b54759e2.jpg

**Comment by benthecarman** [comment]
This means the LSP isn't able to service new channels right now. I would check back later

**Comment by Cashstachestashcache** [comment]
Thank you Ben! 

Can you advise what later might mean? 

Is it like to many people are trying to make channels right now and I just have the shit end of that connection stick? 

Or is it like a just keep trying periodically because we have no idea sort of thing?
