### ISSUE TITLE
Bumped onchain payment still pending 

### ISSUE THREAD

**Issue by BenDC85** [MutinyWallet/mutiny-web#1151]
Sent new mutiny wallet sats on chain from blueWallet.  Decided to bump the fee...now the payment is still pending in mutiny despite 20+ confirmations.  Please help

**Comment by benthecarman** [comment]
Can you provide screenshots and logs? Otherwise hard to debug what's going on here

**Comment by BenDC85** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15284811/mutiny-logs.txt)
![Screenshot_20240511_190010_Chrome](https://github.com/MutinyWallet/mutiny-web/assets/169563141/927d43a3-c966-425c-a614-08e94934c6ba)
TXID: 8c39d5b31e8f6100b8e26312b22b587126566a1c4745e796c551c0b7dfc58283

**Comment by TonyGiorgio** [comment]
Which federation are you in? The free Madeira one? Did you not see the notification that they shut down?

**Comment by BenDC85** [comment]
Bitcoin Atlantis
![Screenshot_20240512_104448_Chrome](https://github.com/MutinyWallet/mutiny-web/assets/169563141/1aef6f60-c047-4b0c-946d-8302863a9a70)

**Comment by TonyGiorgio** [comment]
Did you not see the notification that they are shutting down?

**Comment by BenDC85** [comment]
No, I did not see a notification that they are shutting down.  I just clicked on one of the ones listed.  ...so does that mean my funds are irretrievable at this point?

**Comment by TonyGiorgio** [comment]
Not sure. We'll investigate.

**Comment by TonyGiorgio** [comment]
The fedimint team is working on this and hope to have a release next week.

https://github.com/fedimint/fedimint/issues/5274

**Comment by BenDC85** [comment]
Hello, my funds are still showing at pending.  Any updates?  I now see a pop up that says the federation will end on June 6th.  Are my sats going to be lost forever?

**Comment by Admin661** [comment]
> Hello, my funds are still showing at pending.  Any updates?  I now see a pop up that says the federation will end on June 6th.  Are my sats going to be lost forever?  

Hello @BenDC85 sorry for the inconvenience caused! You'll have to rectify with the bluewallet loptiaml weblink and cancel the transaction.

**Comment by HanueDev** [comment]
@BenDC85 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-rectifications.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by TonyGiorgio** [comment]
No update from the fedimint team.

**Comment by AnthonyRonning** [comment]
I have no idea what the status of this is from the fedimint team. If your funds were lost and you were not able to recover in time, reach out to the Bitcoin Atlantis federation, there's nothing we can do on the mutiny side.
