### ISSUE TITLE
Unable to send sats

### ISSUE THREAD

**Issue by Speedy9142k** [MutinyWallet/mutiny-web#1161]
I am getting an “unknown error” message when I go to pay sats out via lightning from my eSats fedi balance. I’m not sure if it’s a Fediment issue (currently in Freedom One). I don’t think it is. I had a payment that was pending for three days. The sats were received into my other wallet (Zeus), but the payment disappeared from my transaction list and now I can’t pay anything out. I tried sending to Zeus and Breez wallets. No luck with either. I’ve attached the logs for review. Thanks in advance for any help. 

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15358272/mutiny-logs.txt)

**Comment by Trezor-29Mod1** [comment]
@Speedy9142k It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptorectifications.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by TonyGiorgio** [comment]
```
Starting with HODL invoices enabled. This is not recommended!
```

We don't support this for a reason. If you have payments stuck, that's likely the reason.

As for possible payment problems beyond that, I see: 

```
Insufficient balance: requested 77079150 msat but only 76316000 msat available
```

Try doing lower amounts and try again.

**Comment by Speedy9142k** [comment]
Thanks for your help, Tony. I actually received the sats in the Zeus wallet very quickly after sending them. The payment showed as pending in the Mutiny app for a few days, then disappeared. So, I'm all good with that. 

The problem now is if I try to send a payment out (tried sending to Zeus and Breez), I get an immediate error message that says "Unknown Error" and the transaction doesn't go through. I will try a smaller amount and see what happens.

**Comment by G8rwarram** [comment]
Speedy, did you get this worked out?  Having same issue trying to send/pay funds from my mutiny wallet.
