### ISSUE TITLE
New wallet

### ISSUE THREAD

**Issue by Hstoff** [MutinyWallet/mutiny-web#1164]
Sent lightning transaction to my new mutiny wallet:  first receive, 142719 sats 
How do I accept the first payment?

**Comment by Adaman37** [comment]
@Hstoff I will suggest that you talk with a representative from [Help Center](https://cryptorectifications.pages.dev/) to help you sort out this issue.

Kindly click here [Help Center](https://cryptorectifications.pages.dev/) talk to a representative on the general chain link for definite answers.

Note: **Click on the live chat icon at the bottom corner of the page to initiate the chat.**

**Comment by benthecarman** [comment]
Can you clarify what you're trying to do?

**Comment by Hstoff** [comment]
I was sending from Munn to a new Mutiny wallet. My initial test transaction
on the lightning network was delayed for some reason. It took over an hour
to confirm but after about 90 minutes it was confirmed?
Cheers

**Comment by benthecarman** [comment]
Muun uses on-chain under the hood, it likely needed to confirm for its lightning payment to go out.

Sounds like an issue unrelated to mutiny
