### ISSUE TITLE
Failed to sync nostr: Failed to get nostr data

### ISSUE THREAD

**Issue by DireMunchkin** [MutinyWallet/mutiny-web#1165]
I'm using Mutiny Wallet on Android - I had to reset my phone at one point. After I restored Mutiny wallet I have an issue where I can't get my profile info on nostr to fetch any more. After I import my nsec it says "invalid nsec" or something like that, and then I have no profile metadata or contacts list.

I'm attaching the logs from the troubleshooting section in the app, it has a lot of these sorts of errors:
```
ff65 2024-05-22 14:05:49.447 ERROR [mutiny_core:1442] Failed to sync nostr: Failed to get nostr data.
```
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/15406422/mutiny-logs.txt)

**Comment by benthecarman** [comment]
what is the npub of the profile that you're trying to import?

**Comment by DireMunchkin** [comment]
`npub1mxrt3fyvaay4plrz7lwzurf80jjs2atmt2nn7z2ekgr9necl0jkqekkyq5`

**Comment by DireMunchkin** [comment]
This just started working again today - I didn't do anything else with the app to fix it. Closing as I can't reproduce.
