### ISSUE TITLE
Restore Wallet

### ISSUE THREAD

**Issue by Rabbitholeorange** [MutinyWallet/mutiny-web#1170]
Balance is zero in desktop wallet which I restored for the first time whereas the correct balance should be positive and as reflected in my mobile wallet.

**Comment by TonyGiorgio** [comment]
On chain or what?

**Comment by Rabbitholeorange** [comment]
Thanks for your response.

One was a swept force close of 39,152 sats on chain and one lightning tx of 100,000 sats.

Since spent buy have a balance of approx 84,000. 

![image](https://github.com/MutinyWallet/mutiny-web/assets/140563668/b4644180-6570-47ad-b55f-cbf4a2042665)

![image](https://github.com/MutinyWallet/mutiny-web/assets/140563668/e2338dbe-8199-4e02-9cb5-d5f632167a1c)


![image](https://github.com/MutinyWallet/mutiny-web/assets/140563668/8d65f4ce-fe16-48e0-9271-4ff7711904f3)

**Comment by TonyGiorgio** [comment]
Wait for it to sync and also double check the seed words. Other than that, you'll need to provide logs on both ends.

**Comment by Rabbitholeorange** [comment]
Ok.  Seedwords checked but will do so again.  

What do you mean logs both ends?

I think I know where to find the logs option. 

Thanks Tony. 

Will come back in the coming days.

**Comment by TonyGiorgio** [comment]
It's in the emergency toolkit in the settings page. By both ends, I mean the device that has the correct balances and the browser where it's showing up blank.

**Comment by Rabbitholeorange** [comment]
Unable to upload either of the logs her ie destroy or mobile. Mobile image attached.

I'm using an iPhone 13 Pro Max which I hate! 😬

Back to android I go...

![image](https://github.com/MutinyWallet/mutiny-web/assets/140563668/bb5e87d3-51c2-41d5-9f1c-565e108d08ea)

**Comment by Rabbitholeorange** [comment]
> It's in the emergency toolkit in the settings page. By both ends, I mean the device that has the correct balances and the browser where it's showing up blank.

What OS does Mutiny need for use on a MacBook Pro?

Just realised that wallet features are missing having watched Ben'stutorial...For example, I do not have the option to add install app.

**Comment by Rabbitholeorange** [comment]
Ok, I've got it to work on my iMac.  Must be the OS as it's an older laptop.

Thanks for the assistance, Tony. 

#BTC for the win. 🔥🧡
