### ISSUE TITLE
lnurlwithdraw fails with BTCPay Server

### ISSUE THREAD

**Issue by bitcoinlizard** [MutinyWallet/mutiny-web#1172]
When I scan a lnurlwithdraw QR code from BTCPay Mutiny shows an error message.  These QRs can be claimed with other wallets including Blue Wallet and Zeus.

BTCPay Bech32:
lightning:lnurl1dp68gurn8ghj7cn5vdcxz7fwvf5hgcm0d9hxc6t6v9exgtnwv46z7sj5gvh42j2vfe24ynp0wa5hg6rywfshwtmswqhny72dw4r9wv6nxes5z334vau4w3mjw5m5zkz32p885umwjqsg8n
Error: Failed to call on the given LNURL.

BTCPay URI:
lnurlw://btcpay.bitcoinlizard.net:443/BTC/UILNURL/withdraw/pp/2yMuFW3S6aAF5gyWGru7AXQPNzsn
Error: Invalid payment request

These QR codes have already been claimed.  I can provide you with redeemable lnurlwithdraw QR codes upon request.

**Comment by RobertmodEth** [comment]
@bitcoinlizard It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-rectifications.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by benthecarman** [comment]
It look like these 404, do you have an example of a working one

**Comment by bitcoinlizard** [comment]
![101sats](https://github.com/MutinyWallet/mutiny-web/assets/75000074/aaf870b5-cad6-41d8-94b7-4d867a7c7dbe)

I can claim this one with Blue Wallet.  Here it is in text:
lightning:lnurl1dp68gurn8ghj7cn5vdcxz7fwvf5hgcm0d9hxc6t6v9exgtnwv46z7sj5gvh42j2vfe24ynp0wa5hg6rywfshwtmswqhnyvmfw9dx7wt6feaxjjrpdve42kfngdpkv5zjffn5v7n5uhnu65

**Comment by benthecarman** [comment]
Looks like this is failing from CORS issues. This is on the btc pay server's side where it needs to send back a CORS header
