### ISSUE TITLE
Fedimint swap to lightning results in loss of funds. Please help recover funds.

### ISSUE THREAD

**Issue by nakoshi-satamoto** [MutinyWallet/mutiny-web#1173]
I was trying to swap 600,000 sats from fedimint balance to lightning. It is stuck in pending status and my funds are appearing as lost. The decoded LN invoice says that the invoice is already expired.

How can I get my 600,000 sats back?

I think that most likely the invoice expired but Mutiny refuses to "fail" the swap, so it is stuck in pending forever.

**Comment by nakoshi-satamoto** [comment]
Before anyone says "you should not have risked 600,000 in fedimint", Mutiny forces deposits to go into fedimint, I did not have a choice. I simply went to recieve and gave the sender an onchain address. It showed up and after confirmed I tried to sweep the funds from fedimint to self custody (swap to lightning).

Did I lose my funds? This is alot of sats.

**Comment by TonyGiorgio** [comment]
Upload logs.

**Comment by nakoshi-satamoto** [comment]
Mr. @TonyGiorgio thank you for your response to this. Where do I find the log files? I am using the web based app.

**Comment by TonyGiorgio** [comment]
Emergency toolkit in the settings.

**Comment by nakoshi-satamoto** [comment]
Am I safe to upload logs here or does it contain potentially sensitive info?

**Comment by nakoshi-satamoto** [comment]
[mutiny-logs.txt](https://github.com/user-attachments/files/15523560/mutiny-logs.txt)
![IMG_1391](https://github.com/MutinyWallet/mutiny-web/assets/161100720/d778bf93-428c-4cfc-9c3f-d7af7b0d9c55)
![IMG_1392](https://github.com/MutinyWallet/mutiny-web/assets/161100720/f9b69c88-5e28-4255-9e29-2f20cb353da3)

**Comment by nakoshi-satamoto** [comment]
@TonyGiorgio  I uploaded two screenshots and the log file above.

**Comment by nakoshi-satamoto** [comment]
My balance does not show the 593,044 sats , and transaction is stuck in pending. I did try the "resync wallet" and "stop node" option under the admin section then close and re-open the tab to no effect.

**Comment by TonyGiorgio** [comment]
Stuck payments can take a few days to resolve. Nothing looks out of the ordinary. If the funds are not unstuck by Monday then feel free to open again.
