### ISSUE TITLE
How do I fund a self-custody Lightening Channel

### ISSUE THREAD

**Issue by Bitcoinium** [MutinyWallet/mutiny-web#1176]
Hi Tony and Ben. I watched the BTC Sessions tutorial on Mutiny Wallet  but I do not have the option to swap funds from on-chain to open a self-custody lightening channel. 

please advise.

**Comment by benthecarman** [comment]
Can you provide screen shots, logs or anymore info. Otherwise we don't have much to go off of to help you

**Comment by Bitcoinium** [comment]
I think it is a case of not updating the app. I see the swap option now. But fees are high lol. I'll close the issue soon once I successfully open the channel.

**Comment by Bitcoinium** [comment]
Channel done, thanks.
