### ISSUE TITLE
QR scanner should handle LN invoices that start with the "lightning:" prefix.

### ISSUE THREAD

**Issue by blackcoffeexbt** [MutinyWallet/mutiny-web#1177]
The QR scanner in Mutiny does not recognise QR codes that have the prefix "lightning:". These should be recognised as this prefix is commonly used and allows the generic camera app on mobile devices to launch a lightning wallet.

**Comment by benthecarman** [comment]
Mutiny already handles this, just tested. May be an issue with your camera
