### ISSUE TITLE
Channel close - Peer's feerate much to low

### ISSUE THREAD

**Issue by KayTX** [MutinyWallet/mutiny-web#1189]
iOS App: 1.7.1
Channel was closed by app / (lsp?).
**Reason:** "_Channel closed because of an exception: Peer's feerate much to low. Actual: 2219. Our expected lower limit: 2250_"

I assume the two numbers above are the expected fee in sats of the force close tx.
The broadcasted tx is stuck with a fee of ~2500 sats ( ~ 9 sats/vB) in mempool. The current fee rate recommendation (mempool.space) for low priority is 41 sats/vB.

My outbound liquidity before closure was ~50000 sats.

**Extract from log file**

- _ERROR [lightning::ln::channelmanager:8815]  Force-closing channel: Peer's feerate much too low. Actual: 2219. Our expected lower limit: 2250_

- _DEBUG [lightning::ln::channelmanager:2848]  Finishing closure of channel due to Channel closed because of an exception: Peer's feerate much too low. Actual: 2219. Our expected lower limit: 2250 with 0 HTLCs to fail_

**Questions**
1) Is this channel closure a bug?
2) Why was such a low fee rate chosen?
3) How can I prevent a channel closure like this?

Thank you.

PS: You do a **great** job!

**Comment by markskram** [comment]
Hey @KayTX, this is poor fee estimation with the LSP. We are working to resolve various issues with the LSP. At the moment there isn't much you can do to avoid this. Looking for ways to improve this through LDK config options.

**Comment by Astaroth678** [comment]
I also had a force closure because of a low feerate. Will the on chain transaction be claimable in the near future? If so, will this appear directly in the wallet?

**Comment by markskram** [comment]
It can take anywhere from 3-14 days for the Lightning Network to settle the funds back on chain.
