### ISSUE TITLE
Unable to send a Lightening Transaction

### ISSUE THREAD

**Issue by Bitcoinium** [MutinyWallet/mutiny-web#1192]

**Comment by Bitcoinium** [comment]
I have a Lightening channel open with adequate inbound and outbound liquidity to cover the $100 transaction to Cashapp. But it keeps failing. I checked my channel is online and I attempted a refresh using the admin page. Please advise.
![IMG_1872](https://github.com/MutinyWallet/mutiny-web/assets/152038074/7e898e34-11af-4ab8-b9d3-c897ccc67ecf)

**Comment by markskram** [comment]
We're having issues with our Lightning Service Provider. Have you tried it multiple times? It can fail the first time and succeed on a subsequent attempt.

**Comment by Bitcoinium** [comment]
Hi Mutiny Wallet. I attempted the same transaction with Strike and it also failed. I now believe the problem is with Cashapp placing limits on inbound lightening transactions. I am closing this issue. Thank you.
