### ISSUE TITLE
Massive channel force close! Why?

### ISSUE THREAD

**Issue by Thebitcoinyogi** [MutinyWallet/mutiny-web#1197]
I opened up mutiny on a laptop browser using my seed phrase and then for some reason that triggered a big force close of my lightning channel and drew down my bitcoin balance. Any idea why this happened?! https://mempool.space/tx/e9bb496275a0737221436ad132ce9a5958caef80ba90f74d3a10bd222dfad028

**Comment by benthecarman** [comment]
If you click on the force closure it will give you a reason why. Otherwise if you can provide logs we can get to the root issue

**Comment by Thebitcoinyogi** [comment]
[mutiny-logs jg.txt](https://github.com/user-attachments/files/15744586/mutiny-logs.jg.txt)
 heres my logs

**Comment by Thebitcoinyogi** [comment]
![image](https://github.com/MutinyWallet/mutiny-web/assets/172078264/9e704280-5e59-4574-89d9-8587366bef6f)

**Comment by benthecarman** [comment]
> 7633 2024-06-07 19:37:36.154 ERROR [lightning::ln::channelmanager:8815] Force-closing channel: Peer's feerate much too low. Actual: 3170. Our expected lower limit: 3250
> 7633 2024-06-07 19:37:36.155 DEBUG [lightning::ln::channelmanager:2848] Finishing closure of channel due to Channel closed because of an exception: Peer's feerate much too low. Actual: 3170. Our expected lower limit: 3250 with 0 HTLCs to fail

Yeah I see the same in your logs, this happens when the two lightning nodes disagree on the on-chain fee rates. Seems like the Voltage LSP has bad fee estimation right now with the fee spike and is causing this. Sorry about this, we're working to get switch LSPs soon due to issues, this being one of them.

**Comment by Astaroth678** [comment]
> > 7633 2024-06-07 19:37:36.154 ERROR [lightning::ln::channelmanager:8815] Force-closing channel: Peer's feerate much too low. Actual: 3170. Our expected lower limit: 3250
> > 7633 2024-06-07 19:37:36.155 DEBUG [lightning::ln::channelmanager:2848] Finishing closure of channel due to Channel closed because of an exception: Peer's feerate much too low. Actual: 3170. Our expected lower limit: 3250 with 0 HTLCs to fail
> 
> Yeah I see the same in your logs, this happens when the two lightning nodes disagree on the on-chain fee rates. Seems like the Voltage LSP has bad fee estimation right now with the fee spike and is causing this. Sorry about this, we're working to get switch LSPs soon due to issues, this being one of them.

Would you recommend waiting for the switch to occur to open another channel or can we open a larger channel now without worry of another force closure?

**Comment by benthecarman** [comment]
We'll be deploying a fix soon that should help fix this. May be best to wait until then
