### ISSUE TITLE
High Number of Lightning Channels Opened

### ISSUE THREAD

**Issue by stasgnikcats** [MutinyWallet/mutiny-web#1213]
I originally opened a lightning channel back in December [12/7/2023] and didn't realize there were about 19 other channels that opened between 12/6 and 12/7. Attached are a few log files from May and the logs for today. Hopefully you can find something useful in there and review with the LSP to see what might have gone wrong. 

I also opened a channel back in April [4/29/2024], so I'm guessing the other channels are erroneously opened and my wallet should only have two open channels. 

[Logs_05_27_24.txt](https://github.com/user-attachments/files/15827507/Logs_05_27_24.txt)
[Logs _05_28_24.txt](https://github.com/user-attachments/files/15827508/Logs._05_28_24.txt)
[Logs_06_13_24.txt](https://github.com/user-attachments/files/15827509/Logs_06_13_24.txt)

**Comment by benthecarman** [comment]
Logs don't go far back enough to garner anything useful, but I do see all the channels working in your logs. We'll reach out to the LSP about this, thanks
