### ISSUE TITLE
On chain balance not showing

### ISSUE THREAD

**Issue by z444p** [MutinyWallet/mutiny-web#1214]
Hi mutiny team! 

Loving the app so far, but I’ve run into an issue. I think it’s the same as the one described here:
https://github.com/MutinyWallet/mutiny-web/issues/1065

This should be the txid for my deposit from my external wallet to my mutiny on chain wallet. 
6a9dbd6e4a94d0b2b69a5589279e99968ffb2de4b6658dd2b855528ba9026eb7

I have tried both resyncing and restoring on a different device, balance doesnt appear. 

Is it possible to check if it’s the same issue? any advice to recover? Would appreciate any advice. 

Cheers!

**Comment by benthecarman** [comment]
Looks like this was deposited into a Fedimint, did you ever fee bump the tx or anything?

**Comment by benthecarman** [comment]
Also if you can provide any logs that'd be helpful

**Comment by z444p** [comment]
thanks! does this help? 

[mutiny-logs.txt](https://github.com/user-attachments/files/15832511/mutiny-logs.txt)

**Comment by z444p** [comment]
I haven't manually done anything with the tx like tried bumping it.

**Comment by benthecarman** [comment]
Do you know what federation this was to?

**Comment by z444p** [comment]
Should've been either 

b21068c84f5b12ca4fdf93f3e443d3bd7c27e8642d0d52ea2e4dce6fdbbee9df

c944b2fd1e7fe04ca87f9a57d7894cb69116cec6264cb52faa71228f4ec54cd6

Bitcoin principles and a freedom one are the ones I joined, but I'm not sure which it would've gone to.

**Comment by z444p** [comment]
FWIW I have tried recovering on a different device, and the balance is the same on my main and the second device.

**Comment by benthecarman** [comment]
you shouldn't be joining multiple federations unless you are transfering between the two

**Comment by z444p** [comment]
I see. Finding out the hard way I guess 😓 

Any advice on whether this is recoverable, and if so which fediment it could be in?

**Comment by z444p** [comment]
I haven't done much with the wallet since the above. It's still in the state of being between 2 federations. 

Is it safe to leave and if i do, anything I can do to attempt to recover from the Fedimint?

**Comment by TonyGiorgio** [comment]
Both of those federations are experiencing issues and you should leave them both.
