### ISSUE TITLE
Error: Load timed out

### ISSUE THREAD

**Issue by dveo1** [MutinyWallet/mutiny-web#1224]
keeps getting stuck on “loading: setup” when starting up. then a load timed out error. after multiple tries, it eventually worked so I tried sending funds out (just to be safe), was only using a couple of mints, no lightning channels. thankfully somehow got more than half of it out, but kept getting error messages when sending slightly larger amounts. now it’s back to the error again and won’t open. would love to start over with a new wallet, but have a custom address I don’t want to lose (and some funds stuck in there that can’t send out)

**Comment by TonyGiorgio** [comment]
Provide logs

**Comment by djveo** [comment]
[mutiny-logs.txt](https://github.com/user-attachments/files/15887267/mutiny-logs.txt)

**Comment by djveo** [comment]
[mutiny-logs.txt](https://github.com/user-attachments/files/15887356/mutiny-logs.txt)

**Comment by djveo** [comment]
was able to get in and move most of the funds out but still have some sats left in there. keeps getting stuck on loading on launch and won’t go past it now except for the error page again. enabled diagnostics as well in hopes that something can help. so sad to lose access to the wallet. been really liking mutiny as a much needed simple solution

**Comment by djveo** [comment]
I would be fine scrapping that wallet and starting over too, especially if that would clear any issues up, but I don’t want to lose my custom lightning address

**Comment by coinop-logan** [comment]
Facing the same issue. [logs](https://github.com/user-attachments/files/16143088/app.mutinywallet.com-1720527504247.log)

**Comment by benthecarman** [comment]
Sorry about this, we're aware of some potential causes and working on a fix

**Comment by coinop-logan** [comment]
@benthecarman not sure if this is the right place to ask, but can we get some sort of progress update? I'd really like to get that BTC freed up.

**Comment by AnthonyRonning** [comment]
Issue could be related to fedimint data. There's now a rescan fedimint data button in version 1.8 released today. Try that, it may take a long time.

**Comment by coinop-logan** [comment]
@TonyGiorgio  I don't see any button to rescan fedimint data, even after a hard refresh.
