### ISSUE TITLE
Wrong account balance. Can't send and receive sats- X unknown error

### ISSUE THREAD

**Issue by archjourneyai** [MutinyWallet/mutiny-web#1225]
Hi there. I am a subscriber in Mutiny wallet. Yesterday I received a big zap in a nostr client. When I checked my Mutiny balance the zaps where not there. I tried also to send some sats somewhere from my Mutiny wallet and I received a big X with "unknown error" msg.
People also told me in nostr that they can't zap me.

**Comment by TonyGiorgio** [comment]
If you restore from seed, it'll scan through the zaps again. A known issue we'll hopefully fix soon.

**Comment by archjourneyai** [comment]
right. Restore and everything is there 👍
