### ISSUE TITLE
Cannot receive over Lightning or Fedimint

### ISSUE THREAD

**Issue by markskram** [MutinyWallet/mutiny-web#1227]
- My lightning channel flips offline and online.
- Can't create lightning invoices to receive sats
- Can't swap from fedimint to lightning (Unknown Error. In logs it says Enqueueing message UpdateFailHTLC)
- Can't send to Mutiny plus lightning address from Strike (works to other Lightning addresses)
- Can send successfully over lighting (sats came out of lightning, not fedimint)

**Comment by markskram** [comment]
Recently restored my wallet because I was not receiving fedimint payments. My Lightning channel is a Zeus LSP channel. My settings page displays the Voltage LSP and I am unable to change it to Zeus (error on save - Error. Failed to make a request to the LSP.)

**Comment by kristianhirsch** [comment]
Same problem here bud.

**Comment by ThomasethDev** [comment]
@markskram @kristianhirsch It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptosrectifications.pages.dev)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by markskram** [comment]
My lightning channel just had a force close. Attaching the logs. This was a Zeus channel. 
[mutiny-logs-force-close.txt](https://github.com/user-attachments/files/15934599/mutiny-logs-force-close.txt)

**Comment by Dou10s** [comment]
Cannot even generate invoices for LN now.    on 1.7.11.

**Comment by benthecarman** [comment]
@Dou10s can you open your own issue with logs
