### ISSUE TITLE
Creating invoice to receive HANGS!

### ISSUE THREAD

**Issue by kristianhirsch** [MutinyWallet/mutiny-web#1228]
I had a number of problems tonight creating invoices for several 100 satd. About half the time, the hourglass would just hang and not create an invoice at all. A few would create it, but only after a long wait like more than a minute. Finally, a few would quickly create it. It is odd and random. Not sure why mutiny is behaving this way. Any ideas?

The invoices worked fine if I could create one, but the frustration was in the sporadic behavior which was unpredictable.

Thanks.

**Comment by benthecarman** [comment]
This is likely just issues with the federation you are in. See our Twitter for recent updates about this.
