### ISSUE TITLE
Not able to send Bitcoin from Fedimint to hardware wallet 

### ISSUE THREAD

**Issue by edjanx** [MutinyWallet/mutiny-web#1230]
Hello. I've transferred a few Bitcoin from a Sparrow wallet into my Mutiny Fedimint last night.

Today I've been trying to move these to cold storage but have experience nothing but the spinning red and white icon at the bottom of the screen after I paste in the Bitcoin address and the amount to send. 

So I tried to send it from the current Bitcoin Principles Mint to Freedom One, but that also still has the spinning red/white icon, and I'm afraid to close the window.

My latest attempts received the red X error screen instead of the ongoing spinning red and white circle

Is there a potential bug for some whole coins unable to get back to an on-chain wallet?

FWIW, I've tried several variations of smaller amounts with no success. Thanks for your help. 

Any insight on my potential ill advised liquidity test is appreciated.
[mutiny-logs-6-24.txt](https://github.com/user-attachments/files/15960006/mutiny-logs-6-24.txt)

**Comment by TonyGiorgio** [comment]
That federation is experiencing issues apparently and you should either contact them or see if it resolves. Nothing we can do here.
