### ISSUE TITLE
Cannot generate lightning invoice 

### ISSUE THREAD

**Issue by mpberry** [MutinyWallet/mutiny-web#1236]
When I got receive and try to generate an invoice to receive some sats I click the continue button and it just turns into a forever spinning wheel. I'm a new user and I'm in a fediment. I have received SATs prior to my wallet. 

![Screenshot_20240627-060836](https://github.com/MutinyWallet/mutiny-web/assets/7533851/5a7657fe-78d8-40b3-9f0a-6791a1ce2280)

**Comment by TonyGiorgio** [comment]
Which fedimint are you in?

**Comment by mpberry** [comment]
Freedom One fediment

**Comment by TonyGiorgio** [comment]
You need to get your funds off and leave that federation. 

https://x.com/MutinyWallet/status/1805346636660429021
