### ISSUE TITLE
Swapping fedi to lightning stuck at 'pending' 

### ISSUE THREAD

**Issue by exfrog** [MutinyWallet/mutiny-web#1238]
Yesterday, After a successful large swap from fedi to lightning, I attempted to swap the remaining balance (slightly less than before) , but the txn is stuck as 'pending'

Initially, the txn balance was not showing up in fedi or lightning or total balance, but today it looks like the swaped amount is back in my fedi and included in my total balance.  But trying to swap to LN again gives an error message 'swap must be above 100k sats' even though the txn is much larger. 

The previous, failed swap still shows as 'pending' in my activity.

**Comment by benthecarman** [comment]
if the balance is back in your balance it should be fine to retry, there is currently a bug where the swap error message persists, that can be safely ignored.

**Comment by exfrog** [comment]
When I retry, I get an error after previewing swap fee that the swap amount must be over 100k sats, and the swap is 8x that minimum amount...

**Comment by benthecarman** [comment]
there is currently a bug where the swap error message persists, that can be safely ignored.

**Comment by exfrog** [comment]
The only option presented is 'preview swap fee' which just persists the error message. 
There is no way to proceed past this screen and compete the swap that I can see.

**Comment by benthecarman** [comment]
the button should be clickable as long as you don't enter a number higher than your balance

**Comment by exfrog** [comment]
![Screenshot_20240628_092710_Chrome.jpg](https://github.com/MutinyWallet/mutiny-web/assets/36036563/75e8351a-e700-4ff0-936a-cee31f508070)

**Comment by TonyGiorgio** [comment]
Then just move your funds off to a different wallet.
