### ISSUE TITLE
Error trying to swap sats from Fedimint to lightning

### ISSUE THREAD

**Issue by dantzler** [MutinyWallet/mutiny-web#1239]
![Screenshot at 2024-06-28 12-30-32](https://github.com/MutinyWallet/mutiny-web/assets/7741403/108c017f-422a-4931-ac3c-c1eac8599f3f)

Given the recent DNS issues, I am trying to swap funds currently in Fedimint to Lightning. I am trying to swap >500k sats, but when I click 'Preview Swap Fee', I get an error saying 'Invalid amount entered. You need to swap at least  100k sats.'

I get this error on both Android 14 & web app on Chromium Version 126.0.6478.114 (Official Build) built on Debian 12.5, running on Debian 6.1 (64-bit)

**Comment by TonyGiorgio** [comment]
withdraw through lightning or on chain to a different wallet
