### ISSUE TITLE
NWC: create invoices via BTCPay Server

### ISSUE THREAD

**Issue by petzsch** [MutinyWallet/mutiny-web#1240]
Since a couple of days, it's possible to add a lightning wallet via NWC to BTCPay Server. However when doing this with the Mutiny connect string, I get the following:

> Invalid URL (No commands available or not all required commands are available (get_info, make_invoice, lookup_invoice, list_transactions))

The issue is tracked here: https://github.com/Kukks/BTCPayServerPlugins/issues/54

I'm just opening an issue with you, in case changes to your NWC interface could be needed.

**Comment by benthecarman** [comment]
We don't support list transactions and aren't planning to add it.
