### ISSUE TITLE
Transaction pending on MutinyWallet after 6 confirms

### ISSUE THREAD

**Issue by Bitcoinium** [MutinyWallet/mutiny-web#1242]
Hi Ben and Tony. I sent a utxo and it shows as confirmed on the time chain but still appears as pending on the wallet.  Please advise on why the lag?
![IMG_2027](https://github.com/MutinyWallet/mutiny-web/assets/152038074/24579b7a-4b6f-4cbf-b608-43acb3751ecd)

**Comment by benthecarman** [comment]
If you deposited into a Fedimint it takes 10 confirmations, however, you should not be depositing into them as they are shutting down

**Comment by Bitcoinium** [comment]
Hi Ben. I deposited on chain, not fediment.

**Comment by benthecarman** [comment]
If you have joined a federation, any receive (lightning or onchain) goes into the federation

**Comment by Bitcoinium** [comment]
Got it. I did join Freedom One. So after 10 confirms, should I swap to Lightening? What is the best way to get it on chain

**Comment by benthecarman** [comment]
Withdraw the money from the federation and then remove it, then on chain receives will go to your onchain wallet

**Comment by Bitcoinium** [comment]
Understood. I will wait until I have the funds on chain and then close the issue.

**Comment by Bitcoinium** [comment]
Ben, it is 10 confirmations and still it shows pending. What now?

**Comment by benthecarman** [comment]
The federations are having issues which is why we are telling people not to deposit into them, you'll just need to wait for the federation to be properly online

**Comment by Bitcoinium** [comment]
Wow, Ben. I had no idea. That's why I sent funds on chain using a self-custody wallet to avoid any mishap. This could be disaster for me :(

**Comment by Bitcoinium** [comment]
Phew, it cleared on the fediment, as you said.
