### ISSUE TITLE
Cant get funds of fedimint.

### ISSUE THREAD

**Issue by timvak** [MutinyWallet/mutiny-web#1252]
Hey guys,

I saw the notification about the fedimint xyz dns issues. So i tried to move the remaining ~13k sats from freedom one mint, but im not able.. when i tried to send to another wallet it takes from my lightning ballance. Is there a way circumvent this so i can safely remove freedom one mint? And what replacement mint do you recommend?

[mutiny-logs.txt](https://github.com/user-attachments/files/16078383/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Please read our tweets. Send over LN or on chain and keep trying and with different amounts. Nothing else we can do here.
