### ISSUE TITLE
mutiny.plus Lightning addresses not found

### ISSUE THREAD

**Issue by Dou10s** [MutinyWallet/mutiny-web#1254]
LN addresses as part of mutiny plus subscription do not seem to be working. they are no longer detected as a valid LN address (at least not by Strike).  I have been able to send and receive to/from Strike using invoices, and LN address worked as recently as a month ago.

**Comment by benthecarman** [comment]
The lightning addresses are disabled as of now because they are reliant on fedimints which are shutting down

https://x.com/mutinywallet/status/1805346636660429021?s=46
