### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by sam22-jeg** [MutinyWallet/mutiny-web#1256]
Hi, I can't get into my account
I'm getting an error saying that the account is already signed in on another device
After that, it says failing to connect to Federation

How can I fix this? I have tried installing on different platforms.
With the seet word and import stats from file.

But still get the same issues

**Comment by benthecarman** [comment]
Sounds like you have it open on another device

**Comment by sam22-jeg** [comment]
I don't 
The problem started on my phone and at that time I've never tried to install it on another device

I have installed it on my Mac later and the problem is the same
I made sure that it was closed down on my phone

**Comment by benthecarman** [comment]
Can you provide logs?

**Comment by sam22-jeg** [comment]
[mutiny-logs.txt](https://github.com/user-attachments/files/16101237/mutiny-logs.txt)

**Comment by sam22-jeg** [comment]
Now I get this arrow. 
![IMG_0440](https://github.com/MutinyWallet/mutiny-web/assets/174719317/ff301d2c-085c-4656-8a0d-ed67fcc34ac5)

**Comment by sam22-jeg** [comment]
problem solved
