### ISSUE TITLE
Can't generate an invoice

### ISSUE THREAD

**Issue by dangershony** [MutinyWallet/mutiny-web#1261]
Any ideas?

![image](https://github.com/MutinyWallet/mutiny-web/assets/7487930/62f1a4a5-c987-41b3-8a47-9ebaa4df493f)

**Comment by TonyGiorgio** [comment]
LSP unable to handle the request.

**Comment by dangershony** [comment]
What does it mean? anything I can do to fix it? or just use another (centralized) wallet?

**Comment by TonyGiorgio** [comment]
You can try again later or use another wallet

**Comment by dangershony** [comment]
FYI if anyone else got that issue, after 3 days I managed to get an invoice
