### ISSUE TITLE
Failed payment stuck in reserve balance

### ISSUE THREAD

**Issue by KayTX** [MutinyWallet/mutiny-web#1268]
Hi, I've tried to pay an invoice through my LSP (_Flow 2.0 by Voltage_).
The payment got in pending state and after some minutes a fraction of the payment returned into my balance.
After beeing for about 2 hours in pending state I closed my browser.
The browser cache was cleared.
I've restored my wallet from seed in a new session but the rest of the payment did not show up in my balance.
The missing amount is part of my "reserve balance".

The invoice has already expired (I still have the invoice if needed).
The channel is still open and online.

How can I get the missing amount of the failed payment back into my balance?

Thank you in advance.

**Comment by KayTX** [comment]
Time seems to have solved the problem.
The missing amount has been credited back to my balance.

I find it strange that it took several hours after the invoice expired.

Was I lucky that with the process described above (pending status, own node goes offline, clear browser cache) my sats were finally credited back to my balance (back from reserve balance) ?

Would I also have received the sats back with another LSP or is it independent of this due to the Lightning (/ Mutiny ?) architecture?

**Comment by TonyGiorgio** [comment]
This is how lightning works.
