### ISSUE TITLE
Lost funds after attempting to sweep federation to off chain

### ISSUE THREAD

**Issue by DireMunchkin** [MutinyWallet/mutiny-web#1269]
I was trying to sweep my remaining funds off a Fedimint - I sent all of them using a on chain transaction. However when sending the transaction Mutiny crashed. When I restarted the app I have zero ecash balance, and there's a "pending" transaction on chain listed. However if I click the mempool link in the transaction I can see it's actually not broadcast, so it's not being confirmed. This was about 75k sats, so not a huge amount, but I'd still like to get them back if possible.

I'm attaching logs, let me know if there's anything else I can try.

[mutiny-logs.txt](https://github.com/user-attachments/files/16321752/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
The next version of the app should have a way to rescan fedimint data. Should go out this week.

**Comment by DireMunchkin** [comment]
Cool, I'll make another attempt once that's out.

**Comment by AnthonyRonning** [comment]
Version 1.8 has that, I think in the emergency toolkit. It may take a long time.

**Comment by DireMunchkin** [comment]
I'm not seeing anything that looks like that in emergency tools:

![Screenshot from 2024-09-04 18-43-22](https://github.com/user-attachments/assets/1445234b-3175-4361-b2e7-1f8d5e60552e)

**Comment by DireMunchkin** [comment]
I checked https://app.mutinywallet.com

**Comment by DireMunchkin** [comment]
OK, so after looking around a bit I found it was possible to re-scan federations by enabling safe mode, and then going to the Federations page. Sadly this did not undo the funds lost.
