### ISSUE TITLE
Account Name “account name” is not found on “mutiny.plus”

### ISSUE THREAD

**Issue by wksantiago** [MutinyWallet/mutiny-web#1270]
Account Name “account name” is not found on “mutiny.plus”

But I paid for an account and was working 

Can it be re-enabled?

**Comment by benthecarman** [comment]
It is re-enabled

**Comment by wksantiago** [comment]
No, I got out but can join one.

Is there a recommended one?

**Comment by benthecarman** [comment]
We don't recommend any federations

**Comment by wksantiago** [comment]
Is this a good place to look
https://bitcoinmints.com/?show=fedimint&tab=mints

**Comment by wksantiago** [comment]
I have onchain sats and lightning channel open, but still get “Name “williamsantiago” is not found on “mutiny.plus”.”

**Comment by TonyGiorgio** [comment]
As we indicated, a federation is required.
