### ISSUE TITLE
Browser settings/wallet resetting

### ISSUE THREAD

**Issue by MatthewD-btc** [MutinyWallet/mutiny-web#1273]
Hi Mutiny team. Mutiny is resetting on me pretty constantly, about 4 or 5 times a week and it is hampering my UX. Tony mentioned to me in a nostr post this might be a browser setting problem, but I've dug through the tickets here and looked in my browser settings and can't figure anything out. 

I've mainly been using chrome, android...would the PWA be better run through another browser? 

It's been kind of a pain in the butt having to enter my words in every time I need to use the app. Thanks for your time, Matt.

**Comment by benthecarman** [comment]
Try using the app, it is more preformant

**Comment by MatthewD-btc** [comment]
I am. I was under the impression that the app runs through the browser in some regard, like the PWA appeared on my app list.
