### ISSUE TITLE
where are nostr wallet connect features ?

### ISSUE THREAD

**Issue by gotcha** [MutinyWallet/mutiny-web#1274]
I did not manage to find how to setup nostr wallet connect. Is that a Mutiny plus feature ?

**Comment by benthecarman** [comment]
It is on the home screen under requests

**Comment by gotcha** [comment]
Thanks for quick answer !

I feel it is not that intuitive to relate the "requests" button with NWC.

It might be useful to add a NWC section in settings. Am I missing sthing obvious that makes that suggestion silly ?

**Comment by benthecarman** [comment]
Nwc sends payment requests to your wallet

**Comment by gotcha** [comment]
Yup, it does. Am I the first that did not find it ?
