### ISSUE TITLE
Issues withdrawing onchain funds after closing channel

### ISSUE THREAD

**Issue by ssbright** [MutinyWallet/mutiny-web#1275]
Hey all,

I read the news this morning that Mutiny is closing down. I was bummed to read this, I think this is an amazing app. 

Regardless, I decided to close my channels so I can move my BTC onchain. However, after closing my channels, I cannot seem to move them onchain. Funds seem unavailable for spending. Curious how to fix this. 

I had the idea of using my seed phrase to just use another wallet software to move it, but what is the default derivation path?

The app does say it takes a few days for funds to be in wallet. Confused why this would be the case, any explanation here?

**Comment by benthecarman** [comment]
This means the channel was force closed. After a few days the funds should be available and you'll be able to send them.

**Comment by darrenahunter** [comment]
Hi @benthecarman 
What is the default Mutiny Wallet derivation path ? have tried M/84/0/0 using Sparrow but not finding UTXO's - do you use a different path ?
thanks

**Comment by TonyGiorgio** [comment]
https://github.com/MutinyWallet/mutiny-web/wiki/Recovery#on-chain

**Comment by darrenahunter** [comment]
thanks you tony - worked like a charm with sparrow

**Comment by TonyGiorgio** [comment]
If you’ve had force closes, those take up to a few weeks. Otherwise you can try to bump up the derivation path gap to a hundred or 2.

**Comment by TonyGiorgio** [comment]
Since the original issue was solved here I’m closing this but feel free to open a new issue with logs if you’re still having problems.
