### ISSUE TITLE
Channel force closed month ago. Still can't move sats onchain

### ISSUE THREAD

**Issue by SLIM-CODE-412** [MutinyWallet/mutiny-web#1276]
![Screenshot_20240806-145202](https://github.com/user-attachments/assets/33aa8618-5cdb-413b-bdcd-f84fdd10f0e4)

Still getting error about balance. Any suggestions.

**Comment by benthecarman** [comment]
Can you provide logs

**Comment by SLIM-CODE-412** [comment]
[mutiny-logs.txt](https://github.com/user-attachments/files/16514720/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Looks like you had a stuck htlc that force closed the channel, it was broadcast at a low fee rate and hasn't been confirmed yet. I accelerated it for you, hopefully it'll be confirmed soon and then your wallet should sweep the funds after a few days.

https://mempool.space/tx/cec29cf3310d8adec9ba3037e49a0abe2d2c4fc64b6be53b46f483d50a9b5081

**Comment by SLIM-CODE-412** [comment]
> Looks like you had a stuck htlc that force closed the channel, it was broadcast at a low fee rate and hasn't been confirmed yet. I accelerated it for you, hopefully it'll be confirmed soon and then your wallet should sweep the funds after a few days.
> 
> https://mempool.space/tx/cec29cf3310d8adec9ba3037e49a0abe2d2c4fc64b6be53b46f483d50a9b5081

**Comment by SLIM-CODE-412** [comment]
Thank you sir. Let me know what fee was to bump so I can reimburse. I don't expect you to pay that. Hit me with an LN Invoice or on chain addy.
