### ISSUE TITLE
Swept force close

### ISSUE THREAD

**Issue by Sniggly** [MutinyWallet/mutiny-web#1279]
I received some Sats over Lightning. Next to the amount I received, it says Swept force close. What have I done to make this happen?

Tonight, I also sent a Lightning invoice to someone who them sent me Sats which I have never received. Do I not have a channel? 

Thanks!

**Comment by benthecarman** [comment]
seems like your channel was force closed, you should have an activity item that'll give you the reason why

**Comment by TonyGiorgio** [comment]
We are shutting down so I suggest not opening another channel and instead send your on chain funds elsewhere.
