### ISSUE TITLE
[FEATURE] Send All

### ISSUE THREAD

**Issue by crimsonleaf363** [MutinyWallet/mutiny-web#1281]
## Summary
Add the ability for users to send all of their on chain and/or lightning network sats from the wallet.

### Motivation
Some users want to move their funds to a new wallet before the wallet development stops. This feature would make the process more convenient and efficient.

### Technical Details
The wallet must calculate the balances and fees.

**Comment by TonyGiorgio** [comment]
It’s not possible with lightning and on chain send all already exists. Just type the max amount.
