### ISSUE TITLE
Unable to come to consensus about closing feerate

### ISSUE THREAD

**Issue by pawelkata** [MutinyWallet/mutiny-web#1284]
Hello. I tried to close my lightning channel and something went wrong, namely I got this error (Mutiny iOS, latest version):

```2024-08-21 13:58:06.281 daa4 DEBUG [mutiny_core::event:543] EVENT: Channel 9a857d1d6d68ea6da4bc0e2b57d3efdf9f44911a10b7505e336345708c69b48b of size 249700 closed due to: ProcessingError { err: "Unable to come to consensus about closing feerate, remote wants something (473 sat) lower than our min fee (770 sat)" }```

When I press on the transaction, it says "Funds may take a few days to be swept back into the wallet".

What actually happened and can I speed this up?

**Comment by TonyGiorgio** [comment]
The nodes couldn’t agree on a fee rate so it had to be force closed. Nothing can be done here besides waiting for the force close transaction to confirm and the time lock to expire so it can be swept back to your wallet.

**Comment by pawelkata** [comment]
Thank you kindly for your answer. Do I understand correctly that if I restore the on-chain wallet using my 12 words in, say, Sparrow, the funds will eventually show up and I can close the Mutiny app on my device (won't remove it until it's done, of course)?

**Comment by TonyGiorgio** [comment]
No. These are lightning transactions that still need to close and sweep properly. Wait.
