### ISSUE TITLE
Channel close transactions are not being broadcasted.

### ISSUE THREAD

**Issue by BanDieter64** [MutinyWallet/mutiny-web#1286]
I closed 9 channels.
And I can't find the transaction ID's in the mempool...
![image](https://github.com/user-attachments/assets/4cbc3f63-5f31-4057-badf-c076d7553465)
![image](https://github.com/user-attachments/assets/8adc1759-6625-4300-a873-e3221cd3bab2)

**Comment by TonyGiorgio** [comment]
That's the channel ID, not the transaction ID. 

I would do what the text says and wait a few days when force closes occur.
