### ISSUE TITLE
blank page on ubuntu touch

### ISSUE THREAD

**Issue by ulrichard** [MutinyWallet/mutiny-web#1291]
When I load https://app.mutinywallet.com/ in the https://gitlab.com/ubports/development/core/morph-browser on https://ubports.com/ it appears to load some stuff, but the page stays black indefinitely, and no UI elements appear. There are limited developer tools on that browser. Displaying the page source shows some limited boilerplate page.

**Comment by TonyGiorgio** [comment]
Not supported, won't fix
