### ISSUE TITLE
Lightning funds 

### ISSUE THREAD

**Issue by maxip2129** [MutinyWallet/mutiny-web#1297]
Is there an alternate way to access lightning funds ? I am having similar problems as others. Stuck on beginning screen that says can’t connect to federation. Is there another way to access lightning funds with seed phrase via another wallet or something ?

**Comment by laalauren1** [comment]
@maxip2129 Looks like you're facing a connection problem with the lightning funds.?

**Comment by AnthonyRonning** [comment]
If a federation isn't working then it's not working. Outside of our control.
