### ISSUE TITLE
Unknown error when swapping to lightning

### ISSUE THREAD

**Issue by calvinhg** [MutinyWallet/mutiny-web#1299]
I'm trying to swap to lightning from my eSats balance but I get an "unknown error" message when I do. Browser devtools says "got unhandled error: no LN gateway available". Am I doing this right?
[mutiny-logs.txt](https://github.com/user-attachments/files/17003504/mutiny-logs.txt)

**Comment by benthecarman** [comment]
You should just withdraw onchain

**Comment by calvinhg** [comment]
Oh ok that worked thanks!

A little off-topic, how do I withdraw my lightning balance?

**Comment by benthecarman** [comment]
Best to just close the channel and send out onchain
