### ISSUE TITLE
Federation to Lightning swap Pending

### ISSUE THREAD

**Issue by Pukasv** [MutinyWallet/mutiny-web#1300]
Hello, my Federation to Lightning swap is stuck. Shows as Pending, status Unpaid. I can't move these sats to On chain adress, or lightning.

**Comment by Pukasv** [comment]
Attaching log file. Anyone can help? Transaction stuck.
[mutiny-logs.txt](https://github.com/user-attachments/files/17305200/mutiny-logs.txt)

**Comment by Pukasv** [comment]
Is anyone in here? How can i save my sats before Mutiny is shut down? I have this transaction that seems can't get trough.
![Screenshot 2024-11-11 at 15 49 48](https://github.com/user-attachments/assets/c90c87a0-3abf-4c03-9e7c-64a3f2d8876c)
![Screenshot 2024-11-11 at 15 49 35](https://github.com/user-attachments/assets/d8a26372-01da-4b24-a270-9d75a1e3418c)

**Comment by blockscout-oss** [comment]
> Is anyone in here? How can i save my sats before Mutiny is shut down? I have this transaction that seems can't get trough. ![Screenshot 2024-11-11 at 15 49 48](https://private-user-images.githubusercontent.com/19520930/384945118-c90c87a0-3abf-4c03-9e7c-64a3f2d8876c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTQwMDUsIm5iZiI6MTczMjU1MzcwNSwicGF0aCI6Ii8xOTUyMDkzMC8zODQ5NDUxMTgtYzkwYzg3YTAtM2FiZi00YzAzLTllN2MtNjRhM2YyZDg4NzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE2NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYjM5N2FkYWY1NmI2OWIyMDEzNWRiZmVkMDQ3ZmIwMTUwZWEwZTg1ODc1OTYxNjNmZTE5MWYyZGYwN2MwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e-2Q2VAczpbXpjwhf4Ilf8VMnDrNCKKIgaGtlHrkE2g) ![Screenshot 2024-11-11 at 15 49 35](https://private-user-images.githubusercontent.com/19520930/384945133-d8a26372-01da-4b24-a270-9d75a1e3418c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTQwMDUsIm5iZiI6MTczMjU1MzcwNSwicGF0aCI6Ii8xOTUyMDkzMC8zODQ5NDUxMzMtZDhhMjYzNzItMDFkYS00YjI0LWEyNzAtOWQ3NWExZTM0MThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE2NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZDZhZWFlY2Y4MzRmYWRhNDIzNjVhODVmMzllOTY0NGFlNjBkZTIxMzlhNDY0Yzk5NzViMGY4ZDE1ODRjOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PWduHnPIlCd4f7__BZMVKPv3QPKulTcIMuoOnoh31Gc)

Thanks for bringing this issue to our attention. The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

 [MutinyWallet Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by AnthonyRonning** [comment]
Can't do anything about a transaction that's stuck.
