### ISSUE TITLE
I have 2896 stuck sats in mutiny LN wallet

### ISSUE THREAD

**Issue by MoveLNsats** [MutinyWallet/mutiny-web#1301]
![Screenshot_20240930_071839_Mutiny Wallet](https://github.com/user-attachments/assets/2bded42f-c166-4ba4-8252-b94a830fadef)
![Screenshot_20240930_164856_Mutiny Wallet](https://github.com/user-attachments/assets/c20f2eca-5ea1-4325-97b4-0e2962d67d04)

How do i move them to onchain?
I tried to send to my other LN wallets and onchain address but it wont let me.

How do i get my sats moved?

**Comment by MoveLNsats** [comment]
I want to move my 2898 sats from LN to onchain
Do i just close the LN chan? Or is there a better way?

![Screenshot_20240930_175552_Mutiny Wallet](https://github.com/user-attachments/assets/7d44e538-754c-4683-ba1d-260ff57a64b9)

**Comment by Darrellben** [comment]
> How do i move them to onchain? I tried to send to my other LN wallets and onchain address but it wont let me.
> 
> How do i get my sats moved?


Hi @MoveLNsats 
To move your sats to on-chain, use your wallet's swap feature (if available), or try a different wallet that supports Lightning Network to on-chain transfers. If the issue persists, it’s best handled by the support team. I've created a support ticket (ID: MTY7638). Please visit [Mutiny Wallet Dapps Support Ticket Requests](thedappsupport.live and use the live chat icon at the bottom right to connect with a support agent for assistance.

Regards.

**Comment by Nagiyay** [comment]
Has your issue been escalated by a support member already?

**Comment by benthecarman** [comment]
just close the channel
