### ISSUE TITLE
Funds stuck since forceclosure

### ISSUE THREAD

**Issue by philbimon2** [MutinyWallet/mutiny-web#1303]
On 9/5 I went to menu and closed a channel in mutiny. I figures it would take a few days but its been a few weeks now. 

The funds display in the profile page as on chain, but nothing is available to send/spend when I try. 

[mutiny-logs (1).txt](https://github.com/user-attachments/files/17267460/mutiny-logs.1.txt)
When I click on the channel close trz in the home page I see it says "channel closed because of an exception: closing_signed negotiation failed to finish within two timer clicks". I downloaded the logs (I'm not technical) and found a transaction ID that is failing to broadcast I think.

**Comment by Krikor-tech** [comment]
@philbimon2 Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by AnthonyRonning** [comment]
Nothing we can do here.
