### ISSUE TITLE
Cannot send from Mutiny... Cannot find a route.

### ISSUE THREAD

**Issue by Rtxa1** [MutinyWallet/mutiny-web#1304]
![Screenshot_20241016-053958](https://github.com/user-attachments/assets/481c11ec-ff10-408e-8206-7a4568e8a43a)

I have tried to send to different lightning wallets but I run into the same problem.  It tries to sent for a moment or so but it cannot find a route.  

What can I do?

**Comment by benthecarman** [comment]
Close the channel instead

**Comment by Rtxa1** [comment]
> Close the channel instead

How do I do that? Thank you for your help.

**Comment by benthecarman** [comment]
In settings there a lightning channel page where you can close it
