### ISSUE TITLE
E-cash stuck in mutiny wallet

### ISSUE THREAD

**Issue by PCAanalytics** [MutinyWallet/mutiny-web#1305]
Hi, I've been away, just found out about mutiny closing down. Managed to get my on chain funds out. But, I'm unable to get the e-cash into Fedi app. Is it because you have closed the lightning channels?

**Comment by Tony-ptech** [comment]
@PCAanalytics Thanks for bringing this issue to our attention.
The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by AnthonyRonning** [comment]
Idk, contact your federation.
