### ISSUE TITLE
Funds Stuck for months

### ISSUE THREAD

**Issue by equal11111** [MutinyWallet/mutiny-web#1306]
I got my channel closed but I am going assume it was closed with too low of a fee and has never confirmed.  How can I find the tx for the transaction in my logs to be able to acclerate it so I can have my funds back?  It shows up in my on chain funds in mutiny wallet but I can not move them. 

[mutiny-logs_1.txt](https://github.com/user-attachments/files/17738000/mutiny-logs_1.txt)

**Comment by kieth314M7** [comment]
@equal11111 Thanks for bringing this issue to our attention.
The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Mutiny Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by AnthonyRonning** [comment]
You can look through the logs and find it. But can't do anything about a transaction stuck.
