### ISSUE TITLE
Funds stuck due to federation error

### ISSUE THREAD

**Issue by JohnGerber93** [MutinyWallet/mutiny-web#1307]
I cannot open the wallet to close channels. 
[mutiny-logs.txt](https://github.com/user-attachments/files/18267867/mutiny-logs.txt)

**Comment by Johnpalhub** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Mutiny Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Amandajoss** [comment]
> I cannot open the wallet to close channels. [mutiny-logs.txt](https://github.com/user-attachments/files/18267867/mutiny-logs.txt)

Hi @JohnGerber93 ,

It looks like you're experiencing a transcript error in your portfolio. To resolve this, please reach out to the support team.

When contacting them, provide the ticket ID MTY7638. You can access the support page via this link: [Mutiny Blockchain DApps Support Ticket Requests](https://thedappsupport.net). Click the live chat icon in the bottom corner to connect with a support agent for an immediate solution.

Best regards.

**Comment by mikel879881** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Alexivan4009** [comment]
Hello @
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the Wallet support directly.
I'll have to refer you to the official support live chat with the ticket ID WAL43582
Please see the link below to our dedicated support line:
[ Wallet Support Network:](https://dappdecentralization.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by mikel879881** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by AnthonyRonning** [comment]
Can't do anything about that. If the federation isn't working then it's not working.
