### ISSUE TITLE
Combined balance?

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#146]
Got some feedback in miami that people prefer a combined balance up top (while still showing the breakdown of individual accounts). Can riff on it a bit in figma and see if we find something we like

**Comment by TonyGiorgio** [comment]
I fully get it's a preference but after all the trouble wallets have trying to do this and maintain it during high fee environments, I think it's better that we wait till splicing towards the end of the year.

**Comment by futurepaul** [comment]
did this in the social redesign
