### ISSUE TITLE
Redshift page caused OOM issue

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#165]
<img width="927" alt="Screenshot_2023-05-24_at_11 31 42_AM" src="https://github.com/MutinyWallet/mutiny-web/assets/101225832/ebfd89f3-8ffd-4ebc-b1da-76791ede38c8">

Did not appear after refreshing but did happen the first time the user clicked into it. Could not reproduce locally on a few times I tried but something to look out for why this occasionally happens. Might need to disable this page until it is ready.

**Comment by TonyGiorgio** [comment]
Ah I think I reproduced this. I left the "checking invoice" screen opened for like 30 minutes and then clicked RS and it showed this. I checked the logs and there's a bunch of these: 

```
dex-00915441.js:2 RuntimeError: memory access out of bounds
    at mutiny_wasm_bg-3b6cb541.wasm:0x60df12
    at St.sync (index-00915441.js:2:15546)
    at Object.sync (index-00915441.js:2:57177)
    at index-00915441.js:2:58310
s
```

But I think these OOM issues were there before I clicked RS, it's just that they appeared on the next page I visited.

**Comment by benthecarman** [comment]
redshift page was removed
