### ISSUE TITLE
Show first and last part of long address strings

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#186]
Instead of first X amount of characters for long addresses or invoices, maybe just do the first and last X / 2 instead. Typically users just check the first few and last few.

**Comment by thebrandonlucas** [comment]
Looks like this one can be closed? I started working on this but seems this is solved with the [`TruncateMiddle`](https://github.com/MutinyWallet/mutiny-web/blob/master/src/components/ShareCard.tsx#L44-L59) component, and is being used
![Screenshot 2023-10-06 at 1 49 30 PM](https://github.com/MutinyWallet/mutiny-web/assets/38222767/83bfdaee-feb6-4ce4-8458-99c0e58f1f6f)
![Screenshot 2023-10-06 at 1 49 51 PM](https://github.com/MutinyWallet/mutiny-web/assets/38222767/ca4b4438-7fdf-4b6f-816b-03e8631e2de0)
