### ISSUE TITLE
Home button on activity screen doesn't clear navigation stack

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-web#199]
https://github.com/MutinyWallet/mutiny-web/assets/15256660/491edad5-ff88-447e-a108-ff58a455557e

**Comment by benalleng** [comment]
Just so i understand correctly the ideal flow would be to replace the history when pressing the home button?
i.e. `navigate.replace()`

**Comment by futurepaul** [comment]
no longer applicable
