### ISSUE TITLE
Just wanted to say thank you for releasing the script to set up a custom signet

### ISSUE THREAD

**Issue by dangershony** [MutinyWallet/mutiny-web#227]
We used it and its great.

Question about the wallet, the seed words are stored in the browser local storage I suppose, how do you store the mnemonic safely?

**Comment by benthecarman** [comment]
For now the seed is in indexed db, we're adding an option to encrypt it as well.

**Comment by dangershony** [comment]
Thanks for the reply, good luck I will follow the progress
