### ISSUE TITLE
Show negative sign on sends

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#231]
Receives are pretty clear but sends are not. You can imagine seeing all three as sends in the activity screen and not knowing those are sends. I think even just a negative sign would clear that up. 

![Screenshot from 2023-06-08 21-18-08](https://github.com/MutinyWallet/mutiny-web/assets/101225832/b9f0c807-1f6b-42e1-8dc1-d5c9c8438486)

**Comment by TonyGiorgio** [comment]
Alterantively, another user brought up arrows for in and out if we don't want negatives.

**Comment by futurepaul** [comment]
Where would the arrows go? I don't really like negatives if I can avoid them

**Comment by TonyGiorgio** [comment]
Not sure, they didn't know where it would be best to go either. But something needs to make it more obvious that it is a spend, so open to alternative approaches. Not sure why negatives are bad... typically when money goes down, a negative sign is what is used for that..
