### ISSUE TITLE
Browser checks aren't catching Vanadium 

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#246]
https://twitter.com/Trojan81/status/1668706073258360832

**Comment by benthecarman** [comment]
Probably need to check for Javascript first

**Comment by TonyGiorgio** [comment]
Same issue for Fennec.

There was no storage warning. Fennec tries to load but doesn't go anywhere, was a few minutes and nothing happened.

Need to reproduce myself.

https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

Javascript was not blocked in the settings, I didn't see anythign that would cause it to be blocked.
