### ISSUE TITLE
Fennec Browser non-supported

### ISSUE THREAD

**Issue by AnthonyRonning** [MutinyWallet/mutiny-web#251]
There was no storage warning. Fennec tries to load but doesn't go anywhere, was a few minutes and nothing happened. 

Need to reproduce myself. 

https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

**Comment by TonyGiorgio** [comment]
Closing in favor of https://github.com/MutinyWallet/mutiny-web/issues/246
