### ISSUE TITLE
Camera does weird zooming stuff when first opened.

### ISSUE THREAD

**Issue by suhailsaqan** [MutinyWallet/mutiny-web#281]
I'm on iOS 17.

https://github.com/MutinyWallet/mutiny-web/assets/43693074/fddb2910-3731-45db-bffe-a9932685ad88

**Comment by benthecarman** [comment]
happens to me, on ios 17 too

**Comment by futurepaul** [comment]
thx doesn't happen for me on ios 16 but will keep an eye out

**Comment by benthecarman** [comment]
think this was an ios bug
