### ISSUE TITLE
Do some Static Rendering so we get some minimal page for JS-less browsers

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#290]
especially useful for rendering meta tags... right now we basically ship a blank html page + a script tag

Possibly want to use this... https://github.com/solidjs/solid-start/tree/main/packages/start-static the readme isn't very encouraging though lol

the main goal would be to find a way to have only a single page worried about "am I being rendered" on the server so we don't have to pepper that logic all over the app

**Comment by benalleng** [comment]
One point of confusion for rendering these meta tags is how some metadata is shown when googling.
Both the `description` and `twitter:description` are displayed
![image](https://github.com/MutinyWallet/mutiny-web/assets/108441023/3a05b2c3-6991-4c81-93ca-2818a9363892)

**Comment by futurepaul** [comment]
yeah google does a minor amount of js afaik

**Comment by futurepaul** [comment]
looks like this could be solved by this PR: https://github.com/solidjs/solid-start/pull/810/files
