### ISSUE TITLE
Warn users to keep the app open to receive a payment

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#294]
Getting issues especially when users are switching to open lightning wallets on their phone to pay the invoice. 

The user can switch to initiate the payment in another app but they need to come back to the mutiny wallet, wait up to 10 seconds (reconnect peer and open channel flow if needed) to order for the payment to be received.

So for all incoming payments, a dialog to keep the app opened or to come back to the app once initiating the payment from another wallet (this one is so tough, because the other wallet might be noncustodial too and want the phone to stay opened the whole time as well....)

For incoming payments that are also new channel opens, some more dialog that the first time payment received will take up to 10s to complete while the payment is being received, to establish the new channel. 

We can work on more enhancements in the future to give the user real time feedback whenever the channel has been opened and it's just a few more seconds until it is fully received. 

So many issues around backgrounding the app while a payment is being received, such as [this](https://github.com/MutinyWallet/mutiny-node/issues/625) one that resulted in a force close, and ones that result in bad UX around users not thinking the payment could be sent from the other wallet, which is typically a first time action being taken.

**Comment by benalleng** [comment]
Would we want to add a general alert Anytime a user is closing a mutiny instance? or only once they have gone through a receive-flow?

**Comment by TonyGiorgio** [comment]
I think on the receive screen itself would be helpful. We just brought this up in a design meetup. Not sure if there's something in the figma designs for it yet. @futurepaul

**Comment by extrapockets** [comment]
I have noticed this when Zapping on Nostr - typically until I open Mutiny again, my Zaps don't show up on Amethyst (using NWC in Mutiny Debug Tools). Is this the same issue?
