### ISSUE TITLE
Fee estimation re-runs after it's needed

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#301]
It's possible this could happen in send, but it def happens in swap quite often:

https://github.com/MutinyWallet/mutiny-web/blob/22ca57c93e736c8d9d8d01ad2a1b2c0853825fb7/src/routes/Swap.tsx#L252

**Comment by Fajarcipta23** [comment]
![Screenshot_2023_0713_042843](https://github.com/MutinyWallet/mutiny-web/assets/100537350/c9fe19d9-cd86-4412-b261-53e787ec8cc6)

Help sir, invalid amount 🥲

**Comment by TonyGiorgio** [comment]
Are you entering an amount greater than 50k sats for the first lightning receive? This is a warning on the receive amount input screen.

**Comment by Fajarcipta23** [comment]
yes sir I have entered 60k, but it is still invalid

**Comment by TonyGiorgio** [comment]
Think we fixed this in general.
