### ISSUE TITLE
Wallet Connection feature: slow zap process

### ISSUE THREAD

**Issue by extrapockets** [MutinyWallet/mutiny-web#322]
Just tested the new NWC method. I connected to Amethyst, and now every zap must be authorized in Mutiny. I used to have to open Mutiny to have the zap work anyway, however now I need to change between screens until I get an option to authorize the zap (seems as if a screen refresh is required to see the zap authorization button). Attached are 2 videos (the 2nd video is a whole lot of nothing - just me waiting for the auth button to appear until I finally refresh the screen) and the Mutiny logs. 

[Zap Video 1](https://nostr.build/av/7454cab061a4b45fc76c01ec733d89b2ebd0b29edf09a593922044e0d4958ab5.mp4) 

[Zap Video 2](https://nostr.build/av/2fc1b143a350b63f5498fb6bf727d67e4f50cc056a216379c97590c639a10f53.mp4) 

[mutiny-logs (3).txt](https://github.com/MutinyWallet/mutiny-web/files/12014803/mutiny-logs.3.txt)

In the future, I'd like the option to authorize all payments of a connected client automatically (or all payments less than a certain amount of sats). Happy release week!

**Comment by yudi469** [comment]
Processing takes too long and doesn't finish quickly even though the signal already supports it

**Comment by futurepaul** [comment]
> seems as if a screen refresh is required to see the zap authorization button

I believe this has been fixed as of https://github.com/MutinyWallet/mutiny-web/pull/327, please confirm?

Def want an "approve all" button and auto-approve budgeting as well, will get there!

**Comment by extrapockets** [comment]
@futurepaul confirmed that it works! Is this a good time to ask for a Mutiny shirt? I'm at the PoL Summit.

**Comment by extrapockets** [comment]
Got a shirt, thanks guys!
