### ISSUE TITLE
Receive 50k from Muun payment seems hung

### ISSUE THREAD

**Issue by mattius459** [MutinyWallet/mutiny-web#334]
![IMG_EF26A6182521-1](https://github.com/MutinyWallet/mutiny-web/assets/39392504/13dc20e4-4340-4689-9c66-b34131695cdc)

**Comment by mattius459** [comment]
Hi Ben, I kept it open for at least 10 minutes as I remember reading that warning.

Nonetheless, payment on the muun side still seems to be in same state as it was this morning. Will it eventually revert or something? I'll try again once I get my 50k sats back.

**Comment by benthecarman** [comment]
Yeah it should eventually fall back to muun
