### ISSUE TITLE
Payment pending in Phoenix. Don’t see anything in mutiny

### ISSUE THREAD

**Issue by fyourads** [MutinyWallet/mutiny-web#338]
tried to send sats to mutiny.  It says it should stay open while you try to receive but need to switch apps to send from Phoenix. 
Now transaction is pending in Phoenix. 
Anyone knows how long it stays pending before returning to Phoenix ?

lightning payment not on chain. So weird that it’s pending

on latest version of iOS

**Comment by benthecarman** [comment]
Yeah it is hard to send from non-custodial to non-custodial on the same device because they both need to sign for the payment to go through.

The payment pending normally means the transcation is just stuck at the LSP, it should eventually fail back to phoenix

**Comment by fyourads** [comment]
Do you know how long that usually takes ?

**Comment by fyourads** [comment]
Funds are back thanks for your help ben
