### ISSUE TITLE
Can’t access on-chain funds

### ISSUE THREAD

**Issue by BTCapsule** [MutinyWallet/mutiny-web#340]
I added the 50,000 sats to open a channel, and after a few zaps, my channel was closed automatically with this message:

Channel closed because counterparty force-closed with message: channeld: received ERROR error channel ee59e413434c9d8249b2019fff536b3551564500abc9120cc24e1f5ac90cc0f6: Peer attempted to reestablish channel with a very old local commitment transaction

Now I have ~40,000 sats on-chain, but when I try to send it to another wallet, it says my On-Chain Balance has No Balance. If I try to Swap to Lightning, it also says No Balance

![76E80054-BCFC-4E9D-80AC-FEC0FB0D6358](https://github.com/MutinyWallet/mutiny-web/assets/115264270/1f31086d-6e85-4da4-b1cb-e3e7fa188a6a)

![C5F0DB35-E576-4C21-B6EA-DACF9062A881](https://github.com/MutinyWallet/mutiny-web/assets/115264270/2719a1f5-42e6-4af8-abb3-c1598835d4a5)

**Comment by benthecarman** [comment]
Damn seems you had a force close. They aren't showing up in your balance because they are in a force close state. They should be available in at most a couple days. 

Did you have the app open on two devices? These force closes shouldn't be common

**Comment by BTCapsule** [comment]
> Damn seems you had a force close. They aren't showing up in your balance because they are in a force close state. They should be available in at most a couple days.
> 
> Did you have the app open on two devices? These force closes shouldn't be common

No, when I first got the app, I didn’t realize I had to approve zaps and that I couldn’t receive zaps with nwc. So I closed the app several times, because I had to close and reopen for the zap authorizations to pop up. That’s all I can think that would have caused it.

**Comment by benthecarman** [comment]
Okay thanks, sorry about that, will keep the issue open, let us know if the money doesn't show up eventually

**Comment by BTCapsule** [comment]
> Okay thanks, sorry about that, will keep the issue open, let us know if the money doesn't show up eventually

Sure I’ll wait a couple of days and let you know what happens.

**Comment by 555-FILK** [comment]
More data for you Ben and the Mutiny team: Same thing happened to me. Created wallet on Chrome browser on desktop. Sent 100,000 sats. No issues. Opened wallet on Chrome browser on iOS. Force closed. Sent 100,000 sats to wallet on iOS. Opened wallet on desktop. Force closed. Will wait a few days for the sats to be returns to me.

**Comment by benthecarman** [comment]
@555-FILK you shouldn't be opening it across devices, that will cause force closes. Only one device can be used at a time.

**Comment by 555-FILK** [comment]
@benthecarman yup I got that after the first force closed. The second one was kind of to make sure I was right. Thanks for the reply.

**Comment by jnsats** [comment]
@benthecarman I had a forced channel close and didn't have Mutiny running on multiple devices. But:

1. I had a signet Mutiny app on my iOS 17 beta home screen. (Although I hadn't opened it since signing up for the mainnet beta.)
2. Signed up for the mainnet beta via Safari and subsequently added it to my home screen to create an "app".
3. Doing so left me logged-in to Mutiny in Safari, but because the "add to home screen" flow in iOS takes you immediately away from Safari to the location of the new app location, I didn't close the open tab in Safari.

I don't know exactly when I eventually closed the tab in Safari, but I wonder if that's what led to the forced close. If so, I imagine this could be a more common occurrence and worth warning users.

**Comment by BTCapsule** [comment]
Okay I have a new update. Opened Mutiny to check my funds, and now my balance is showing 0 sats in both lightning and on-chain.

I checked the Mutiny log and it had some addresses, but none of them show any transactions on Blockstream.info

Here is my wallet:

![2F201953-499B-4ECB-8C69-48E57D47EB1C](https://github.com/MutinyWallet/mutiny-web/assets/115264270/a011e6c7-d2d5-48cb-99d5-0ef58b14369c)

Here are the addresses on the logs:

![82D00DA4-C34B-4B4C-AD0D-A7CFE8D7A794](https://github.com/MutinyWallet/mutiny-web/assets/115264270/06d80b1f-e6fd-4b95-ae22-f7fc0d7ecba6)

**Comment by BTCapsule** [comment]
## Here is the Mutiny State when the channel closed:


{"address_labels":{"bc1p2hmkq5c32axmwprwq42garamfn63a7hn5zgrz9jf7e4s2ds7ap3qaxgmmh":[],"bc1p592mqn09x2t39qa8mstrhjy3fykq4f9j5tjsyflh357ndr6w3g8spvnwtx":[],"bc1p5zdjjjnp5749ehml3xk2nvjw69g7hxtp8fcep069myx0sns635wqaugdm9":[],"bc1pf4003276g7qmjzj598danalfl6d2n44h3ly4ng4shjngashuqt2sxnshny":["Swept Force Close"],"bc1pl86atynwz8pyy50f8cgktt2l0sktlp9u3w9d3ndujx29klr8svhs8druxw":["Swept Force Close"],"bc1ps3rsk8z0xn3j3k9u3fpug5ynufpcy2ctpse9he03ryfgmea5j87qevxfuq":["Swept Force Close"],"bc1pu859l63drkc7tlk4c7jn45xtc5lf68xmmy4enxy6m4lyy6gzq8es8d2eqs":["Swept Force Close"],"bc1pvj600psust7ds7adp92mjvjwarjt8jtp9v5g2809mxj9tw5u6kvqzj4wtq":["Swept Force Close"]},"bdk_keychain":{"chain_changeset":{"798695":"00000000000000000004c0a6342fefb47c38cf7dcaf35c296975fa205c24e864"},"indexed_additions":{"graph_additions":{"anchors":[],"last_seen":{},"txouts":{},"txs":[]},"index_additions":{}}},"channel_closure/839a2e39c7383a8d393e6d7115f7f7d3_84bd9401-b57c-4b22-a31d-f3ed22b5a3f2":{"channel_id":[238,89,228,19,67,76,157,130,73,178,1,159,255,83,107,53,81,86,69,0,171,201,18,12,194,78,31,90,201,12,192,246],"node_id":null,"reason":"Channel closed because counterparty force-closed with message: channeld: received ERROR error channel ee59e413434c9d8249b2019fff536b3551564500abc9120cc24e1f5ac90cc0f6: Peer attempted to reestablish channel with a very old local commitment transaction","timestamp":1689215355,"user_channel_id":[131,154,46,57,199,56,58,141,57,62,109,113,21,247,247,211]},"failed_spendable_outputs_84bd9401-b57c-4b22-a31d-f3ed22b5a3f2":["01c70022e551a2c6e8499d3d2f5d84441af3d738ecda12b7d8ec156f7b224a0ed787f41100000221039d1d04e78c3f7249bc43c797b4365117b2858e73bd479e562d815cebb6c709bd04020090062b1a9d000000000000220020e7dcb8c105056090183b6260d05ab19a3e46b86efd3c56020415fb39f2cb66510821028d8d3df0c8463d526bc45ea8af5cce6460f1f5083ba931d1ca564c666457b7220a200000000080ecaf400000000064af4d6ac301618503098fdf291aaefb9879fd950c080000000000022867"],"fee_estimates":{"1":10,"1008":4,"12":8,"3":9,"6":8},"first_sync":true,"invoice_labels":{"lnbc200n1pj27h3mdqqnp4qvse2075ulgrlvxgthwvg67gsectldhzewe5avp5h4en5wamy9m4zpp5rxule0zdhalakk0wc8qpcadx4q7xcpm8w3kyweuuhetc53tqcj9ssp5hhwd6zy5rtdvnsepsen8ratdheajtdnt7nhgkaam5545nmlsv0ds9qyysgqcqzptxqrpwu48s0y0uh87efu77t8kxmnwll88axg729t4aj6h9v2yw9k8a6402yxwfrzpdhamwz6haf6r69ft9hayqvtsvwvj6aa6akfwnp982x3ycq8h3v8c":[],"lnbc210n1pj2742hpp5kt0p4qr6f23exxxm9l2tj2qsrdp2qjk6x2ua3z96s9ysdcnpz5pqhp5luxx6xtr7yh0u9au64ss26p4fmvmww4vpsdpyfuhqqa8cc8xxrnqcqzzsxqyz5vqsp5hgg6cql8k5z5kjqtfw4fw3a362awmxpkfmxx3xfvdhc05903q4cq9qyyssqnv3k9rf6xc26mn9sm7akjq6ezj9kk9htl28h58twwwvyj2r5er853l70vtf3z45dp3m95yz2dvxzsawfn8r0ancvcu2c8lu2gpwc99sqwqzmu5"

## And here are the logs when it closed:

2023-07-14 19:14:28.786 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
2023-07-14 19:24:18.121 ERROR [mutiny_core::networking::socket:88] got an error reading msg: Network connection closed.
2023-07-14 19:24:18.121 TRACE [lightning::ln::peer_handler:2252] Handling disconnection of peer 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
2023-07-14 19:24:18.122 DEBUG [lightning::ln::channelmanager:6981] Marking channels with 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0 disconnected and generating channel_updates.
2023-07-14 19:24:18.122 TRACE [mutiny_core::networking::socket:103] WebSocket Closed
2023-07-14 19:24:18.123 DEBUG [mutiny_core::networking::proxy:107] closed websocket
2023-07-14 19:24:18.124 TRACE [mutiny_core::background:556] Persisting ChannelManager...
2023-07-14 19:24:18.126 TRACE [mutiny_core::background:556] Done persisting ChannelManager.
2023-07-14 19:24:19.543 TRACE [mutiny_core::background:556] Calling PeerManager's timer_tick_occurred
2023-07-14 19:24:20.030 DEBUG [mutiny_core::nodemanager:2174] fetching new bitcoin price
2023-07-14 19:24:20.176 TRACE [mutiny_core::node:1625] going to auto connect to peer: 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
2023-07-14 19:24:20.846 TRACE [mutiny_core::fees:126] Retrieved fees from mempool

**Comment by benthecarman** [comment]
@BTCapsule looks like you had a force close, the balance should be swept back within a few days

**Comment by BTCapsule** [comment]
> @BTCapsule looks like you had a force close, the balance should be swept back within a few days

Okay, I just thought it was strange that my balance went from 12,000 to 0. I’ll keep an eye on it and update if anything happens

**Comment by BTCapsule** [comment]
Hey it’s been 5 days since my last comment, and my wallet is still empty. Do I need to wait longer, or could something else be wrong?

**Comment by TonyGiorgio** [comment]
Could have been swept by the LSP since it closed for "outdated state" reasons. Can you confirm if this is your nodeid: `0321953fd4e7d03fb0c85ddcc46bc88670bfb6e2cbb34eb034bd733a3bbb217751` ? 

It's in admin tools section in settings. At the very top it should say `nodes`.

**Comment by BTCapsule** [comment]
> Could have been swept by the LSP since it closed for "outdated state" reasons. Can you confirm if this is your nodeid: `0321953fd4e7d03fb0c85ddcc46bc88670bfb6e2cbb34eb034bd733a3bbb217751` ?
> 
> It's in admin tools section in settings. At the very top it should say `nodes`.

Yes that appears to be mine 

![6F541F2F-34CD-4EF9-B17A-C8EDB0A85A46](https://github.com/MutinyWallet/mutiny-web/assets/115264270/ea0df9f4-0b77-4960-816d-573d9cae7339)

**Comment by TonyGiorgio** [comment]
Thanks, will forward this to the LSP. Assuming it got swept on their side and they have it, do you have an on chain address we can send the funds to? Feel free to DM me or mutinywallet on nostr or twitter if you want to keep it private.

**Comment by BTCapsule** [comment]
> Thanks, will forward this to the LSP. Assuming it got swept on their side and they have it, do you have an on chain address they can send the funds to? Feel free to DM me or mutinywallet on nostr or twitter if you want to keep it private.

Sure I’ll DM you on nostr. Thanks for the help 🤙

**Comment by BTCapsule** [comment]
Okay I received my 40,000 sats back. Thanks everyone!
