### ISSUE TITLE
50K sats sent from Muun but none received 

### ISSUE THREAD

**Issue by derekg6** [MutinyWallet/mutiny-web#342]
Sent the required 50K sats from Muun wallet to Mutiny wallet. Using Safari on a iPhone XR

![IMG_5135](https://github.com/MutinyWallet/mutiny-web/assets/139503217/6235b4aa-a5dd-40ff-a241-d63fb628c6b7)

But nothing showed up in Mutiny wallet

![IMG_5137](https://github.com/MutinyWallet/mutiny-web/assets/139503217/14c045ae-ac60-4054-ba61-6ca1e35a447b)

Will it eventually appear?

**Comment by benthecarman** [comment]
on iphone state is not shared across browsers, did you make the invoice in a different browser or install it as a pwa?

**Comment by derekg6** [comment]
Made the invoice using Mutiny in Safari.
Copied it to clipboard
Opened Muun app on same iPhone 
Hit send and pasted invoice text
Transaction to Voltage started and was confirmed 1-2 minutes later

All this on the same phone.  during the send I opened a couple other tabs  (bitcoin was pumping-lol).  Came back to the Mutiny tab and it was all black and not responding.  After a couple refresh attempts I closed it and re-opened a new Mutiny wallet tab.

That’s where I’m at now, but no sats yet.

**Comment by derekg6** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12044162/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Does it show as the payment sent on the muun side? Does a preimage show up there? 

Are you running this in a private window in safari? I see no indication in the logs that even an invoice was created. Did you back up your original seed words?

**Comment by GlenCooper** [comment]
The refreshes might have generated new wallets with each refresh(?).
