### ISSUE TITLE
Lightning channels gone

### ISSUE THREAD

**Issue by lordofwar81** [MutinyWallet/mutiny-web#343]
Havent done anything out of the ordinary. The onchain balance i see i believe is correct.  All of my lightning channels are gone. Over 1200 usd, might have had 2000 in there. And the balance has not reverted back to my onchain wallet

**Comment by lordofwar81** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12044318/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Hmm looks like you had a duplicate connection to the LSP. Did you have the app open on multiple devices at the same time?

**Comment by lordofwar81** [comment]
i did try to open on iphone. But the channels disappeared before then from graphene phone

**Comment by benthecarman** [comment]
Did you try restoring from seed?

**Comment by lordofwar81** [comment]
i did. should i delete everything on both and just try on 1 device?

**Comment by benthecarman** [comment]
Yes, if you run on multiple devices it can cause force closes and loss of funds.

**Comment by lordofwar81** [comment]
the channels were closed prior to restoring wallet on 2nd device. thats 100%. If force closed shouldnt the balnce be sent to my onchain wallet? Where is the 2000 usd?

**Comment by lordofwar81** [comment]
its been deleted from 2nd device. the onchain funds are there. The channels are still gone. You can see swaps into lightning and no lightning balance. 
![2023-07-13 14 25 02](https://github.com/MutinyWallet/mutiny-web/assets/61852793/ca82418d-a277-4389-b742-3a9af454cdb2)

**Comment by benthecarman** [comment]
Oh the channel was opened 2 weeks ago, we did not launch the lightning backups until yesterday. 

You need the original state to get those channels.

**Comment by lordofwar81** [comment]
did i fuck myself by just deleting the wallet and restoring?

**Comment by lordofwar81** [comment]
something happened when u launched yday because i havent had any issues until today.

**Comment by benthecarman** [comment]
You said you deleted from the 2nd device, if you have the original phone you should be okay.

**Comment by lordofwar81** [comment]
i deleted from both devices like u told me
![Screen Shot 2023-07-13 at 2 30 47 PM](https://github.com/MutinyWallet/mutiny-web/assets/61852793/17827f69-d54e-4012-8fac-b307c74a8e00)

**Comment by benthecarman** [comment]
Our LSP has been being bombarded from all the sign ups, could have been having connection issues

**Comment by lordofwar81** [comment]
i hope you arent telling me i lose 2k in bitcoin, cause thats not cool

**Comment by benthecarman** [comment]
As long as you have the keys it is _potentially_ recoverable. But you shouldn't be putting too much money into a wallet in closed beta

**Comment by lordofwar81** [comment]
please help me recover. when channels close the balance should go to the onchain address right? Where did my btc go?

**Comment by benthecarman** [comment]
If you give me your node id (in the admin page) we can have voltage force close the channel and you can potentially sweep it back to the wallet. 

The channel may have been force closed already as well.

**Comment by lordofwar81** [comment]
02e3508218f316aa9c2ff428215d5da3e9d48c2819eb5b662fafacfe355c8c3a3d

**Comment by lordofwar81** [comment]
In the event the channel was force closed by mistake. It is sitting somewhere that you or voltage control, right? So we should be able to access it

**Comment by benthecarman** [comment]
Your balance will be locked by keys you should own. We may need to do some ldk magic to try to get it.

**Comment by lordofwar81** [comment]
i think its closer to 1300 not 2000. Lol i need your magic to get this back please

**Comment by lordofwar81** [comment]
i have the keys no problem

**Comment by lordofwar81** [comment]
@benthecarman how we looking 🥹

**Comment by TonyGiorgio** [comment]
Looks like the 4 channels are showing up on the LSP side. One of them should have gone back on chain, and 3 are awaiting unilateral closure. May take up to a few more days. Should be able to check back on it on Monday.

**Comment by lordofwar81** [comment]
Glad its not lost.thanks for response

**Comment by lordofwar81** [comment]
i had 4 channels. My on chain balance is correct, but 1 of the 4 lightning channels definitely did not revert to the on-chain balance.

**Comment by TonyGiorgio** [comment]
Could you perhaps check your on chain addresses with a wallet like sparrow? If you put in your seed there and use the derivation path `m/86'/0'/0'`, it should show your chain states and balances and stuff. Curious if it shows up there. From what I can tell the 1 channel closure that already happened doesn't seem like a force closed one. Perhaps it's just not being picked up by the wallet.

**Comment by lordofwar81** [comment]
Need a couple hours. Will report back soon.

**Comment by lordofwar81** [comment]
@TonyGiorgio this remaining balance is different than what is in the wallet on chain. (2nd pic) The 980867 1263481 1184515 I assume are closed lightning channels. 1 is missing for sure.
![IMAGE 2023-07-14 15:24:36](https://github.com/MutinyWallet/mutiny-web/assets/61852793/9f45acfc-5b57-4fbc-98eb-f6817a756749)


![IMAGE 2023-07-14 15:26:04](https://github.com/MutinyWallet/mutiny-web/assets/61852793/202bf104-d9cd-4b2b-ba39-885e731673be)

**Comment by lordofwar81** [comment]
Actually i misspoke. The 970418 is the remaining on chain balance. Sparrow is showing that balance. the rest of the lightning balances are not here

**Comment by benthecarman** [comment]
These channels may not actually be recoverable. Talked to the LDK team and seems that the keys used for the channel are not recoverable without the lightning state. There's a chance we could make a tool to potentially brute force and recover but looking less and less likely.

![image](https://github.com/MutinyWallet/mutiny-web/assets/15256660/d9e9a3dc-bd4b-436a-94ce-64fab41f6919)

**Comment by lordofwar81** [comment]
I really hope that I am not punished by a forced channel closure that occured during your system update. I didnt do anything wrong 😢

**Comment by TonyGiorgio** [comment]
Try opening the wallet again and leaving it opened for a few minutes. I think the time locks should have expired and the sweep transactions should be possible now as of Saturday. 

For reference, here is your 4 channel closes that happened: 

https://mempool.space/address/bc1qvzg0guw67t0umtw2ngtur07mg23x523ttr3jrc
https://mempool.space/address/bc1qqtjwzf8u0wr9ltce3n0v9f598jtysvth2zta4m
https://mempool.space/address/bc1q2ks49kp2uxef3h205a8u9d238n0myjzshre9s3
https://mempool.space/address/bc1qwc6hzqelu0czhtc9hjeh3hyc6dxm9896eg4edl

**Comment by lordofwar81** [comment]
Thanks Tony. Opening now and will let it sit. I will report back in an hour.

**Comment by lordofwar81** [comment]
![IMAGE 2023-07-17 12:50:15](https://github.com/MutinyWallet/mutiny-web/assets/61852793/ed56ea33-b329-4f8b-877b-dcad645dda54)

Onchain balance is showing and available. Nothing else

**Comment by TonyGiorgio** [comment]
Was this on the original wallet where the channel closes happened? I don't see that in the activity list.

**Comment by TonyGiorgio** [comment]
You mentioned trying to open this wallet on iPhone too. If you can submit the latest logs again on the original device, we can see whether or not it is aware of the channels and trying to broadcast the sweep transactions.

**Comment by lordofwar81** [comment]
[mutiny-logs (1) (1).txt](https://github.com/MutinyWallet/mutiny-web/files/12073522/mutiny-logs.1.1.txt)
Here you go @TonyGiorgio

**Comment by lordofwar81** [comment]
this is from device running latest version of graphene OS

**Comment by TonyGiorgio** [comment]
Did you ever delete the wallet from the original device? These logs have no recover that they existed, yet in the image below there was at once a time where they did.

> its been deleted from 2nd device. the onchain funds are there. The channels are still gone. You can see swaps into lightning and no lightning balance. ![2023-07-13 14 25 02](https://user-images.githubusercontent.com/61852793/253410639-ca82418d-a277-4389-b742-3a9af454cdb2.jpg)

Have you ever done a "State save" in the past? There's an advanced setting for it and was the old way to save state before we implemented channel backups. Perhaps there's something that can be recovered from that.

**Comment by lordofwar81** [comment]
I didn't do a save state. I deleted everything per Bens instructions. If we see where the btc went upon the forced channel closure. Who has the keys to that btc, voltage? I only created one wallet with you guys and as such only have 1 keyset.

**Comment by TonyGiorgio** [comment]
He had meant from the second device, not delete everything completely...

When a force close happens, there's timelocks involved and it requires both parties to redeem their side of it. 

From these transactions, the LSP had redeemed what they were owed but each of the 4 unspent outputs are ones that your wallet needs to sweep after the timeout:

https://mempool.space/address/bc1qvzg0guw67t0umtw2ngtur07mg23x523ttr3jrc
https://mempool.space/address/bc1qqtjwzf8u0wr9ltce3n0v9f598jtysvth2zta4m
https://mempool.space/address/bc1q2ks49kp2uxef3h205a8u9d238n0myjzshre9s3
https://mempool.space/address/bc1qwc6hzqelu0czhtc9hjeh3hyc6dxm9896eg4edl

Deleting the original wallet which had your channel state on it makes it such that I don't think there's really a way to recover it. These did not go to the LSP. They are in limbo waiting for your wallet to redeem them. Sadly I don't think there's anything we can do. At the time that you joined private beta, we had warnings that lightning related data was not backed up and that you shouldn't put more into this wallet than you were comfortable with.

I'm waiting to confirm with the LSP that the sweeps are complete from their side of it. There's some longer time locks in lightning that could push things into 10 - 14 days. At least one of the channels was fully closed from their point of view but maybe the other 3 are still partially pending.

**Comment by lordofwar81** [comment]
I get that now. But he clearly said to delete both. Doesn't seem fair for me to get screwed over when I didn't do anything wrong.
![Screen Shot 2023-07-17 at 1 14 51 PM](https://github.com/MutinyWallet/mutiny-web/assets/61852793/a83bf915-4eaf-4a3e-a5b3-1de93d2b97e7)

**Comment by TonyGiorgio** [comment]
Perhaps it was a misphrase but what he meant was that running it on multiple devices was the problem. We were getting hit left and right with things on launch day when you were reaching out. I'm sorry if something got lost in translation. 

I get it doesn't seem fair. We're doing everything we can to investigate this and redeem your part of the channel. But without the channel data, there's a high likely hood at this point that all of those funds are lost forever on chain, not redeemable by anyone.

I just wish you hadn't put so much on there while it was still private beta, or even now that we launched and fixed a lot of these issues. I'm sorry this happened, but please don't put that much on here. This is all still experimental.

**Comment by TonyGiorgio** [comment]
It appears all channel closes show as completed on the LSP side now and no additional sweeps took place. There's no way anyone else can access those funds without your channel state that's been deleted. I am really sorry. I don't think there's anything else we can do here. We fixed many problems regarding state but that was after your channels were opened. Not sure why it had issues when it updated but if the data was still there it would have swept all the transactions.

**Comment by lordofwar81** [comment]
Appreciate the response Tony. Its pretty disappointing because i have been signing up everyone who would listen to me to test the wallet. Hard for me to reconcile a company asking people to use their product and then not offering anything when the product malfunctions. Thats a life altering amount of btc for my kids kids thats fucked off because i trusted you guys.
