### ISSUE TITLE
No sats from cash app 

### ISSUE THREAD

**Issue by csarge22** [MutinyWallet/mutiny-web#345]
Attempted 50000 sat send from cash app 2 hrs ago, still pending

**Comment by csarge22** [comment]
Ok, that worked. Now I’m trying to connect my mutiny to Nostr via Zapple pay to allow one tap zaps. I put the NWC string into Zapple pay, but I cannot figure out how to get the emoji zaps to work. Not sure if the disconnect is in Zapple pay, mutiny, or Damus. Any ideas?Sent from my iPhoneOn Jul 13, 2023, at 5:00 PM, benthecarman ***@***.***> wrote:﻿
You need to keep mutiny open to receive the payment, once you initiate the payment in cash app you'll need to open mutiny.

**Comment by benthecarman** [comment]
Zapple pay has been having issues, could be that
