### ISSUE TITLE
Scan QR Doesn't Work on iOS Safari Installed as PWA

### ISSUE THREAD

**Issue by leesalminen** [MutinyWallet/mutiny-web#346]
Hi there,

Just getting to try out Mutiny today for the first time. Love it! 

I'm running into an issue scanning QR codes with Mutiny wallet when installed as PWA on iOS. The camera never initializes, and am unable to scan a QR code. Specifically on iOS 16.5.1 on iPhone 12 Pro.

I've attached a short video demoing this here: https://github.com/MutinyWallet/mutiny-web/assets/3018359/ddff7c6e-cc5d-4b5e-a639-84bd5f21a284

It looks like Mutiny is using the `qr-scanner` package maintained by Nimiq (a non-BItcoin "crypto" company). I was looking into their issues and there do seem to be various iOS-specific issues on there, nothing that describes this issue perfectly. Perhaps there are more reliable/widely used QR scanning packages out there?  If you're open to using a different package I'd be happy to try and PR it.

**Comment by benthecarman** [comment]
yes we have #174 documenting this. seems like an ios issue and less of a library issue.

**Comment by leesalminen** [comment]
FWIW, we use `html5-qrcode` in our web wallet as part of the Galoy stack. Works fine on iOS as PWA, I use it nearly every day personally.

https://github.com/mebjas/html5-qrcode

**Comment by TonyGiorgio** [comment]
> FWIW, we use `html5-qrcode` in our web wallet as part of the Galoy stack. Works fine on iOS as PWA, I use it nearly every day personally.
> 
> https://github.com/mebjas/html5-qrcode

Looks like they have the same problem: https://github.com/mebjas/html5-qrcode/issues/713

**Comment by leesalminen** [comment]
> > FWIW, we use `html5-qrcode` in our web wallet as part of the Galoy stack. Works fine on iOS as PWA, I use it nearly every day personally.
> > https://github.com/mebjas/html5-qrcode
> 
> Looks like they have the same problem: [mebjas/html5-qrcode#713](https://github.com/mebjas/html5-qrcode/issues/713)

Very interesting indeed. As I mentioned, I use that package in my daily life buying things with lightning. Haven't experienced it. Perhaps it's some very weird iOS thing.
