### ISSUE TITLE
Adding other fiat currency value

### ISSUE THREAD

**Issue by HostFat** [MutinyWallet/mutiny-web#350]
Can you add other fiat currency values as EUR, GBP etc...

**Comment by futurepaul** [comment]
for sure. just curious: is it useful enough if this is a setting you set in settings, or do you need to switch all the time on the fly?

**Comment by HostFat** [comment]
I guess that it already good enough if it is a setting.

**Comment by benalleng** [comment]
@HostFat just want to follow up with you, as of #503 we have support for this! Is there a specific currency you use that may not be currently supported?
