### ISSUE TITLE
Sats not being received

### ISSUE THREAD

**Issue by Fonta1n3** [MutinyWallet/mutiny-web#351]
I sent 100,000 sats over signet. Got one confirmation yet my onchain balance shows as 0 still.

**Comment by dipunm** [comment]
I read that you have to wait 6 confirmations.

**Comment by Fonta1n3** [comment]
That would be strange. 

Either way my tx has more than 6 confirmations and the balance is still 0.

**Comment by dipunm** [comment]
https://blog.mutinywallet.com/mutiny-wallet-open-beta/

![Screenshot_20230714-110406](https://github.com/MutinyWallet/mutiny-web/assets/5099980/5b60ef46-e95c-4218-8a76-4b2cf3021206)

**Comment by benthecarman** [comment]
Our signet is our own custom signet, are you using that? 

faucet.mutinynet.com

**Comment by Fonta1n3** [comment]
Nope, will do.
