### ISSUE TITLE
'Add To Home Screen' option not available

### ISSUE THREAD

**Issue by toddkutzke** [MutinyWallet/mutiny-web#352]
under the Share button on iOS safari browser. This would be really nice to have ![image](https://github.com/MutinyWallet/mutiny-web/assets/931285/d2a00b24-f6b5-4cd3-8143-2797c8c2d6d1)

**Comment by futurepaul** [comment]
I'm confused, I see it in your screenshot?

<img width="772" alt="Screenshot 2023-07-14 at 10 12 38 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/d23fcec9-c160-4b76-bf05-5ca4fba1c293">

**Comment by toddkutzke** [comment]
OMG. How embarrassing. I'm an idiot. Sorry 🤷‍♀️😀
