### ISSUE TITLE
URL bar hides receive button iphone 8

### ISSUE THREAD

**Issue by marimes** [MutinyWallet/mutiny-web#363]
![image](https://github.com/MutinyWallet/mutiny-web/assets/12594437/4462a10b-1a38-4317-9b3a-4874d1f88cde)

**Comment by benthecarman** [comment]
Good find! If you add to home screen it will hide the navy bar

**Comment by marimes** [comment]
Yes, I found that and it works 😃. However, one then needs to redo the backup as one gets new words.Am 15.07.2023 um 10:04 schrieb benthecarman ***@***.***>:﻿
Good find! If you add to home screen it will hide the navy bar

**Comment by futurepaul** [comment]
this should be fixed now with the receive / send redesign #775 

<img width="487" alt="Screenshot 2024-01-13 at 1 58 22 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/e9825bb9-0ad9-4213-a041-7260e171c161">
