### ISSUE TITLE
Fees are too high

### ISSUE THREAD

**Issue by jurjendevries** [MutinyWallet/mutiny-web#364]
I had a non custodian android app before and it didn't need 50000 sats to start, so it is not clear to me why it is needed for this non custodian wallet. To have for example children on board for their pocket money, or people living in poverty but give them an unbanked experience we need fees that are around a couple of sats, that was some kind of written when the lightning protocol started. Now the fees are around 15 usd and that is even higher than an on chain transaction, while a part ot the idea about lightning was to lower transaction costs. I hope the bitcoin community can solve this somehow to make it accessible for a larger group. At least that is needed after beta.

**Comment by benthecarman** [comment]
The 50k sats does not all go to fees, there is just a 10k sat setup fee for the channel so we require a 50k minimum so people dont spend everything on fees. After you have a channel, there is only a 1 sat fee per tx.

This is voltage's flow 2.0 pricing, not ours
