### ISSUE TITLE
Channel closed because counterparty force-closed

### ISSUE THREAD

**Issue by paisalk** [MutinyWallet/mutiny-web#365]
I created a new wallet on my iPhone and imported the seed words to my browser.  I then received 100,000 sats into my browser wallet, a channel was created and everything worked ok.  I then switched back to use the same wallet on my iPhone and somehow the channel was force closed later.  Screen capture and log attached.

What should I do?  Please advise.  Thank you very much.

<img width="550" alt="Screenshot 2023-07-15 at 11 55 43 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/63239409/0948cb5c-9d73-4f6c-bea4-1ae37ff4a52d">

<img width="670" alt="Screenshot 2023-07-16 at 12 08 09 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/63239409/56fde2eb-3dd4-4265-a418-766ddc6c7528">

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12062261/mutiny-logs.txt)

**Comment by benthecarman** [comment]
You can't have the app on multiple devices otherwise it will cause force closes

**Comment by paisalk** [comment]
Is there anyway I can recover my fund or get the 90k sats back into my lightning balance?

**Comment by benthecarman** [comment]
Those funds should be sweeped back to you on chain wallet in the next couple days.

**Comment by paisalk** [comment]
ok thank you very much.

**Comment by paisalk** [comment]
My on-chain balance is now 0 and I do not receive any sats in my on-chain wallet.  Is this normal?  Thanks.

<img width="668" alt="Screenshot 2023-07-17 at 8 05 01 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/63239409/4b738b24-8b43-434a-941b-3899e3b3dec2">
