### ISSUE TITLE
[Feature Request] Sign Message

### ISSUE THREAD

**Issue by eznix86** [MutinyWallet/mutiny-web#367]
Some apps might ask to validate ownership of public key. To prove ownership, we often make use of a signature.

It would be nice to have an option in settings like 'Sign Message' where you have to paste a message and spit out the signed version which can be copied back to clipboard.

**Comment by benthecarman** [comment]
Do you want to sign a message with your node id or a specific address? Only reason I could see the use is signing into amboss but all of mutiny is private channels so that wouldn't do anything

**Comment by eznix86** [comment]
Actually what I was really talking about is proving ownership of the private key

**Comment by benthecarman** [comment]
Which private key

**Comment by TonyGiorgio** [comment]
The derivation path is `m/86'/0'/0'`

feel free to use the seed with some other wallet that participates in regulatory wallet signing practices, but I wouldn't if I were you.
