### ISSUE TITLE
Failed to find payment route is persistent

### ISSUE THREAD

**Issue by rctrinity** [MutinyWallet/mutiny-web#368]
Yesterday, no issues with sending LN payments.  Today, every try is a failure to same wallets sent to yesterday. 

From the logs:
WARN  [lightning::routing::scoring:1292] Payment failed at the first hop - we do not attempt to learn channel info in such cases as we can directly observe local state.
	Because we know the local state, we should generally not see failures here - this may be an indication that your channel peer on channel 878193131395678209 is broken and you may wish to close the channel.
2023-07-16 01:14:06.834 DEBUG [lightning::routing::scoring:1312] Not able to penalize channel with SCID 878193131395678209 as we do not have graph info for it (likely a route-hint last-hop).

**Comment by benthecarman** [comment]
Yeah this is something we detailed in our beta blog post. Payment routing isn't very reliable yet. We will be our next priority to work on.

**Comment by rctrinity** [comment]
Thanks.  I'll be patient.
