### ISSUE TITLE
Failed to load Mutiny

### ISSUE THREAD

**Issue by toddkutzke** [MutinyWallet/mutiny-web#369]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12065334/mutiny-logs.txt) i'm using Chrome on latest mac OS.

i successfully used munity for a day or two but today when I opened mutiny i received the "Failed to load mutiny" message.  attached are my logs. I've tried exporting and importing mutiny-state.json into a different browser but recv'd the same message. i was successfully able to use my 12 seed words in a chrome incognito browser to restore my wallet. also fyi i onboarded a normie friend to mutiny 2 days ago and they lost all their funds hitting the same error because they didn't save their 12 words. i've tried to upload my mutiny-state.json, but ofc github doesn't support that file type. now the tricky part i don't understand yet is how to restore my wallet on my iphone safari browser, because their i'm getting the "Error: Failed to read data from storage" message. How do i get rid of that message on my iphone safari browser and use the "Restore" feature to recover my funds there? If i hit the "Delete Everything" button does that just clear the browser cache or does that also delete my sats from my wallet?

Thanks for the help.

**Comment by benthecarman** [comment]
Hi, we currently have a bug with restoring from 12 words if you had an encryption password set for your wallet. If that is the case you can go to https://app.mutinywalet.com/settings/encrypt and set the password to what you had previously after you restore.

> If i hit the "Delete Everything" button does that just clear the browser cache or does that also delete my sats from my wallet?

that deletes everything, including your sats

**Comment by toddkutzke** [comment]
follow up to this message, I orginally hit this error tapping on my iphone safari home screen Mutiny icon. then exported mutiny-logs.txt and mutiny-state.json to my chrome mac osx browser. imorting mutiny-state.json on mac osx chrome failed, then i went to chrome incognito macosx browser and was able to restore my wallet using my 12 words.

**Comment by toddkutzke** [comment]
i did not set an encryption password on this current wallet b/c that's how lost all my sats in the first mutiny wallet i created. i must've hit that bug.

**Comment by benthecarman** [comment]
you really shouldn't be importing and exporting state unless you know what you are doing

**Comment by benthecarman** [comment]
from your logs:


```
3-07-16 23:27:08.141 ERROR [lightning::ln::channelmanager:8469] A ChannelMonitor is stale compared to the current ChannelManager! This indicates a potentially-critical violation of the chain::Watch API!
2023-07-16 23:27:08.141 ERROR [lightning::ln::channelmanager:8470]  The ChannelMonitor for channel 558d245917ecb80323aaff653f421752cc454c08f53b62a87c51938acac90579 is at update_id 7 with update_id through 7 in-flight
2023-07-16 23:27:08.141 ERROR [lightning::ln::channelmanager:8472]  but the ChannelManager is at update_id 50.
2023-07-16 23:27:08.141 ERROR [lightning::ln::channelmanager:8473]  The chain::Watch API *requires* that monitors are persisted durably before returning,
2023-07-16 23:27:08.141 ERROR [lightning::ln::channelmanager:8474]  client applications must ensure that ChannelMonitor data is always available and the latest to avoid funds loss!
2023-07-16 23:27:08.141 ERROR [lightning::ln::channelmanager:8475]  Without the latest ChannelMonitor we cannot continue without risking funds.
2023-07-16 23:27:08.141 ERROR [lightning::ln::channelmanager:8476]  Please ensure the chain::Watch API requirements are met and file a bug report at https://github.com/lightningdevkit/rust-lightning
```

**Comment by toddkutzke** [comment]
so if i haven't set an encryption pswd on this wallet how do i safely get back to a default wallet where i can use the restore feature on my iOS safari browser where I originally hit the error?

**Comment by toddkutzke** [comment]
update...i just opened a new safari tab on my iphone and now i'm seeing the default mutiny wallet with the restore funtion enabled

**Comment by toddkutzke** [comment]
trying a restore their now...

**Comment by toddkutzke** [comment]
that worked...sats restored on iOS safari now. thx.

**Comment by benthecarman** [comment]
Yay!

**Comment by toddkutzke** [comment]
what's interesting is that if i open my iOS Mutiny Home screen button i still get the "Error Faild to read data from storage message" even thoug i've successfully restored the wallet in a new safari tab. i guess i need to delete that home screen mutiny icon and then create a new one from the safari tab where i successfully restored?

**Comment by benthecarman** [comment]
> what's interesting is that if i open my iOS Mutiny Home screen button i still get the "Error Faild to read data from storage message" even thoug i've successfully restored the wallet in a new safari tab. i guess i need to delete that home screen mutiny icon and then create a new one from the safari tab where i successfully restored?

Yes, when you add to homescreen it no longer shares storage with the safari app. I would just delete the app and re-add to homescreen. You will need to restore from 12 words one last time. 

Make sure to clear the state from safari after that, if you have both open it can cause a force close.

**Comment by toddkutzke** [comment]
does closing safari clear the state?

**Comment by toddkutzke** [comment]
i closed safari and now tapping on the home screen my sats are gone...i guess this is where i need to restore from seed once again

**Comment by benthecarman** [comment]
> i closed safari and now tapping on the home screen my sats are gone...i guess this is where i need to restore from seed once again

yes

**Comment by benthecarman** [comment]
> does closing safari clear the state?

would be safest to use the delete everything button here, just make sure have the 12 words. also make sure the install version of mutiny is not open

**Comment by toddkutzke** [comment]
how do i know when it's safe to use the delete everything button and when it will delete my sats?

**Comment by benthecarman** [comment]
> how do i know when it's safe to use the delete everything button and when it will delete my sats?

if you have the 12 words written down you're safe

**Comment by toddkutzke** [comment]
got it...to confirm deleting everything doesn't delete your wallet sats just everthing on your devices browser, right? you can always restore from seed right?

**Comment by benthecarman** [comment]
> got it...to confirm deleting everything doesn't delete your wallet sats just everthing on your devices browser, right? you can always restore from seed right?

exactly

**Comment by toddkutzke** [comment]
ok...i successfully have an iOS home screen buttion i can open and close and my sats are there again. i did not have to hit the delete everthing button. thanks for the quick response! you guys are creating a game changer here. can't wait to see how it develops. not quite ready to try onboarding my normie friends yet though.

**Comment by toddkutzke** [comment]
i'd like to connect with you (benthecarman) on simplex. attached is my invitation link.
![IMG_CAA29AD806FD-1](https://github.com/MutinyWallet/mutiny-web/assets/931285/b84084ed-8492-4dca-9f82-4be62dafcdf4)

**Comment by benthecarman** [comment]
accepted invite!
