### ISSUE TITLE
My on-chain balance is now 0 and I do not receive any sats in my on-chain wallet.  Is this normal?  Thanks.

### ISSUE THREAD

**Issue by paisalk** [MutinyWallet/mutiny-web#373]
My on-chain balance is now 0 and I do not receive any sats in my on-chain wallet.  Is this normal?  Thanks.

<img width="668" alt="Screenshot 2023-07-17 at 8 05 01 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/63239409/4b738b24-8b43-434a-941b-3899e3b3dec2">

_Originally posted by @paisalk in https://github.com/MutinyWallet/mutiny-web/issues/365#issuecomment-1638108747_

**Comment by TonyGiorgio** [comment]
Could use some logs if you have that. It looks like it would have been a force close channel and that may take a few days on chain to be redeemed. But the logs would help confirm that. When you click on the "channel close" button, does it show the reason for the close?

**Comment by paisalk** [comment]
Please refer to #365 .  I have already uploaded the log there with description of channel force close.  Thanks.

**Comment by TonyGiorgio** [comment]
Also can you give your node it? It is in settings -> admin 

In all likelihood, running two browsers at the same time with the same seed caused this issue and we will probably have to pass this request off to the LSP to see where the funds are. It could have been in a terrible state that caused them to sweep the funds. Do not run multiple browsers at the same time with the same seed.

**Comment by paisalk** [comment]
Yes, I will never run multiple browsers again.
Here is the log and node ID.  Thanks a lot.

Node ID : 03a92ae85c7872a2265863f5eeec63f95613615396357fb1d7da9b1be818bfb5a6

[mutiny-logs (2).txt](https://github.com/MutinyWallet/mutiny-web/files/12071349/mutiny-logs.2.txt)

**Comment by TonyGiorgio** [comment]
Okay, these logs weren't very detailed either, probably all the information was on the other instance. No worries, we should be able to dig up stuff just from the node id. Will report back once we learn something.

**Comment by paisalk** [comment]
Thank you so much.  Really appreciate your support.

**Comment by TonyGiorgio** [comment]
So the good news is that it looks like the entirety of it went back to the LSP: https://mempool.space/tx/3ff3decb23a693acd022ab5f16fa1c300d145178fc436c165c81633f56d156fc

Now we just gotta figure out what portion should have gone back to you. I think in your case, it closed pretty suddenly after you were doing this? Did you happen to send or receive any payments before the channel closed?

**Comment by paisalk** [comment]
Yes, it closed suddenly. I did not send any payment before the channel closed.

**Comment by TonyGiorgio** [comment]
Okay that looks accurate on the LSP side as well. Mind if you send a bitcoin address in a DM to me or the mutiny account on nostr? Or join our matrix and DM me there? 

https://matrix.to/#/#mutiny-community:lightninghackers.com

**Comment by paisalk** [comment]
Thanks.  I just sent my bitcoin address to the Mutiny Wallet account on nostr.  Thank you very much.

**Comment by TonyGiorgio** [comment]
Sent on chain. Sorry this happened again but glad we were able to recover it. Let us know in another issue if there's any further problems you have. Thanks!
