### ISSUE TITLE
Screen capture video of channel close

### ISSUE THREAD

**Issue by extrapockets** [MutinyWallet/mutiny-web#375]
I was trying to screen-capture a bug where NWC kept showing old payments that I had already approved. During this video, I got a message that 2 tabs were open, then a forced channel close. There's a lot going on that is over my head here, so I am attaching the logs and video in case this is useful to developers more familiar with the project.

[mutiny-logs (5).txt](https://github.com/MutinyWallet/mutiny-web/files/12073840/mutiny-logs.5.txt)

[Link (encrypted)](https://void.cat/5mScKNJphUyCbBQQwWkpRV) 

Encryption key for video:

2494684b8659d04e9ba0e859743f6fee:9c1d23cd20b701c2d3f73a14

**Comment by TonyGiorgio** [comment]
And yes, there's a duplicate invoice paid bug we are aware of. Right now if that happens, you can just click X and it shouldn't appear anymore (but new ones may still come, just hit X on those when you get that warning).

**Comment by extrapockets** [comment]
I see now. That was a channel close and open from a month ago. Thanks for the explanation.

**Comment by TonyGiorgio** [comment]
Hopefully those confirm or cancel at some point soon. We don't have a way to bump the transactions at the moment.
