### ISSUE TITLE
Funds stuck after a force close

### ISSUE THREAD

**Issue by SeanGriffithz** [MutinyWallet/mutiny-web#380]
Hi, I jumped the gun and opened the wallet on a second device leading to my channels being force closed... 90,000 sats are showing but not available... I've waited a week to see if they would arrive but to no avail :(

**Comment by SeanGriffithz** [comment]
I sent over 100,000 sats... 10,000 went on the creation of the channel leaving 90,000 in the channel... that channel then got force closed and the funds sent back to my on chain wallet, but the 90,000 sats are not available to spend.

The BlueWallet screenshot is the transaction sending over the 100,000 sats.

![image](https://github.com/MutinyWallet/mutiny-web/assets/77235172/494dc5eb-bbb7-4958-859a-7f21037386cb)
![image](https://github.com/MutinyWallet/mutiny-web/assets/77235172/0243d146-71ad-4562-83e5-9ed4cccb0fd8)
![image](https://github.com/MutinyWallet/mutiny-web/assets/77235172/0672c0e1-5ccb-4750-bb79-0458c91fecaf)

**Comment by TonyGiorgio** [comment]
The logs are in the "emergency tools" section of the settings page. 

To get transaction ids, click on the force closed transactions and a little pop up will have that info.

**Comment by SeanGriffithz** [comment]
My transactions aren't going back to the day of the transaction?

![image](https://github.com/MutinyWallet/mutiny-web/assets/77235172/1b56c3d0-5796-4bf5-9132-cbe64014d61e)

**Comment by SeanGriffithz** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12099502/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
So the 111000 on chain balance is correct but when you go to swap it, only 21k shows as available. Does the same happen when you go to "send" and try to send it to an on chain address? 

If so, maybe go to "admin tools" in the settings screen and click on just the "resync wallet" button. Then restart the app and wait a few minutes. It might show as 0 balance while it pulls down all the transactions again.

**Comment by SeanGriffithz** [comment]
I've re synced my wallet, waited five minutes and nothing has changed... also I'm still only able to send 21,000 on chain

**Comment by benthecarman** [comment]
> I sent over 100,000 sats... 10,000 went on the creation of the channel leaving 90,000 in the channel... that channel then got force closed and the funds sent back to my on chain wallet, but the 90,000 sats are not available to spend.

you need to wait for the force close to be swept, it can take awhile sometimes

**Comment by TonyGiorgio** [comment]
I did run into it recently where the balance says something more than what it appears and no indiciation in the activity list. I think it's due to a pending sweep that still needs to wait. I see there's other force closes and activity, but specifically for the 90k problem, how long has it been since you noticed that? There might have been another force closure that is still taking awhile. This can be up to 10 - 14 days technically but often just 3 days.

**Comment by SeanGriffithz** [comment]
The force close for 90,000 was back last Wednesday or Thursday so 12th or 13th... the 2nd device that caused the force close still had the Mutiny window open so when I went to use that device again, that's what triggered the other force closures, those cleared in a day or two... I'd say it's been a solid week so far since the initial 90,000 force closure.

**Comment by TonyGiorgio** [comment]
If this still has not come back yet, could you provide your node id? It is in settings > admin tools, at the top

**Comment by SeanGriffithz** [comment]
Hi, it is still the same 90,000 not available to be used...
Node ID: 02b1d0d33c0f21ba86720e1002ec230c0e8e943122c9b376975e217799528bef9d

**Comment by TonyGiorgio** [comment]
Forwarded this to the LSP, waiting for a response

**Comment by SeanGriffithz** [comment]
Hi, is there any update regarding this as nothing has changed and I think I may cut my losses and get a new wallet?

**Comment by SeanGriffithz** [comment]
Hi, please see the on chain address below... Thank you and apologies for any inconvenience.

bc1qfysnpffttzd92y0lsjwuwpkk0m8nsc8spsth65dcwwrkcac5fa8seydxpk

**Comment by TonyGiorgio** [comment]
Funds should have been sent back, sorry about the issue and delay.
