### ISSUE TITLE
Simnet or local dev

### ISSUE THREAD

**Issue by astanciu** [MutinyWallet/mutiny-web#383]
Any way to connect mutiny to local networks for dev purposes? For ex to pay an invoice generated on simnet?

**Comment by TonyGiorgio** [comment]
RIght now we have a signet version at https://signet-app.mutinywallet.com/

And yes, you can configure the endpoints at https://github.com/MutinyWallet/mutiny-web/blob/master/.env.example if you want to point things to your own network. For instance like esplora.
