### ISSUE TITLE
Force Closed - Error broadcasting transaction

### ISSUE THREAD

**Issue by jnsats** [MutinyWallet/mutiny-web#389]
My channel was forced closed on July 13 with the following message:

> Channel closed because of an exception: Peer attempted to reestablish channel with a very old local commitment transaction

Exported logs and noticed the following error message repeated several times in the log–the latest from July 22 17:57Z:

> 2023-07-22 17:57:43.390 ERROR [mutiny_core::onchain:73] Failed to broadcast transaction (REDACTED): Reqwest(reqwest::Error { kind: Status(400), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("mempool.space")), port: None, path: "/api/tx", query: None, fragment: None } })

> 2023-07-22 17:57:43.391 WARN  [mutiny_core::chain:56] Error broadcasting transaction: Failed to broadcast transaction (REDACTED): Reqwest(reqwest::Error { kind: Status(400), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("mempool.space")), port: None, path: "/api/tx", query: None, fragment: None } })

Messaged @benthecarman via Nostr five days ago and sent him the logs via email.

Received communication from Ben 4 days ago that the next release (released yesterday) should fix the issue, but still seeing the error message above.

Reached out to Ben and he recommended I create an issue here.

My sats are sitting in limbo. Gents, please help me recover my sats!

**Comment by benthecarman** [comment]
Added Context:

I think multiple were running, from logs:

```
2023-07-14 12:42:30.665 TRACE [lightning::ln::peer_handler:1218] Disconnecting peer due to a protocol error (usually a duplicate connection).
2023-07-14 12:42:30.665 ERROR [mutiny_core::networking::socket:84] got an error reading event: Peer Sent Invalid Data
2023-07-14 12:42:30.665 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
```

was hoping for a good force close but does not seem like it :(

@jnsats if you could provide your node id (at the top of settings > admin page) and any relevant tx ids that would help us recover the funds from the LSP

**Comment by jnsats** [comment]
Node ID: 03a8d2751a41bea4dd7337e1167b4dabf10e9184ae6ff4da5d5ba003289d42de27

TXID: This should be included in the logs I sent to you. Do you want me to post it here? Privacy concerns.

**Comment by TonyGiorgio** [comment]
I have forwarded this along to the LSP to see what channels were involved and what happened to them on chain. Should be able to find out what we need just from the node id. I'll let you know what we learn.

**Comment by TonyGiorgio** [comment]
Is there a particular amount that the channel close would have left you with? Any balance you're expecting back on your side?

**Comment by jnsats** [comment]
Yes, 490,000 sats.

**Comment by jnsats** [comment]
Yes. The actual on-chain balance is zero. It says "No balance" when I try to swap it into lightning.

**Comment by TonyGiorgio** [comment]
Could you provide an om chain address to send the funds back to?

**Comment by jnsats** [comment]
Sure. What’s the best way for me to privately send this to you?

**Comment by TonyGiorgio** [comment]
Nostr or email: team@mutinywallet.com

**Comment by jnsats** [comment]
https://send.bitwarden.com/#n1F_ib5rzE6v47BPAAOSnQ/EH0pZnI4crT1zNSeYto6lA

Password to access coming via Nostr.

**Comment by TonyGiorgio** [comment]
Thanks, got it and provided it to the LSP.

**Comment by TonyGiorgio** [comment]
Resolved.
