### ISSUE TITLE
Tried to swap on chain to Lightning with out luck

### ISSUE THREAD

**Issue by Bird84** [MutinyWallet/mutiny-web#390]
Hi, I recently sent 100k sats on chain to my Mutiny wallet. Worked perfectly👌🏽

Tried to swap 50k of them to Lightning for trying it out on one of my Nostr clients.

It didn’t go through and the attempt costed me around 12k which I don’t quite understand. Except the around 1700sat fee for opening the channel (which didn’t go through)

Not sure what I should have done differently and what is needed to add here to help you understand what’s going on. So have just added som screen dumps of what I’m seeing:-)

Hope this helps.

![IMG_5371](https://github.com/MutinyWallet/mutiny-web/assets/140345540/d299a7a6-c0e0-4ad5-9ac8-60fd94a92974)

![IMG_5372](https://github.com/MutinyWallet/mutiny-web/assets/140345540/3e4bf9ee-e9ce-4a0d-ad8c-6dd9647d6838)

![IMG_5373](https://github.com/MutinyWallet/mutiny-web/assets/140345540/fb7904ef-e049-4cd3-9b07-e1a3277d1868)

![IMG_5374](https://github.com/MutinyWallet/mutiny-web/assets/140345540/b1eac8af-fe1c-43a6-9a3d-a173d0adc949)

**Comment by benthecarman** [comment]
The error you got normally happens when you have the wallet open on multiple devices, did you do that?

**Comment by Bird84** [comment]
hi Ben.No, I have only been tinkering with Mutiny on my phone.RegardsBird1984On 23 Jul 2023, at 21.21, benthecarman ***@***.***> wrote:﻿
The error you got normally happens when you have the wallet open on multiple devices, did you do that?
