### ISSUE TITLE
Back button on android close the app

### ISSUE THREAD

**Issue by Turtlecute33** [MutinyWallet/mutiny-web#391]
Device infos:
Pixel 7
Android 13.0 grapheneOS

If you press the back button the app will close.
Could be good if the back button in the settings menu works ad 'return to home' button and if you press back on the home pop-up a 'do you want exit?' message

**Comment by TonyGiorgio** [comment]
Thanks! Yeah just noticed that myself. Weird because back works on the web just fine. Probably just a setting I need to find somewhere.

**Comment by TonyGiorgio** [comment]
Fixed
