### ISSUE TITLE
Channel closed

### ISSUE THREAD

**Issue by Rabbitholeorange** [MutinyWallet/mutiny-web#394]
Channel closed without warning

d175adbfb1a7d0a8b88f4a72382abf65acc966aa66793b5946d4965aca68a903

**Comment by benthecarman** [comment]
Can you provide more information? Logs, channel close reason, what you were doing.

**Comment by Rabbitholeorange** [comment]
Hey Ben,First things first.  I’m not a techie.  I downloaded a mutiny to play with it.  Had an issue but had to open a github account.  I have no idea how to use the system and couldn’t work out how to submit attachments etc.So, I transferred 50000 sats without issue. I e backed up my wallet but I received a message stating the channel was closed.  Pl. see attachments. Funds still appear in wallet. Hope this helps.  Good luck with this project.  Sounds amazing! Sent from my iPhoneOn 26 Jul 2023, at 00:08, benthecarman ***@***.***> wrote:﻿
Can you provide more information? Logs, channel close reason, what you were doing.

**Comment by Rabbitholeorange** [comment]
Sent from my iPhoneOn 26 Jul 2023, at 00:08, benthecarman ***@***.***> wrote:﻿
Can you provide more information? Logs, channel close reason, what you were doing.

**Comment by Rabbitholeorange** [comment]
Did you receive the attachments? Sent from my iPhoneOn 26 Jul 2023, at 00:08, benthecarman ***@***.***> wrote:﻿
Can you provide more information? Logs, channel close reason, what you were doing.

**Comment by benthecarman** [comment]
No, maybe email them here: team@mutinywallet.com

**Comment by benthecarman** [comment]
Got the email, looks like you had the wallet open across browsers, that will cause force closures. Make sure you are only using the wallet on a single device/browser at a time. If you restore it into a new one you should delete it from the previous one.

We have something in the works that should prevent this in the future.

**Comment by Rabbitholeorange** [comment]
No problem.  I was able to restore the wallet but have no lightning channel.  Does this mean I can’t send/receive sats or should I just send another 50k?Yes, I had a browser open on my Mac, MacBook and iOS as I was playing with it but restored without issue (other than the channel) 😆Sent from my iPhoneOn 26 Jul 2023, at 00:39, benthecarman ***@***.***> wrote:﻿
Got the email, looks like you had the wallet open across browsers, that will cause force closures. Make sure you are only using the wallet on a single device/browser at a time. If you restore it into a new one you should delete it from the previous one.
We have something in the works that should prevent this in the future.

**Comment by benthecarman** [comment]
You might get the funds back within a few days, otherwise it might have been a bad force close and the LSP has it now, but we should be able to recover it

**Comment by Rabbitholeorange** [comment]
It’s not a problem. Thanks, Ben. Sent from my iPhoneOn 26 Jul 2023, at 00:46, benthecarman ***@***.***> wrote:﻿
You might get the funds back within a few days, otherwise it might have been a bad force close and the LSP has it now, but we should be able to recover it

**Comment by TonyGiorgio** [comment]
If the funds have not come back yet in the wallet, you can provide us your node id and we can pass it along to the LSP. Your node ID is in settings > admin tools, at the top.

**Comment by TonyGiorgio** [comment]
Let us know if the funds have not been swept back.

**Comment by Rabbitholeorange** [comment]
Hello Tony, Ben etc,

Funds were swept back.

Good luck
