### ISSUE TITLE
Real tx / invoice / utxo detail pages

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#40]
- [x] lightning
- [x] onchain
- [ ] uttxo

<img width="630" alt="Screenshot 2023-05-11 at 5 53 45 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/0a716294-21a3-4b97-8f4a-aa327b142a2f">

**Comment by TonyGiorgio** [comment]
Let's not worry about UTXO quite yet, we can create a seperate issue for that when we want it. Everything else is complete.
