### ISSUE TITLE
On chain balance is stuck

### ISSUE THREAD

**Issue by Kruwed** [MutinyWallet/mutiny-web#415]
I closed a channel, my on chain balance appears at the top of the home screen, but when attempting to send the coins it says "No balance".

OS: Ubuntu Linux
Browser: Firefox

**Comment by TonyGiorgio** [comment]
Please provide screenshots, logs, and the node id in the admin tools settings page.

**Comment by Kruwed** [comment]
Node ID: 025b44696204b972d2c1b136a5955cb476e02a28cb695d31c91eb5bcb71c1349db

![image](https://github.com/MutinyWallet/mutiny-web/assets/118238055/840844f9-0e8a-4dc5-abc1-c84522ece86a)

![image](https://github.com/MutinyWallet/mutiny-web/assets/118238055/f1488e16-0fe9-40e3-88e1-8b08e81dfd61)

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12207616/mutiny-logs.txt)

Also, what seed type/derivation path is used by my 12 words?

**Comment by benthecarman** [comment]
> Also, what seed type/derivation path is used by my 12 words?

Everything is Taproot so it's m/86'/0'/0'

**Comment by Kruwed** [comment]
> > Also, what seed type/derivation path is used by my 12 words?
> 
> Everything is Taproot so it's m/86'/0'/0'

I can see my UTXO is in a bc1q address though - https://mempool.space/tx/3decd4e2e3e86f6e7372ade5080152a3d813f8e01bb4e5ea58f5a3c4c2413f6f

**Comment by benthecarman** [comment]
That is from a force close, you need to wait for it to be swept to your onchain wallet

**Comment by TonyGiorgio** [comment]
If you click on the channel close item, what does it say is the close reason?

**Comment by Kruwed** [comment]
> If you click on the channel close item, what does it say is the close reason?

Cooperative - 
![image](https://github.com/MutinyWallet/mutiny-web/assets/118238055/8f383bb7-7fba-47bf-95b6-c48677e4c0a8)

**Comment by Kruwed** [comment]
The UTXO was swept from the force close and was recovered.  Thanks guys.
