### ISSUE TITLE
Allow user to adjust the invoice expiration time

### ISSUE THREAD

**Issue by bilthon** [MutinyWallet/mutiny-web#416]
It seems like invoices expire after ~~10 minutes~~. That's reasonable default, but for some applications we'd need more, so it would be nice to allow the user to change this in settings.

**Edit:** It seems like I was parsing the invoice incorrectly and the expiration time is actually more than 10 minutes. The point of having a way to customize it still stands though.

**Comment by TonyGiorgio** [comment]
Is there any particular application you use that needs more time? I think it's an hour expiration but I forget.

**Comment by bilthon** [comment]
I just checked, and the current invoice expiration time for the signet version of the wallet is 1490 seconds, or ~25 minutes.

An invoice expiration time of at least 1 hour is currently required for [lnp2pbot](https://lnp2pbot.com/). This makes sense because a P2P trade can easily take that, or a bit longer to complete.

But regardless, I feel like there could be more applications for which a longer lasting invoice might be desired. It's nice to have a sensible default, but it's also useful to be able to change this in (advanced?) settings.

**Comment by TonyGiorgio** [comment]
We just set the default timeout to 1 hour. Can't easily support more than that in the current moment but hopefully that will resolve things with lnp2pbot. Should be deployed on next release, maybe end of week for some minor bug fixes release.
