### ISSUE TITLE
Allow retry on Failed to load mutiny (already running) screen

### ISSUE THREAD

**Issue by rolznz** [MutinyWallet/mutiny-web#423]
I saved the PWA and tried to restore it but I was already running the app on my PC *and* in safari on my phone. I closed the PC one and closed the PWA, and re-opened and still got it. Then closed the safari version and closed and re-opened the PWA on my phone again, and now it works.

It might be good to have a refresh button and also guide the user to where they should close the app (I think this could happen to some people who save the PWA and directly use it?)

**Comment by TonyGiorgio** [comment]
We added this on a dedicated page that warns the user what's happened and it has a refresh page now.
