### ISSUE TITLE
Idea: Allow a web app or mobile app to pre-configure a NWC connection

### ISSUE THREAD

**Issue by rolznz** [MutinyWallet/mutiny-web#424]
With Alby the webapp can pre-configure new connection settings and can do something like: https://nwc.getalby.com/apps/new?c=TestApp&pubkey=c5dc47856f533dad6c016b979ee3b21f83f88ae0f0058001b67a4b348339fe94&return_to=https%3A%2F%2Fexample.com&budget_renewal=weekly&expires_at=1687594345492&max_amount=100&editable=false

The benefit here is the webapp is the one who generates the NWC private key, and only passes the public key to NWC where you can confirm the new connection. There is no need to copy the NWC url back to the app, which is more secure and better UX for the user.

Example apps that could use this: [Zapple Pay](http://zapplepay.com/), [Alby ZapPlanner](https://zapplanner.albylabs.com/), Mobile Nostr clients (Damus, Amethyst, Primal, etc)

**Comment by benthecarman** [comment]
NWA is the replacement for this!
