### ISSUE TITLE
Missing on-chain balance

### ISSUE THREAD

**Issue by hex17or** [MutinyWallet/mutiny-web#425]
So I deposited some sats on chain to my Mutiny wallet. After the tx was confirmed, I could not see the balance in my wallet, but after multiple app closures and relaunches, I could see the balance reflected on chain. However, when I opened the app today, I can no longer see my on chain balance, even after closing and relaunching the app. 

I even tried the resync wallet option as described [here](https://github.com/MutinyWallet/mutiny-web/issues/382#issuecomment-1644243204) but it did not work and I still cannot see my on chain balance.

Can you help resolve this?

Device - Android smartphone.

Nodes: 036f6beb32b43d7f9022ae4eeabc02c842525cb1c1377bc20c12f43546b12f863a

Let me know if you require any other information.

**Comment by benthecarman** [comment]
Our method for syncing is currently being rate limited by mempool.space, we should have some fixes going out soon.

If you need your funds before the update goes out you can enter your seed phrase into sparrow wallet to get access to your on-chain funds

**Comment by benthecarman** [comment]
An fix was just pushed, that should fix the issues!

**Comment by hex17or** [comment]
Sorry but this is happening again. Any ideas?

**Comment by TonyGiorgio** [comment]
> Sorry but this is happening again. Any ideas @benthecarman ?

are you on the latest android version?

**Comment by hex17or** [comment]
I can't see a version number. Is there any way I can check/ update as it is a pwa?

**Comment by benthecarman** [comment]
If you're on the pwa you should be on their latest version. 

Can you confirm that in the settings > servers page the esplora link is mutiny.mempool.space

**Comment by hex17or** [comment]
Yes that link looks correct. 
![Screenshot_20230816-030253](https://github.com/MutinyWallet/mutiny-web/assets/48261276/f55fe5e7-f571-46b4-8ff7-05fc50e42092)

**Comment by benthecarman** [comment]
Hmm okay, can you post your logs? Either can attach them here or email to us at team@mutinywallet.com

**Comment by benthecarman** [comment]
In your logs you are getting the successful `We are synced!` log. If you enter your seed into something like sparrow does your balance show up?

**Comment by TonyGiorgio** [comment]
maybe try the "chain sync reset" button in the admin page too.

**Comment by hex17or** [comment]
Sorry, was away for some time hence just getting back to this. I tried a chain sync reset as suggested by @TonyGiorgio and now I can see my on chain balance in the pwa. Thanks. I'll monitor the behavior for a few days and report if the problem happens again.
