### ISSUE TITLE
Keysend Support

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#46]
![Screenshot from 2023-04-25 11-35-29](https://user-images.githubusercontent.com/101225832/234344031-b2b4d637-3bff-4095-a2a5-f85d58baacf7.png)

**Comment by futurepaul** [comment]
working on keysend, almost there but it's not going through:

![Screenshot 2023-04-26 at 6 02 09 PM](https://user-images.githubusercontent.com/543668/234720840-4d6565c8-23b6-4151-8acf-2f63e93cf0ed.png)

(paying to the lsp node I'm peered with... get the same error when I try to pay our lnd node)
