### ISSUE TITLE
Changing send amount after too high requires starting over

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#462]
1. Have an amountless invoice or keysend to a node
2. pick an amount over your balance
3. get the error that amount is too high
4. change the amount to 1 sat (singular, not plural....)
5. the error still doesn't let you send

![signal-2023-08-17-134116_002](https://github.com/MutinyWallet/mutiny-web/assets/101225832/5860ed40-c635-4dcc-8b57-eed47d7996bc)

**Comment by climardo** [comment]
found my bug. thanks for opening the ticket @TonyGiorgio

**Comment by benalleng** [comment]
Are we able to make an amountless invoice from within mutinywallet or the signet?

**Comment by benthecarman** [comment]
> Are we able to make an amountless invoice from within mutinywallet or the signet to test?

No

**Comment by benalleng** [comment]
Ok,well  I hacked together a quick test and figured it out.
