### ISSUE TITLE
Just logged in, channel is force-closed immediately, funds missing

### ISSUE THREAD

**Issue by Strunzdesign** [MutinyWallet/mutiny-web#475]
Hi,

before I start: I sent you a support email because I was unable to send a payment of 30k sats to nostr.wine. To date, I got no response from you.

Some minutes ago, I logged into mutiny wallet and immediately saw my lightning channel got closed. What happened here?

Furthermore, about 30k of funds are now missing. My balance was higher than 70k the last time I logged off, and now it reports a balance of only 46k sats. Something is very wrong here.

Please check and fix. And please refund the missing sats.

Log will be attached

**Comment by Strunzdesign** [comment]
Logs
[mutiny-logs-20230821.txt](https://github.com/MutinyWallet/mutiny-web/files/12401632/mutiny-logs-20230821.txt)

**Comment by Strunzdesign** [comment]
Update: the missing funds seem to be there, the UI just increased my balance to 76.878 sats (on-chain). So far, so good. But why was the channel closed?

**Comment by Strunzdesign** [comment]
Reason: "Channel closed because commitment or closing transaction was confirmed on chain."

No, i did not close the wallet for an extended period of time. In fact, I sent you a support EMail last Thursday. that was the last time I tried sending 30k sats to nostr.wine, which failed.

**Comment by TonyGiorgio** [comment]
I see a payment that was in the process of being received on friday that stopped because the app was closed. So when you opened the app today, that HTLC was expired and the channel closed.

**Comment by Strunzdesign** [comment]
Ok, that makes sense. However, I never closed the browser prematurely. Instead, I got an error "no route found" or "timeout": the big red X in a circle. It was just impossible so send funds to nostr.wine, for days. Today is the first time that a channel close happens.

My thoughts were that the channel close is related to my support request; that the payment failed due to a bug or a state mismatch. That you fixed something in the background, and now the system triggered some sort of a cleanup.

Anything I can do? Was the routing issue analyzed?

**Comment by Strunzdesign** [comment]
Sorry for a maybe dumb question: is that the expected behavior that lightning channels are closed in that case? If I get a negative confirmation that my payment fails, then what kind of timelock could be triggered here? Does that mean, that network hickups during payments lead to channel closes? Why? The payment clearly didn't get through, and my local balance was not affected. All is in order. Why should that lead to a channel close?

Regards,
Florian

**Comment by benthecarman** [comment]
> Sorry for a maybe dumb question: is that the expected behavior that lightning channels are closed in that case? If I get a negative confirmation that my payment fails, then what kind of timelock could be triggered here? Does that mean, that network hickups during payments lead to channel closes? Why? The payment clearly didn't get through, and my local balance was not affected. All is in order. Why should that lead to a channel close?
> 
> Regards, Florian

In most cases this shouldn't happen. Since you got a HTLC timeout what likely happened is that on one of the payment attempts that timed out, the payment never fully resolved back to you. You likely closed the app (unless you left it open for a few hours/days) and during that time the channel had to be closed because the HTLC had expired.

Sorry about the failed payments to nostr.wine. This is something we are still working on. Mutiny does all client side routing so it has trouble sometimes finding routes to uncommon destinations. We added their node to our prober which should hopefully help with getting payments there

**Comment by Strunzdesign** [comment]
Ok, thanks for the information. I'm aware of the beta status, and want to help to improve. But to be honest, you really should safeguard this somehow. I consider myself tech-savvy, but you target a much broader audience.

Last question: now that the lightning channel was closed, shouldn't I see an on-chain transaction towards my 12-words wallet? There are just the two transactions that initiated the journey, but no subsequent from today reflecting the channel close. Even in the mempool I see no transaction.

**Comment by TonyGiorgio** [comment]
> But to be honest, you really should safeguard this somehow.

There's a warning on the receive screen about keeping the app opened while the payment is being received. Perhaps that should be more apparent? 

> now that the lightning channel was closed, shouldn't I see an on-chain transaction

Yes, but there's some sweeps that have to take place due to the HTLC timeout nature of what happened with your channels. That may take a few days. We do need to improve this indication somehow because it's not obvious.

**Comment by Strunzdesign** [comment]
Ok thanks. I'm going to monitor my wallet, no problem for me to wait some days.

But again: I got the explicit message that the payment was aborted (timeout or route not found). That was _after_ waiting 20 seconds for the payment to be processed. Then I maybe went back to the wallet screen, or just closed the browser tab. What message do you expect me I ignored, that indicated that I should have kept something open? There was nothing! The failure screen has a clear message: failure. Nothing to do. No need to wait for anything.

That timeout screen seems to be the culprit. It indicates a final error state, but in reality, it should tell the user that one has to wait... for how long, for what event? Good questions. I don't know... but "Timeout" is misleading, especially without such a warning as you mentioned.

**Comment by TonyGiorgio** [comment]
Okay, I was confused by the logs, yes you're right that was on the send side. I agree some more indication about it's state should happen.

**Comment by Strunzdesign** [comment]
Now my mutiny wallet account shows 46k sats again. 30k are missing again, as mentioned in my initial post.

**Comment by TonyGiorgio** [comment]
Sweep is needed and will take a few days.

**Comment by TonyGiorgio** [comment]
Opened up a ticket for the timeout information: https://github.com/MutinyWallet/mutiny-web/issues/480

And also for one to visually indicate when a sweep is still pending too: https://github.com/MutinyWallet/mutiny-web/issues/477

If the sweep doesn't occur after a few days, please let us know. Thanks for your patience and conversations.

**Comment by Strunzdesign** [comment]
Success!

I confirm that the swipe happened and my funds are now back and are completely on-chain. I needed to login to mutiny wallet once to trigger the transaction after waiting 3-4 days. I expected that to happen automatically in the background, but you need to login after the system performed its sweep internally, to trigger the payout (likely the receive addresses had to be calculated?). Maybe, as a suggestion, you should inform users affected by a forced close / swipe that they (a) need to wait 3-4 days and (b) then(!) have to login once again to trigger the on-chain transaction. Just waiting is not enough.

Interestingly, the funds went on chain with two transactions; I expected one, but I need to dig into how a lightning swipe works.

Kind regards,
Florian

P.S. I ask myself if i should go full Homer Simpson mode and just use the recovered funds to open another fresh channel. This would be how testing works... but the frequent routing issues made me hesitant. Maybe after the weekend.

**Comment by TonyGiorgio** [comment]
Glad you were able to recover. Yes that's the flow and ideally it doesn't happen but unfortunately due to bugs we didn't predict it would happen that much. Will work on it. 

FYI, we're working on payment reliability but one thing I will say is the nostr.wine node is terribly connected to the rest of the network: https://mempool.space/lightning/node/031cad9dce02864079c35c6f2b797337e864d7b818ac6e5f7ff52ba4a3cccc4ec3

We're already having difficulty with popular routes but this one will be hard. If you're seeing other destinations having failures after today, please let us know which ones.
