### ISSUE TITLE
just remote results in `No matching version found for @mutinywallet/ui@*`

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#478]
❯ just remote
pnpm unlink "@mutinywallet/mutiny-wasm" && pnpm install
 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @mutinywallet/ui@* inside the workspace

This error happened while installing a direct dependency of /data/Dev/Mutiny/mutiny-web
error: Recipe `remote` failed on line 10 with exit code 1

**Comment by benthecarman** [comment]
try `pnpm run build-submodules`

**Comment by TonyGiorgio** [comment]
Didn't fix it.

**Comment by TonyGiorgio** [comment]
> pnpm unlink only removes the links in your current directory.

I think that's what we'd want. `mutiny-node` is what makes the link. No reason to uninstall it system wide when I often switch between the two versions.
