### ISSUE TITLE
Indicate "pending progress" information when timeout happens

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#480]
Timeout looks like payment failure, which is not the case. This has lead to at least one case of a force closure because the app was closed after the payment looked like it failed: https://github.com/MutinyWallet/mutiny-web/issues/475

We need more indication that the payment is pending, instead of a red X. We also need to warn that the wallet still needs to be opened for the payment to finish.

**Comment by benthecarman** [comment]
We now have a pending payment screen
