### ISSUE TITLE
Channel forced close - cannot retrieve funds 

### ISSUE THREAD

**Issue by MatulefM** [MutinyWallet/mutiny-web#487]
[Screenshot ](https://cdn.nostr.build/i/5ad447523229fbb3255df2215dd933f241fb7c4c0b6a3024c30faa5ed9c4967f.jpg)

**Comment by MatulefM** [comment]
[Balance display ](f10442a58e65fc43ba8f2169fdc324f7bc9923fe1dc58515038920ffaaad564b.jpg) 

[Swap to lightning ](https://cdn.nostr.build/i/43bf59e1ceb2a5d1d5fd9d4e7f90671a475f582b30b8d7dcc37fea1cd7aeccf9.jpg)

**Comment by benthecarman** [comment]
It can take a couple days for your funds to be swept from the force close. 

Please wait and report back if they haven't shown up after 3 days

**Comment by MatulefM** [comment]
Funds are available. Closing issue.
