### ISSUE TITLE
Channel Forced Closed, Funds moved on-chain but disappeared

### ISSUE THREAD

**Issue by stasgnikcats** [MutinyWallet/mutiny-web#488]
[Logs](https://github.com/MutinyWallet/mutiny-web/files/12432595/mutiny-logs.txt)

[Screenshot 1 of Force Closed Channel Screen](https://github.com/MutinyWallet/mutiny-web/assets/137927093/deb141db-32e4-487c-b765-39c8696e2832)
[Screenshot 2 of Force Closed Channel Screen](https://github.com/MutinyWallet/mutiny-web/assets/137927093/96dc7e3e-2c50-4061-82e4-0d3d630b9445)
[Misc Feedback: Can see there's an extra "S" in the word 'Reason' / Also lack of text wrapping for formatting]

Node ID: 03928b247d2924a533ed889c174b682034895eb48d40b7695685cff539a02f4600

Timeline - 
8/22
- Created wallet on Mac (Chrome Browser) > added password
- Sent 60k sats to wallet > established 1 channel and showed 50k sats in lightning wallet
- Closed browser
- Restored wallet on iPhone as PWA via seed words
- Everything normal, balance showing 50k sats in lightning wallet. I could see the lightning channel established under the settings.
- Created new password & closed PWA
- Hours later, I attempted to open PWA to show someone the app > received an error
- Closed PWA and restarted it. Entered password and wallet loaded. However, now activity showing lightning channel forced closed
- Funds showing 50k sats in on-chain wallet
- Closed PWA

8/24
- Opened wallet on PWA, entered password and now no balance showing for either wallet

**Comment by TonyGiorgio** [comment]
>  I attempted to open PWA to show someone the app > received an error

What was the error? According to the logs, there's no log indicating that the device sent over the error message described in the message. Another device that was running must have sent that. We do what we can to prohibit multiple devices from running at the same time but we're always amazed at users that find a way anyways. Do you have the logs from the browser instance?

**Comment by stasgnikcats** [comment]
I wish I had a screenshot of the message presented on iPhone PWA wallet. I don't remember the verbiage of the error, but it was about the channel and force close. Additionally, I just tried to download the Mac instance logs, however it does not do anything when I click the "Download Logs" button under the emergency kit (so unfortunately, no Mac logs). I did notice that the Mac instance wallet still required the first/original password I set. Is this because the current browser state is saved and the password is tied to that password? 

I have saved the current state as json. I can try to delete everything on my Mac browser instance (chrome), create a new wallet and attempt to replicate this from step 1. If I can reproduce the issues, I can screenshot along the way.

**Comment by TonyGiorgio** [comment]
> however it does not do anything when I click the "Download Logs" button under the emergency kit

That's odd. Only heard of someone else that had that issue on iOS once. Can you open up the console logs when you open up mutiny and try to download the logs? Maybe there's some indiciation there about what's going wrong. 

>  Mac instance wallet still required the first/original password I set

Yes, the password set is local just to your device and the local storage that is saved. 

> I have saved the current state as json. I can try to delete everything on my Mac browser instance (chrome), create a new wallet and attempt to replicate this from step 1. If I can reproduce the issues, I can screenshot along the way.

Please don't try to reproduce it with real funds, especially when we haven't recovered yours yet. We have forwardedd this to the LSP to investigate further. If you want to try to reproduce, use the signet version: https://signet-app.mutinywallet.com & signet faucet https://faucet.mutinynet.com

**Comment by TonyGiorgio** [comment]
I have reproduced the logs error, seems like it wont download when there's a password set: https://github.com/MutinyWallet/mutiny-web/issues/513

**Comment by stasgnikcats** [comment]
[The console logs from today](https://github.com/MutinyWallet/mutiny-web/files/12527562/Mac-mutiny-console-logs.log)

The console was showing the following issue:
<img width="554" alt="Mutiny-console-alert" src="https://github.com/MutinyWallet/mutiny-web/assets/137927093/96ad09e4-81b3-48a1-ab40-8052462fa03b">

**Comment by TonyGiorgio** [comment]
We should have a fix soon for the log download issue, maybe we can find out more later if the logs are still there. 

Otherwise, if you provide an on chain address, we can have the LSP send the funds back.

**Comment by stasgnikcats** [comment]
bc1qdl8jg84txryy040f9ck2sn2ff448r02j7ylxqh

Let me know when the fix for log download goes in and I'll try to retrieve the Mac instance logs

**Comment by stasgnikcats** [comment]
Here are the logs from the Mac/Chrome session: 
[Mac-instance -mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12553157/Mac-instance.-mutiny-logs.txt)

Thanks for investigating!
