### ISSUE TITLE
App launching with decrypt password prompt

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#502]
Got 2 reports of the new version of mutiny launching asking for a password when there was not a password set. Restoring from seed fixes the problem.

**Comment by benthecarman** [comment]
Looking through the code the only way I think this could happen is if they haven't opened the app since before #669. In the local storage handling we don't handle parsing the old encoding.

Can you ask them if that is the case?

**Comment by TonyGiorgio** [comment]
Doesn't seem to be happening anymore.
