### ISSUE TITLE
Payment pending but not reflected on Mutiny

### ISSUE THREAD

**Issue by sachintr27** [MutinyWallet/mutiny-web#504]
Tried to send a payment from Phoenix to Mutiny.

Contacted Phoenix and they say that the target node is holding the payment and is neither fulfilling nor failing it.

Payment is still pending on Phoenix but it isn't getting reflected on Mutiny.

Payment hash: 132b96141904474fe0c03bad8b29d0e5efb204a98a8cf370a7d2b1c73e4f1ea2

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12498667/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
It never makes it to your wallet and it's possible it never makes it to the LSP either. It could just be stuck in the network and will show back up in your Phoenix wallet. I'll reach out to the LSP to double check that there's not a bug with the forwarding of it but everything looks fine to me from your logs.

**Comment by sachintr27** [comment]
Thanks for responding!

I've got my funds back in my Phoenix wallet now.
