### ISSUE TITLE
Dev reloading too much

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#51]
I hit some pages sometimes and `vite` keeps trying to "optimize dependencies" and it reloads all my instances sparatically. Not sure what I need to do to turn that off.

```
5:05:02 PM [vite] ✨ new dependencies optimized: qr-scanner
5:05:02 PM [vite] ✨ optimized dependencies changed. reloading
```

**Comment by futurepaul** [comment]
yeah that's annoying I've just been living with it. can probably fix with this: https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-disabled
