### ISSUE TITLE
Add "about" section in settings that shows version

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#522]
I actually was close on this on a branch I ended up abandoning: https://github.com/MutinyWallet/mutiny-web/pull/280/files#diff-da5546638ec3db6cb8a9ab1801d8565cda27daf1b02747e2bb81a9ad7265cc1a

`VITE_COMMIT_HASH` is still available in builds btw (I know it's not the most user-useful info, but it's the "truest" info about what version of the app a user is actually seeing)

**Comment by TonyGiorgio** [comment]
Even showing it at the bottom of settings would be great. People have been asking for any sort of indication.

**Comment by futurepaul** [comment]
closed by #530
