### ISSUE TITLE
Channels Force Closed, funds not showing up on chain (logs included)

### ISSUE THREAD

**Issue by hodlcuban** [MutinyWallet/mutiny-web#525]
Hi -

I moved some funds to mutiny today and set up nostr wallet connect in amethyst. I processed a number of zaps but got a notification later in the day that the two channels were force closed. The comment in the channel close was.

"ChannelManager read from disk was stale compared to ChannelMonitor(s)"

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12567049/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Hey sorry about this, your funds should show up in a couple of days at most. Let us know if they don't

**Comment by hodlcuban** [comment]
No worries, but I do have a couple follow up questions. Was it something I did in the wallet? Can I keep it from happening. Looking to use this as my main lightning wallet but don't want to open channels every time.

Thanks!

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by benthecarman** [comment]
We're still tracking down the _exact_ reason this happens but we suspect this happens when you close the app/page too quickly after an invoice has been paid. Waiting a couple seconds after a payment to close the app should help

**Comment by hodlcuban** [comment]
Thanks! I'll try again and be more careful switching apps after payments come through. Appreciate the answers
