### ISSUE TITLE
Artificial 2 second sleep after payment success

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#527]
Could help with some force closures that are happening when users close their app right as soon as a payment was made but it hasn't fully written to disk / server yet. 

Probably not needed after LDK 117

**Comment by benthecarman** [comment]
We had this before at the mutiny node level, forget why we removed it.

**Comment by benalleng** [comment]
Is this closed by https://github.com/MutinyWallet/mutiny-node/pull/772?
