### ISSUE TITLE
Channel Force Closed

### ISSUE THREAD

**Issue by Brian1-A** [MutinyWallet/mutiny-web#533]
Hello,
my channel was force closed this morning.  Please see attached logs for your review.  Thanks!

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12611338/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
This for `Peer attempted to reestablish channel with a very old remote commitment transaction`. I believe it could be from a persistance that didn't go through, given the proximity of the last payment and the next time it booted up.

Has the funds swept back to you from this? Would have taken a few days and a transaction called "Swept Force Close". If not, let us know the node id in the settings and we can pass this along to the LSP.

**Comment by Brian1-A** [comment]
Hi Tony,

The channel was force closed and I have gotten the funds back at this time. Thanks for checking.

- Brian

------- Original Message -------

**Comment by TonyGiorgio** [comment]
Great, thank you for confirming!
