### ISSUE TITLE
Unable to send funds

### ISSUE THREAD

**Issue by Azz125125** [MutinyWallet/mutiny-web#536]
I opened a channel from phonex wallet to Mutiny. I pushed 1000000 sats to Mutiny and was able to send 11000 back, but now it can't find a route. I have tried sending to WoS but can't find a route there either. 

How can I get my funds out?

**Comment by TonyGiorgio** [comment]
Try now if you can? We made some changes to the route finding scorer about 2 days ago. Otherwise, you can close the channel in the admin tools page in the settings.
