### ISSUE TITLE
Gifting

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#540]
this is mostly done in #421 but need to rebase that PR and then test / make sure it lines up with what we want to accomplish

## Purpose

As a kind, benevolent individual I want to onboard my friends to mutiny via a gift.

Should just be available to mutiny+ users.

## Frontend
- [x] create gift
- [x] redeem gift
- [x] rebase
- [x] show gifting link on send screen
- [x] if not on mutiny+, explain that you need mutiny+
- [x] update mutiny+ features list
- [x] warn them if it's lower than 50k
- [x] can delete a gift
- [x] add qr scan link to main navbar

## Backend
- [x] functionality

## Testing
- [x] not enough funds on sender
- [x] too small amount for receiver (if it's a fresh wallet)
- [x] trying to redeem twice
- [x] loading from url
- [x] loading from scanner

**Comment by benalleng** [comment]
Do you think It's worth adding the qr-scanner to the AmountEditable Page as opposed to the homepage?
![image](https://github.com/MutinyWallet/mutiny-web/assets/108441023/e7bc647a-0ec0-4bef-b835-b7b6128c3cfc)

**Comment by TonyGiorgio** [comment]
There's a lot of things a QR code scanner can do that are not related to creating an invoice, which is how you get to that amounts editable screen. LNURL pay/withdraw/auth being some of them.

**Comment by benalleng** [comment]
Tested on firefox mobile web
- Not enough funds on sender error only happens on the receiver side
- below 50k sats shows a warning on sender and an error on receiver
- scanner and url both work as expected

**Comment by TonyGiorgio** [comment]
Nice work!
