### ISSUE TITLE
mutiny+ nwc shouldn't show QR and auto approve should be simpler

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#541]

**Comment by benalleng** [comment]
Do all Mutiny+ nwc connections share a commonality we can check for when displaying it to the user?

Are there any other instances where we would want the nwc to have this similar UX?

**Comment by TonyGiorgio** [comment]
I think there could be a more "subscriptions" like NWC profile in the future. But the unique thing about mutiny+ is that it is intended to only work with mutiny in a bit of a more seamless way, so it doesn't need to do things like show the QR code. Meanwhile any other external app / service would need to see that QR code / screen.

**Comment by benalleng** [comment]
Picking this one up any desire to show the nwc string to the user?
