### ISSUE TITLE
Redesigned payment details

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#545]
<img width="514" alt="Screenshot 2023-09-20 at 3 15 05 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/d81f5ff6-4b54-4813-9539-152ecbf71274">

fullscreen, available from the send success view

**Comment by TonyGiorgio** [comment]
Nice! My first thoughts on if the text can be a bit more vertically dense (something about it seems too scattered / random spacing). Also not sure i like the underlining for the long text.

**Comment by futurepaul** [comment]
yeah agree on the underlines, I have a comment in the figma. I kind of like the larger spacing but we can tweak that til we're all happy. mostly want to confirm we're cool with fullscreen payment details (they'll be a route rather than a modal)

**Comment by benalleng** [comment]
When creating the routes I am currently using the txid. is there any serious privacy implication for this? Should I instead transition to its index in the users activity?

**Comment by benthecarman** [comment]
That should be fine

**Comment by benalleng** [comment]
Came across a blocker for tags, I figured out a hacky way to grab the first tag but I can't get any more beyond that. What exists now doesn't really work to properly grab the tags from the tags.

**Comment by benalleng** [comment]
At the moment our signet
![image](https://github.com/MutinyWallet/mutiny-web/assets/108441023/08bbd4bc-9c7b-4386-9515-e0739b717137)
