### ISSUE TITLE
Tag transaction rewrite

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#546]
<img width="714" alt="Screenshot 2023-09-20 at 3 26 41 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/acb284b2-02e7-4977-8211-2ac352cb12e6">

Have a lot of different issues related to tags so hope to make this the one major issue for fixes because we need a rewrite

- [ ] flesh out design more to include recent tags / nostr contacts?
- [ ] figure out how sorting works
- [ ] build it (maybe a total rewrite instead of using solid-select)

**Comment by miawhite21** [comment]
Worked on the design a bit more - might prototype some of it to help with clarity

[Link to figma](https://www.figma.com/file/jv72zrIZkNPz70qMsau0K9/Mutiny?type=design&node-id=3055%3A46566&mode=design&t=uBXLQwZ1dRH6Mf8s-1)

**Comment by benthecarman** [comment]
we no longer have this
