### ISSUE TITLE
feature: private transaction labels

### ISSUE THREAD

**Issue by DanConwayDev** [MutinyWallet/mutiny-web#553]
add a private label to a lightning transaction stored only locally on the wallet eg. 'hairbands for my manbun' or 'scissors to chop off my ridiculous man bun'.

**Comment by TonyGiorgio** [comment]
We already have this.

**Comment by DanConwayDev** [comment]
I can see 'private tags' on the 'Receive' page but nothing on the 'Send' page or adding / amending a label from the transaction summary pop up.
