### ISSUE TITLE
feature: improved ln address handling

### ISSUE THREAD

**Issue by DanConwayDev** [MutinyWallet/mutiny-web#554]
Here are a few ideas to improve the UX when dealing with ln addresses.

### 1. 'searching' message
When I type a few letters and press 'continue' I get a 'invalid payment request' message. When I type an address in email format and press 'continue' I get no feedback at all. The app detects the ln address format and begins processing it but doesn't notify the user at all. Suggestion: the 'continue' button should be disabled and change to 'Searching...' until the OnChange event is trigged on the 'destination' input.

### 2. 'unknown' recipient in 'activity'
A transaction sent to a ln address is listed as 'unknown' in the 'activity'.

A better experience would be to store and display the ln address in place of 'unknown'. Even better, when sending to a new ln address it should provide the option to add a label for the contact.

### 3. ln address lookup OnChange in 'destination' field

Another idea is, as I type in the 'destination' field on the 'send' page, it should look up the ln addresses (and associated labels) I have added or sent to in the past and provide me with selectable options.

I was manually typing the same ln address in multiple times over the course of a few hours. One time I did a typo and could have sent to the wrong person if the typo was a valid ln address.

**Comment by benthecarman** [comment]
This is done now, thanks for the suggestions!
