### ISSUE TITLE
bug: state export decypt password prompt

### ISSUE THREAD

**Issue by DanConwayDev** [MutinyWallet/mutiny-web#555]
**test**: state export from `Error: Mutiny is already running` page
**setup steps**: Error: Mutiny is already running` page
* setup password encryption
* get to the `Error: Mutiny is already running` page.
* click 'Save State As File' button
**actual behaviour**:
* prompted with all caps message "do you want to replace your state with" followed by an input box and 'Decrypt Wallet' button.
* unsure whether this is actually going to export the state or attempt to restore a empty state so I stopped

**expected behaviour**:
* not prompted for decryption password again (I don't need this reveal my 12 words)
* state saved to file and notified to tell me

How I got here:
I tried to move from web version to APK. I restored from the backup using 12 words but my activity only showed the on-chain transition to create the channel. My lightning balance was correct though. I thought I could compare the state and attempt to import the web state into the APK as all I have done is open it and check the activity and I only have 1 channel open with the default LSP. Do you think this is safe or does the App make changes to the state of a single lightning channel in the background without prompting me when not using NWC features?

I successfully exported the state from the APK version. I attempted to export the state from the web and I encountered this bug.

I love what you are doing with this wallet! Thanks for your hard work.

**Comment by benthecarman** [comment]
If you wait two minutes this error will go away

**Comment by DanConwayDev** [comment]
ah ok. I got the same issue when I access it from the Emergency Key page. I recklessly so entered my password and it presented me the json file. I think the prompt text is a bug.

The APK version didn't have the lightning state until I imported it for some reason.

The clicking the 'delete everything'  button on the web version was pretty scary after validating the APK version had the data. Perhaps you could outline 'scenarios where this is appropriate' before a conformation prompt?
