### ISSUE TITLE
Channel Close. Loss all my fund. 

### ISSUE THREAD

**Issue by agslai** [MutinyWallet/mutiny-web#557]
What do I need to do to get my fund back?Thanks.

Channel ID: 06c5b23fedca775ed327d7492b32f5269c9397f7eb4f7274b5eafc40355f71b7

![image_123650291](https://github.com/MutinyWallet/mutiny-web/assets/122250196/f49c56fb-eef1-4dc1-8d1f-57158d5cb7b5)

**Comment by TonyGiorgio** [comment]
Submit the logs and the node id. We can take a look.

**Comment by agslai** [comment]
I found the logs but where  can I find the node id? 
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12707253/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
It's in the admin settings at the top

**Comment by agslai** [comment]
Found it. Thank you.

03f4b5e556d9c59d3fe40e2a512a85fcc42e04d5b016f4650b3fb3d0e8bef4de49

**Comment by TonyGiorgio** [comment]
Does it sound accurate that it was for about `62,193` sats?
There's a missing channel update that isn't in the logs. Do you use the same wallet on multiple devices? What's the current os/browser that you sue?

**Comment by agslai** [comment]
Yes. 62k sats sounds about right. I did not know that I cannot run 2 devices at the same time for the same wallet. Right now, I run it in my iPhone. I think Safari.

**Comment by TonyGiorgio** [comment]
> I did not know that I cannot run 2 devices at the same time for the same wallet

You can, but I'm curious if you did or not. Because there's either some missing logs that could be a result of the state not persisting or from it being on a different device. So you only run on the same phone?

**Comment by agslai** [comment]
Yes i did try to run on a different device.

**Comment by TonyGiorgio** [comment]
Do you still have that device around to get the logs off of?

**Comment by agslai** [comment]
I deleted it. It was from my tablet

**Comment by TonyGiorgio** [comment]
That's fine, would have helped prevent the issue going forward, but odds are there was a bug with the multi device syncing and that's why it happened. I'm pretty sure the funds are on the LSP side, so I'll talk to them tomorrow. Can you provide a bitcoin address we can refund the payment to? Either here or email us again.

**Comment by agslai** [comment]
lnbc1pj3pkfjpp5jtdemerq6dpwp5ulgcq2erh7rqd3w6ejw5uqz8y5dr03ezgxvqrsdqqcqzzsxqyz5vqsp53awyrhrpcvchz3crlawnzfz9xqjvtxqpr4qdmkptrhk32n2e4ucs9qyyssqgxxwf5su4zapee2s8l94vseusvnudls6kzjpgtgj2unc9n0ghsu5j092z4gksgde5fger57zy6j9xxka6juwhguxdp623gcfxxjc8ygp68puxp

**Comment by TonyGiorgio** [comment]
It's not going to be immediate and will take up to a few days to verify with the LSP, please send a bitcoin address instead.

**Comment by agslai** [comment]
bc1q87u46v4uzx4gytd25rv6x4e4dxz29cnv6y08hd8myefdcmtu6caqga6jcp

**Comment by agslai** [comment]
Hi Tony, any update?  :)

**Comment by TonyGiorgio** [comment]
Should have been sent earlier today.

**Comment by agslai** [comment]
Awesome, thanks for the update!
