### ISSUE TITLE
problem trying to send sats from my Mutiny wallet from browser

### ISSUE THREAD

**Issue by chuck-shanks** [MutinyWallet/mutiny-web#561]
I'm having some kind of basic newb problem using the wallet to send sats.   I've tried many many times with different amount of sats, and every time I get timed out.  I mainly tried sending sats to a River LN wallet and then tried a Strike LN wallet, but every time I just time out.  Tony asked me to open ticket here and attach my logs.

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12740656/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Thanks for doing that. Nothing out of the ordinary, just a bunch of bad routes. We're consistently trying to make this better, sorry about that.

**Comment by chuck-shanks** [comment]
thanks, but what should I do?  Just keep trying the same thing indefinitely?

**Comment by TonyGiorgio** [comment]
If you want your sats immediately there's a close channel button in the admin tools section of the settings.

**Comment by TonyGiorgio** [comment]
It will be moved to the on chain portion of your mutiny wallet and you can send on chain or move it to a different wallet if you want.
