### ISSUE TITLE
Enumerate all possible payment failure states

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#569]
For design we want to be sure we know all the payment failure states the wallet can tell us about, and what actions are available to the user (and any "why" we can tell the user)

**Comment by miawhite21** [comment]
I think we might have done this a while ago, here's what I have so far on the designs:
[Link to the designs](https://www.figma.com/file/jv72zrIZkNPz70qMsau0K9/Mutiny?type=design&node-id=2932%3A75955&mode=design&t=w0Vx5qsmtHvQGDCV-1)

1. **Payment route not found** (Solution: Retry later, request smaller invoices, or ask for a Bitcoin address.)
2. **Payment timed out** (Solution: Things to try to make your payment go through: Make sure your connection is good, Make sure the receiver’s connection is good , Make sure the receiver has their phone open, Maybe the LSP doesn’t have enough liquidity as the moment.)
3. **The Lightning invoice has expired.** (Solution: Ask the receiver for a new one.)
4. **Low balance - whether both, onchain, or LN** (Solution: load up balance, ask for smaller amount, or enter a smaller amount in case the user is the one setting the amount or use the other balance if it's just one that is low and you entered an unified invoice or swap some funds from one balance to the other). The solution for this one depends where you are on the flow when sending.
5. **Format not recognized** (Solution: Make sure you entered a valid Bitcoin address or invoice.)
6. **Wrong network** (Solution: make sure you enter an invoice, address for mainnet)
