### ISSUE TITLE
UI changed to Signet

### ISSUE THREAD

**Issue by davidohayon669** [MutinyWallet/mutiny-web#576]
didn't touch the wallet for a few days, opening it now and it says "SIGNET" at the top and tells me the channel was closed for this reason:
![image](https://github.com/MutinyWallet/mutiny-web/assets/7001025/a4754923-451a-4720-969a-c015b2f75cb0)
![image](https://github.com/MutinyWallet/mutiny-web/assets/7001025/ec794204-368b-4f99-b357-eb64d9a1a466)
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12786132/mutiny-logs.txt)
2023-09-29 is the last day things worked great
2023-10-02 is when i opened it today and it was like in the screenshots from the beginning

this is PWA installed in iOS. i don't use this account on any other browser and didn't change anything on purpose

**Comment by TonyGiorgio** [comment]
Okay thank you for reporting this. Try refreshing again and seeing what happens? It appears that a preview deployment got pushed to production.

**Comment by davidohayon669** [comment]
@TonyGiorgio looks ok but the channel was closed again...

**Comment by benthecarman** [comment]
Really sorry about this Cloud flare deployed our signet version to production.

https://www.cloudflarestatus.com/incidents/t53r6tfsg1sj

We're adding a check so this will at least not startup the app next time:

https://github.com/MutinyWallet/mutiny-node/pull/786

**Comment by benthecarman** [comment]
> @TonyGiorgio looks ok but the channel was closed again...

You should get your money back in a couple days, if not reached back out to us. Same thing happened to me and @TonyGiorgio so we should be able to reproduce anything that happens

**Comment by davidohayon669** [comment]
@benthecarman @TonyGiorgio you need to figure out a way to refund the setup fees for these issues. i've got two unwanted closures already

**Comment by TonyGiorgio** [comment]
> @benthecarman @TonyGiorgio you need to figure out a way to refund the setup fees for these issues. i've got two unwanted closures already

It'll take some work but eventually we'll have free channel opens for mutiny+ subscribers and plan on giving a free month or two to people that have had closed channels or something. 

But lightning isn't without force close issues across the board. Unexpected things and edge cases happen with all implementations. Unfortunately that's the state of lightning and we do what we can to stop these from happening as much as possible. More fixes for common closes are going out this week. Thanks for being a beta user and helping report these.

**Comment by davidohayon669** [comment]
@TonyGiorgio of course you cannot expect these things, but the expected service from an LSP should be known. liquidity shouldn't be free, that's not the issue, but it is need to be usable across failures

a better UX might be to pay for the liquidity periodically from the channel itself - for example you are required to pay each month some constant fee to preserve an opened channel of X capacity - then the most you can lose for a failure is a month worth of service
