### ISSUE TITLE
No feedback when failing an attempt to send to a lightning address

### ISSUE THREAD

**Issue by NickRHill** [MutinyWallet/mutiny-web#594]
Using the web wallet on Chrome on Android, I attempt to send to a lightning address by clicking send then put an address in the form name@domain.com

When I click Continue, the button briefly turns blue, but nothing happens. No explanation what error is occurring. The lightning address stays in the field, all I can do is go back.

**Comment by NickRHill** [comment]
Also tried on desktop Linux Chromium. Same behaviour.

**Comment by benalleng** [comment]
It's most likely that that lightning address is malformed, we should definitely present that error to the user though

**Comment by benalleng** [comment]
when pressing `Ctrl+Shift+I` or right-click => inspect do you see this error?
`Uncaught (in promise) Failed to call on the given LNURL.`

**Comment by NickRHill** [comment]
A-ha, it is a CORS issue. The lnurlp is static content and no specific Access-Control-Allow-Origin header has been set.

This won't be a problem in an app, but will potentially be a problem in a web browser unless the lnurlp specifications state that such resources should have an Access-Control-Allow-Origin: * header set.

I think either way, the promise rejection should trigger a helpful error message.

Access to fetch at '---redacted---'from origin 'https://app.mutinywallet.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by benthecarman** [comment]
Ah yeah, should reach out to the owner of the domain and ask them to add cors

**Comment by NickRHill** [comment]
I have added an accept header. That fixed the problem for that domain. 

For apache
# a2enmod headers
In apache server config eg virtualhost
        <Directory /home/user/httpdocs/.well-known/lnurlp>
                <IfModule mod_headers.c>
                        Header set Access-Control-Allow-Origin "*"
                </IfModule>
        </Directory>

If that header isn't part of the spec (I suspect it isn't), then a work-around could be implemented. A proxying server to relay the request in the event of CORS failure  would be fairly easy. In any case, a helpful message which at least shows the wallet understands the address but there was an error fetching the lnurl resource would be good.
