### ISSUE TITLE
Closing a channel bricks the wallet

### ISSUE THREAD

**Issue by benalleng** [MutinyWallet/mutiny-web#596]
Only observed on local when testing closing a channel when running locally seemed to have to do with megaStore described it as an unknown Error

`ERROR [mutiny_core::vss:167] Error parsing get objects response: error decoding response body: invalid type: string "cHFDc3/2hWo3AgF9ZazzZFImpmsKOnpXPfnCHtr/apeaHFpU8TjtjpCP2eFT1CmmBAHmL8HNqd2ULIqQxxwNqVO2O/rIwGV+ligNEG4kDVxW81pbt4gkNZIh+zoMFbiw", expected a sequence at line 1 column 159`

[mutiny-logs(2).txt](https://github.com/MutinyWallet/mutiny-web/files/12897211/mutiny-logs.2.txt)

**Comment by benthecarman** [comment]
What is your vss url? It should be https://storage-staging.mutinywallet.com/v2

**Comment by benalleng** [comment]
nope, not on v2, must've never switched since the upgrade

**Comment by benalleng** [comment]
Fixed! thanks for catching that!
