### ISSUE TITLE
support: Force closed channels

### ISSUE THREAD

**Issue by skellam** [MutinyWallet/mutiny-web#599]
Installed Mutiny+ wallet on Chrome iOS.    Sent sats to lightning wallet twice.  Two channels were opened.  The next day I opened app and noted both channels force closed with message "Channel closed because of an exception: Peer's feerate much to low. Actual: 499. Our expected lower limit: 750 (- 250)"   The channelid for the close does not show up on mempool.space.  On the front page, my sats show up in the on-chain balance but when I try to sweep this balance or send it to another walllet, the app states my on-chain balance is 0.  It's difficult for me to see what's going on and I'm not sure if the channels have force closed and the transaction is just pending.  Not sure why the channels that I just opened were force closed.  Any assistance would be appreciated.    Logs attached.  thanks

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/12916893/mutiny-logs.txt)

**Comment by skellam** [comment]
I looked at the logs a bit and it appears the two closing transaction for the force closed lightning channels were confirmed on chain.
c5caddde7487af38b3c784361332f5765bb5ba5b6d3eb0f1368c78f486b80516
e0aa7f3ee66e0eb634044403be335e61ef10a94200b2429a2933d4579adfbbc8

So, not sure why I can't sweep or send the sats in the app.

**Comment by TonyGiorgio** [comment]
How long as it been since the force closed happened?

**Comment by skellam** [comment]
13 hours

**Comment by TonyGiorgio** [comment]
May take up to 3 days for the sweep transaction to occur. We are working on having this info displayed in the app. If it doesn't appear back after 3 days, let us know and we can take a look again.

**Comment by skellam** [comment]
Ok, thanks.   Was there anything I did that may have caused the force close?   I don't think I did anything unusual.  Just sent some sats to wallet.

**Comment by TonyGiorgio** [comment]
No, a fee rate issue between your wallet and the LSP. These occasionally happen on the lightning network but we've been cutting them down as much as possible. Perhaps some like this one still remain. We can look into this one more.

**Comment by skellam** [comment]
Thanks, the funds appeared after about a day.
