### ISSUE TITLE
Lightning send when close to limit (leaving room for reserve/fees) failed

### ISSUE THREAD

**Issue by tnblumer** [MutinyWallet/mutiny-web#607]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13033876/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Thanks for providing these. About half of these errors have been due to outdated gossip errors which we might have just fixed yesterday. Would like to know if it has gotten any better at all.
