### ISSUE TITLE
Feature Request: Self-host at different location

### ISSUE THREAD

**Issue by shyfire131** [MutinyWallet/mutiny-web#614]
I was able to follow the self-host instructions without issue for the most part, however I'd like to lock down access to the web server. 

Easy options:

1) IP whitelisting
2) Basic auth
3) Random path

Neither 1 nor 2 are ideal because I want to access my wallet from anywhere, and basic auth is annoying AF

The feature request is therefore requesting support for a location override so that I can host mutiny on e.g. https://mysite.net/31350127-c761-4db6-a591-336040660d64 effectively hiding in plain sight on a high-entropy path. I tried to do this but seems like the services running locally fetch a bunch of stuff from `/` and I couldn't rewrite easily.

**Comment by benthecarman** [comment]
I think the best way to do this would be an nginx config, not something explicit to mutiny.

if you just change this line https://github.com/MutinyWallet/mutiny-deploy/blob/master/nginx.conf#L9 to instead be `location /<your-random-path>` I think that'll handle it

**Comment by shyfire131** [comment]
OK I'll test that and report the results. 

Just got to figure out why I'm getting a 502 now on server reboot 😅

**Comment by shyfire131** [comment]
Nope that just results in a 404, I assume it has something to do with this https://github.com/MutinyWallet/mutiny-deploy/blob/a2d87171cddf8ae63d48f28651b8db86f3876bf1/docs/setup-docs.md?plain=1#L245

**Comment by benthecarman** [comment]
> I do agree this has nothing to do with mutiny, although it seems like a pretty common use case... perhaps this is a feature request that belongs on the mutiny-deploy repo?

Yeah, it is a good idea. I'll try and set it up on my server and write a guide on how to do it

**Comment by benthecarman** [comment]
Figured it out, docs are here: https://github.com/MutinyWallet/mutiny-deploy/blob/master/docs/hidden-site.md

let me know if you're able to get it to work

**Comment by shyfire131** [comment]
(got my threads crossed and replied on the wrong issue, crossposting the below)

A bit finicky, but seems to work for the most part. When I first load up https://mysite.net/my-hidden-path, I see the below:

![image](https://github.com/MutinyWallet/mutiny-web/assets/116033104/59cdbf28-3272-406a-ac50-5ba7c54d4aac)

Clicking on "Dangit" redirects to https://mysite.net/ and everything just works at that point.
