### ISSUE TITLE
Channel force closed

### ISSUE THREAD

**Issue by afds3j8** [MutinyWallet/mutiny-web#617]
"Channel closed because user manually force-closed the channel" but all I did was open the Android app to approve some zaps. 

I have had two channels close on me previously but they were closed due to reason "REASON
Channel closed because commitment or closing transaction was confirmed on chain."

v0.4.23 installed via Obtanium on GrapheneOS. 
Not using it on any other devices.

**Comment by afds3j8** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13113236/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
This one is typically due to pending payments that didn't complete before the timelock occurs. Zaps to zeuspay addresses has been causing this more frequently in the past week.

**Comment by TonyGiorgio** [comment]
Closing in favor of this issue tracking the underlying problem https://github.com/MutinyWallet/mutiny-node/issues/826
