### ISSUE TITLE
Error: Mutiny is already running.

### ISSUE THREAD

**Issue by avaaum** [MutinyWallet/mutiny-web#620]
this is the error i get when i enter my encrypted password (64 characters long) on pixel 6 pro running the latest grapheneos. i have closed all tabs and tried downloading the browser app, but still get the same message. i literally just set this wallet up. i tried to restore but it tells me my 12 words are not correct. they are correct and and in the correct order. looking forward to your assistance. thx 🤙🏻

**Comment by avaaum** [comment]
vanadium browser with javascript jit allowed

**Comment by TonyGiorgio** [comment]
Confirmed, working on getting a fix out shortly.

**Comment by avaaum** [comment]
awesome. thx for the lightning fast reply 🤙🏻

**Comment by TonyGiorgio** [comment]
Should be fixed now! Sorry about that. Let us know if it is not.
