### ISSUE TITLE
Channel closed, 0 balance

### ISSUE THREAD

**Issue by dipunm** [MutinyWallet/mutiny-web#623]
My unfortunate issue here is I have completely forgotten how much I had on this wallet. I'll accept if the channel close ate everything with on chain fees but I'd like some visibility into what happened.

![Screenshot_20231025-164220](https://github.com/MutinyWallet/mutiny-web/assets/5099980/6103ca83-3cce-4569-b728-953be4e3a4f7)

The channel id is babe93411048c8828c51bfd0c4e3b37c142715fbf6335c335811fcc26a3c5b7e

![Screenshot_20231025-164454](https://github.com/MutinyWallet/mutiny-web/assets/5099980/fc7cf5e4-b25e-4040-a71f-58430c305dd9)

How can I find the channel close tx id?

**Comment by benthecarman** [comment]
If you can provide your logs we can get that for you, it is Settings > Emergency kit. You should be able to just drag and drop the whole log file here

**Comment by dipunm** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13182829/mutiny-logs.txt)

**Comment by benthecarman** [comment]
This was the force close transaction https://mempool.space/tx/66f3c1735d936344afde43c42a76e53391e9f4cbaf4fbf333d59ee6c76fc5ba5

Looking at your logs it looks like the force close happened on 10/6 but you didn't open the wallet again until 10/23 so the funds have been swept by then. If you experience a force close you should try opening the wallet every day so you have the opportunity to sweep the funds back to yourself.

We can contact the LSP to try to get the funds back.

**Comment by dipunm** [comment]
Is that because it is below the dust limit? Or because the fees to sweep it back would supercede the amount?

It would be cool to clean up a little using CPFP or even a multi-input tx to ensure that we remove the now unspendable utxo from the utxo set.

**Comment by dipunm** [comment]
also, good to know I didn't have too much there :face_exhaling: :)

**Comment by benthecarman** [comment]
> Is that because it is below the dust limit? Or because the fees to sweep it back would supercede the amount?

I think the latter. 

> It would be cool to clean up a little using CPFP or even a multi-input tx to ensure that we remove the now unspendable utxo from the utxo set.

Next time the mempool clears if you open mutiny I am guessing it'll get swept. I'll look into if we can add any handling for small utxos (use a smaller fee rate)

**Comment by benthecarman** [comment]
Closing for now, let us know if you have any more issues or questions
