### ISSUE TITLE
Given Node Pubkey is Invalid

### ISSUE THREAD

**Issue by hurleyburt** [MutinyWallet/mutiny-web#628]
I've been having issues ever since I had my channels force close. Originally I was using Mutiny on my android, but when I attempted internal transfers to phoenix wallet, I had continued time outs. Someone ended up telling me that you will have issues sending 2 self custodial lightning node wallets to each other because they both have to be running. Now I know that, but since then I restored my wallet on my desktop browser (brave). Took a while for proper funds to show up. I just re-synced the on-chain wallet via the debug tools and that refreshed my on chain balance. But now when I try to swap to lightning I get this error: "The given node pubkey is invalid"
<img width="946" alt="Screenshot 2023-10-26 at 8 32 01 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/149074391/67699041-893b-449b-8594-793cd9063a89">

**Comment by hurleyburt** [comment]
Having a hard time sending funds out of lightning. Failed to find route.

**Comment by TonyGiorgio** [comment]
Can you share logs again and maybe the destinations you are trying? We can take a look.

**Comment by TonyGiorgio** [comment]
It looks like you tried emailing this in, could you go through the github website to attach the file? It looks like it is missing a lot of logs, I don't see any payments being attempted here.

**Comment by hurleyburt** [comment]
everything seems to be working now. restarted the router and refreshed the wallet. Thanks

**Comment by benthecarman** [comment]
Glad you got it
