### ISSUE TITLE
Channel forced closed cannot spend onchain balance

### ISSUE THREAD

**Issue by ajohnson651** [MutinyWallet/mutiny-web#642]
A channel was forced closed the funds show in my onchain wallet but if I go to spend them or swap to a lightning channel the app shows no funds available.  I have tried resetting and restoring but I still have the same problem.  On-chain tx shows over 12 confirmations.

![Screenshot_20231029_213332](https://github.com/MutinyWallet/mutiny-web/assets/97716531/87752e55-3efd-429b-92d1-0a08f43aeeea)
![Screenshot_20231029_213350](https://github.com/MutinyWallet/mutiny-web/assets/97716531/92047a5b-3985-4c29-adaa-f078812808fa)

**Comment by TonyGiorgio** [comment]
May take up to 3 days for the sweep transaction to funds to become available. There should be a 'sweep transaction' afterwards. Please check back over the next few days and let us know if it doesn't appear.

**Comment by ajohnson651** [comment]
Oh yes I forgot about the wait for a force close.  Thanks
