### ISSUE TITLE
Add ZMW ticker

### ISSUE THREAD

**Issue by 5atoshiNakamoto** [MutinyWallet/mutiny-web#643]
Please add support for Zambian Kwacha, ZMW. Thanks.

**Comment by benalleng** [comment]
Unfortunately, at this time the currencies we can add support for are limited by the coingecko API
https://api.coingecko.com/api/v3/simple/supported_vs_currencies

**Comment by TonyGiorgio** [comment]
Not sure anything we can do besides switching providers so not doing this for now.
