### ISSUE TITLE
Remove tag screen after amount input for receives

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#646]
This screen adds friction for not much gains. I think we should ask the user to tag it afterwards instead. Removes an entire page from the receive flow, which is going to be the very first things the user does. 

![Screenshot 2023-10-31 at 2 17 22 PM](https://github.com/MutinyWallet/mutiny-web/assets/101225832/5f4c51d6-7767-4e13-b1ae-824e329118f3)

**Comment by miawhite21** [comment]
Would you do the same for Send? Or you would allow to tag before and after sending?

**Comment by benthecarman** [comment]
I disagree with this. If you have to go back to tag a transaction, no user will do it. 

Tagging really brings out some of the social features we're doing and this would limit that

**Comment by TonyGiorgio** [comment]
> If you have to go back to tag a transaction, no user will do it.

They arent doing it anyways, and there is always hesitations for the first user coming to this screen and pausing for a few seconds and then proceeding anyways. If they don't want to tag it, they don't want to tag it. Let's move on from it.

**Comment by TonyGiorgio** [comment]
> Would you do the same for Send?

I think sending makes sense to still have it in some way, since they might have a contact they are sending to. In the receive side, it's mostly just "how much do you want to receive" being the main action and then anyone can pay. We could do things like payment requests from others but until then, I think the additional page adds friction.

**Comment by benthecarman** [comment]
This is done now
