### ISSUE TITLE
channel was closed after ~ 15 minutes 

### ISSUE THREAD

**Issue by rolikeusch** [MutinyWallet/mutiny-web#654]
and that is the  message i see in mutiny (web app on ios)
![IMG_3584](https://github.com/MutinyWallet/mutiny-web/assets/3592156/2de49bca-dbbe-4a42-b10c-59682699c8c8)

this is the activity log:
![IMG_3585](https://github.com/MutinyWallet/mutiny-web/assets/3592156/add10d7b-acda-4ac4-a874-3ea918afb695)

and the log:
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13231385/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
There seems to have been some race condition maybe. Just to double check, you didn't try using it on multiple devices or sessions yet, right? Or installed as a PWA and then copy pasted the seed words into another instance? Just trying to rule out multi device bugs, though you probably didn't do that.

**Comment by rolikeusch** [comment]
no i use it only on one device, my iphone.  it‘s installed as pwa but i have not copy any seeds over. i started fresh in pwa.

**Comment by TonyGiorgio** [comment]
Okay thank you. Do you know if you started queuing up zaps before the channel opened?

**Comment by rolikeusch** [comment]
no i started zapping after the channel was opened.

**Comment by TonyGiorgio** [comment]
Okay, this is helpful, thank you for the answers. We've brought this to the attention of the Lightning Dev Kit team members and we think something unknown might be happening here. This is not typical, we're going to troubleshoot it more. Sorry this happened right out of the gate for you.

**Comment by TonyGiorgio** [comment]
I just want to confirm, have the sats come back to you on chain? Force close channels may take a couple days but want to make sure that happened.
