### ISSUE TITLE
Wrong onchain balance after channel close

### ISSUE THREAD

**Issue by f321x** [MutinyWallet/mutiny-web#658]
I closed my only channel in Mutiny on Android in Vanadium Browser (GrapheneOS Android 14).
The pending balance in the top part (below lightning, 2nd row) is double as high (minus ~100 sats, both sats and fiat) than the pending amount in the activity part in the history (which shows the correct amount).

**Comment by TonyGiorgio** [comment]
If you can provide logs and transaction ids, that'll help.

**Comment by TonyGiorgio** [comment]
Got more info. I suspect a fee bump situation is going on and the balance is reflecting near double. Tx still hasn't been confirmed yet.

**Comment by benthecarman** [comment]
Thanks for the report! Fixed the issue, will be released probably sometime next week

https://github.com/MutinyWallet/mutiny-node/pull/825
