### ISSUE TITLE
Sats missing from mutiny balance

### ISSUE THREAD

**Issue by hellosa-sa** [MutinyWallet/mutiny-web#660]
I have been testing out Mutiny wallet for a few weeks and it seems that I may have lost funds due to a lightning channel close. I am hoping that someone can explain to me how to recover my sats.

I sent 430,000 sats over lightning from Strike to my Mutiny wallet on 10/16. I didn’t previously have any channels large enough to accept a transaction of this size, so I assume that a new channel must have been opened for this transaction to be reflected in my Mutiny wallet. For a while, I could see the balance in my Mutiny lightning wallet. However, recently it seems that all my channels closed and the lightning balance disappeared. The funds did not return to my strike wallet and are not showing in my Mutiny lightning or on-chain balance.

Any assistance with this matter is appreciated.

**Comment by hellosa-sa** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13255548/mutiny-logs.txt)

**Comment by hellosa-sa** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13255551/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Sometimes when channels close, it may take a couple days for it to reflect back on chain. When did they close and when you click on the channel close icon in your activity, does it give a reason?

**Comment by hellosa-sa** [comment]
> Sometimes when channels close, it may take a couple days for it to reflect back on chain. When did they close and when you click on the channel close icon in your activity, does it give a reason?

I had two channels close on 10/27 and one channel close on 10/31.

The 10/31 channel close has this reason:

Channel closed because the ChannelManager read from disk was stale compared to ChannelMonitor(s)


The two 10/27 channel closes have this reason:

Channel closed because of an exception: Peer attempted to reestablish channel with a very old local commitment transaction

**Comment by TonyGiorgio** [comment]
What's your node id? It should be in settings > admin, at the top.

**Comment by hellosa-sa** [comment]
> What's your node id? It should be in settings > admin, at the top.

02906138d7dd4f521518a30a7008723b29b1fe913ba931689fe5503f5a5cff6a85

**Comment by hellosa-sa** [comment]
How many days should I expect to wait before the funds return? I still see zero available. I provided my node ID above.

**Comment by benthecarman** [comment]
You'll probably get it sometime next week

**Comment by benthecarman** [comment]
Node Id: 02906138d7dd4f521518a30a7008723b29b1fe913ba931689fe5503f5a5cff6a85

force close transaction: https://mempool.space/tx/71c063bf75a4b004ca852416be4299721e7c2a007b498d48b63d3e02b7be8ad2

**Comment by benthecarman** [comment]
@hellosa-sa if you could please provide an onchain address to refund to

**Comment by hellosa-sa** [comment]
bc1qztpw59sp54l38l9phrkzrskj6mzzzqye5w4wc6

**Comment by TonyGiorgio** [comment]
Sent
