### ISSUE TITLE
on chain funds gone

### ISSUE THREAD

**Issue by tulla2020** [MutinyWallet/mutiny-web#663]
hey guys. i needed help a few days ago with force closing channels. ben helped me. the funds were back in my wallet, on chain. 
i logged in this morning and they are gone. i did not move them. i restored from 12 words. still gone. this is concerning. please advise. --

**Comment by TonyGiorgio** [comment]
Provide logs. The recovery tool might trigger the LSP to sweep the funds because of the situation you were in but we need more info.

**Comment by tulla2020** [comment]
this is what i have: 

c098 2023-11-05 11:06:38.991 DEBUG [mutiny_core::gossip:154] Previous gossip sync timestamp: 0
c098 2023-11-05 11:06:39.350 DEBUG [mutiny_core::gossip:175] retrieved remote scorer
c098 2023-11-05 11:06:39.686 INFO  [mutiny_core::node:200] initializing a new node: 4d2d8b2e-0e4c-4648-82e6-b6e951d6d82b
c098 2023-11-05 11:06:39.696 DEBUG [mutiny_core::ldkstorage:209] Reading channel manager from storage
c098 2023-11-05 11:06:39.697 INFO  [mutiny_core::node:322] creating lsp client
c098 2023-11-05 11:06:39.698 INFO  [mutiny_core::node:564] Node started: 032936341ecf46841cbd2bff8d2280a2fb90f913f167a2749f2703f8fa4510b30a
c098 2023-11-05 11:06:39.698 INFO  [mutiny_core::nodemanager:749] inserting updated nodes
c098 2023-11-05 11:06:39.698 INFO  [mutiny_core::nodemanager:756] inserted updated nodes
c098 2023-11-05 11:06:39.701 TRACE [mutiny_core::background:557] Calling ChannelManager's timer_tick_occurred on startup
c098 2023-11-05 11:06:39.701 TRACE [mutiny_core::background:557] Rebroadcasting monitor's pending claims on startup
c098 2023-11-05 11:06:39.702 INFO  [mutiny_core::nodemanager:1477] RGS URL: https://scorer.mutinywallet.com/v1/rgs/snapshot/0
c098 2023-11-05 11:06:43.220 TRACE [lightning_rapid_gossip_sync::processing:62] Processing RGS data...
c098 2023-11-05 11:06:43.518 DEBUG [lightning_rapid_gossip_sync::processing:148] Processing RGS update from 1699182000 with 8435 nodes, 53801 channel announcements and 107430 channel updates.
c098 2023-11-05 11:06:43.747 TRACE [lightning_rapid_gossip_sync::processing:257] Done processing RGS data from 1699182000
c098 2023-11-05 11:06:43.747 INFO  [mutiny_core::gossip:233] RGS sync result: 1699182000
c098 2023-11-05 11:06:43.747 INFO  [mutiny_core::nodemanager:949] RGS Synced!
c098 2023-11-05 11:06:43.747 TRACE [mutiny_core::background:557] Persisting network graph.
c098 2023-11-05 11:06:43.897 TRACE [mutiny_core::fees:125] Retrieved fees from mempool
c098 2023-11-05 11:06:43.897 INFO  [mutiny_core::nodemanager:958] Updated fee estimates!
c098 2023-11-05 11:06:43.897 INFO  [mutiny_core::esplora:221] Starting transaction sync.
c098 2023-11-05 11:06:44.192 TRACE [lightning::ln::channelmanager:8074] New best block: 0000000000000000000005674e8b6be06d49a4de2691660b1393feb9e6ece8d8 at height 815427
c098 2023-11-05 11:06:44.193 DEBUG [lightning::chain::chainmonitor:682] New best block 0000000000000000000005674e8b6be06d49a4de2691660b1393feb9e6ece8d8 at height 815427 provided via best_block_updated
c098 2023-11-05 11:06:44.193 TRACE [mutiny_core::background:557] Persisting ChannelManager...
c098 2023-11-05 11:06:44.194 TRACE [mutiny_core::background:557] Done persisting ChannelManager.
c098 2023-11-05 11:06:44.268 INFO  [mutiny_core::esplora:317] Finished transaction sync.
c098 2023-11-05 11:06:45.746 INFO  [mutiny_core::nodemanager:1519] We are synced!
c098 2023-11-05 11:06:45.893 DEBUG [mutiny_core::networking::proxy:69] connected to ws: wss://p.mutinywallet.com
c098 2023-11-05 11:06:45.894 DEBUG [mutiny_core::peermanager:433] connected to peer: PubkeyConnectionInfo { pubkey: PublicKey(f0e18eca0f86800041211951fbbbabdbb7743995059d12a4219b00b4fb43faaec9a0af987303533cdaa9a57b32494716c973a7a53696dd46367cb483a5fa46e6), connection_type: Tcp("52.88.33.119:9735"), original_connection_string: "03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0@52.88.33.119:9735" }
c098 2023-11-05 11:06:45.894 TRACE [mutiny_core::peermanager:436] sent 50 to node: 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:06:45.894 TRACE [mutiny_core::networking::socket:65] scheduling descriptor reader
c098 2023-11-05 11:06:45.894 TRACE [mutiny_core::node:1729] auto connected lsp: 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:06:45.895 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:06:45.993 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:45.995 DEBUG [lightning::ln::peer_handler:1374] Finished noise handshake for connection with 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:06:45.995 TRACE [lightning::ln::peer_handler:1240] Enqueueing message Init { features: [33, 81, 138, 8, 128, 160, 8], networks: Some([6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000]), remote_network_address: Some(TcpIpV4 { addr: [52, 88, 33, 119], port: 9735 }) } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:06:45.995 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:06:45.995 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:06:46.088 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:46.089 INFO  [lightning::ln::peer_handler:1539] Received peer Init message from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0: DataLossProtect: supported, InitialRoutingSync: not supported, UpfrontShutdownScript: supported, GossipQueries: supported, VariableLengthOnion: required, StaticRemoteKey: supported, PaymentSecret: required, BasicMPP: supported, Wumbo: supported, AnchorsNonzeroFeeHtlcTx: not supported, AnchorsZeroFeeHtlcTx: not supported, ShutdownAnySegwit: supported, Taproot: not supported, OnionMessages: not supported, ChannelType: supported, SCIDPrivacy: supported, ZeroConf: supported, unknown flags: supported
c098 2023-11-05 11:06:46.089 DEBUG [lightning::ln::channelmanager:8721] Generating channel_reestablish events for 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:06:46.168 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:46.168 DEBUG [lightning::ln::peer_handler:1472] Error handling message from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0; ignoring: Couldn't find channel for update
c098 2023-11-05 11:06:46.169 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:46.175 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:46.177 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:46.244 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:49.840 TRACE [mutiny_core::background:557] Calling PeerManager's timer_tick_occurred
c098 2023-11-05 11:06:49.841 TRACE [lightning::ln::peer_handler:1240] Enqueueing message Ping { ponglen: 0, byteslen: 64 } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:06:49.841 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:06:50.251 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:06:50.251 TRACE [lightning::ln::peer_handler:1586] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:00.025 TRACE [mutiny_core::background:557] Calling PeerManager's timer_tick_occurred
c098 2023-11-05 11:07:00.025 TRACE [lightning::ln::peer_handler:1240] Enqueueing message Ping { ponglen: 0, byteslen: 64 } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:00.025 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:07:00.491 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:00.491 TRACE [lightning::ln::peer_handler:1586] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:09.820 TRACE [mutiny_core::background:557] Rebroadcasting monitor's pending claims
c098 2023-11-05 11:07:10.134 TRACE [mutiny_core::background:557] Calling PeerManager's timer_tick_occurred
c098 2023-11-05 11:07:10.134 TRACE [lightning::ln::peer_handler:1240] Enqueueing message Ping { ponglen: 0, byteslen: 64 } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:10.135 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:07:10.629 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:10.629 TRACE [lightning::ln::peer_handler:1586] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:20.271 TRACE [mutiny_core::background:557] Calling PeerManager's timer_tick_occurred
c098 2023-11-05 11:07:20.271 TRACE [lightning::ln::peer_handler:1240] Enqueueing message Ping { ponglen: 0, byteslen: 64 } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:20.271 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:07:20.663 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:20.664 TRACE [lightning::ln::peer_handler:1586] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:30.428 TRACE [mutiny_core::background:557] Calling PeerManager's timer_tick_occurred
c098 2023-11-05 11:07:30.428 TRACE [lightning::ln::peer_handler:1240] Enqueueing message Ping { ponglen: 0, byteslen: 64 } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:30.429 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:07:30.902 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:30.902 TRACE [lightning::ln::peer_handler:1586] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:39.887 TRACE [mutiny_core::background:557] Calling ChannelManager's timer_tick_occurred
c098 2023-11-05 11:07:39.887 TRACE [mutiny_core::fees:174] Got fee rate from saved cache!
c098 2023-11-05 11:07:39.887 TRACE [mutiny_core::fees:174] Got fee rate from saved cache!
c098 2023-11-05 11:07:39.993 TRACE [mutiny_core::background:557] Rebroadcasting monitor's pending claims
c098 2023-11-05 11:07:40.619 TRACE [mutiny_core::background:557] Calling PeerManager's timer_tick_occurred
c098 2023-11-05 11:07:40.619 TRACE [lightning::ln::peer_handler:1240] Enqueueing message Ping { ponglen: 0, byteslen: 64 } to 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:40.619 TRACE [mutiny_core::networking::proxy:92] sent data down websocket
c098 2023-11-05 11:07:41.042 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:41.042 TRACE [lightning::ln::peer_handler:1586] Received message Pong(Pong { byteslen: 0 }) from 03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0
c098 2023-11-05 11:07:45.938 INFO  [mutiny_core::nodemanager:958] Updated fee estimates!
c098 2023-11-05 11:07:45.938 INFO  [mutiny_core::esplora:221] Starting transaction sync.
c098 2023-11-05 11:07:46.165 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:46.165 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:46.166 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:46.168 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:46.169 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:46.170 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:46.241 TRACE [mutiny_core::networking::socket:77] received binary data from websocket
c098 2023-11-05 11:07:46.903 TRACE [lightning::ln::channelmanager:8074] New best block: 00000000000000000001ef2ce720b14def921985c10b564fece4774e16de760c at height 815428
c098 2023-11-05 11:07:46.903 DEBUG [lightning::chain::chainmonitor:682] New best block 00000000000000000001ef2ce720b14def921985c10b564fece4774e16de760c at height 815428 provided via best_block_updated
c098 2023-11-05 11:07:46.904 TRACE [mutiny_core::background:557] Persisting ChannelManager...
c098 2023-11-05 11:07:46.904 TRACE [mutiny_core::background:557] Done persisting ChannelManager.
c098 2023-11-05 11:07:46.977 INFO  [mutiny_core::esplora:317] Finished transaction sync.
c098 2023-11-05 11:07:47.778 INFO  [mutiny_core::nodemanager:1519] We are synced!

**Comment by benthecarman** [comment]
Like I said on telegram, the funds were in a force closed state and needed to be swept to your wallet. They were likely swept by the LSP and we can try and talk to them to get it back. You restoring your wallet wiped the logs so it might be a bit difficult

**Comment by tulla2020** [comment]
[mutiny-logs(3).txt](https://github.com/MutinyWallet/mutiny-web/files/13302211/mutiny-logs.3.txt)
[mutiny-logs (1).txt](https://github.com/MutinyWallet/mutiny-web/files/13302212/mutiny-logs.1.txt)
[mutiny-logs(2).txt](https://github.com/MutinyWallet/mutiny-web/files/13302213/mutiny-logs.2.txt)
[mutiny-logs(4).txt](https://github.com/MutinyWallet/mutiny-web/files/13302214/mutiny-logs.4.txt)

**Comment by tulla2020** [comment]
here are the logs i was able to download. ben helped me sweep funds (force close?) channels. once he walked me through that process, i logged into my mutiny wallet and, sure enough, the funds were there, on-chain. i checked once more a day or two later, and the funds were gone.

**Comment by tulla2020** [comment]
here is a receive address for when this gets straightened out: bc1qv0xhc0yuesuagg9gfys54hz488ccuntptfxvff

thanks very much.

**Comment by tulla2020** [comment]
hello....looking for an update here? you guys walked me through a 'force close' of channels...and now i am missing BTC.

**Comment by benthecarman** [comment]
@tulla2020 the funds should be sent back sometime next week, please be patient.

**Comment by benthecarman** [comment]
Looks like you never had your original logs in #613 so this might be harder to recover.

can you at least provide your node id? It is at the top of the admin settings

**Comment by tulla2020** [comment]
node ID 
032936341ecf46841cbd2bff8d2280a2fb90f913f167a2749f2703f8fa4510b30a

**Comment by TonyGiorgio** [comment]
Sent
