### ISSUE TITLE
Failed to find route

### ISSUE THREAD

**Issue by sondreolav** [MutinyWallet/mutiny-web#679]
Worked fine until now, but now I just get an error message: "Failed to find route."

Deleted everything and restored with the seed phrase, but still the same error. If I try to create a lightning invoice it wants to create a new lightning channel even though I have one.

Any suggestions?

**Comment by benthecarman** [comment]
if you can post logs we can get more info on what is going wrong.

Sounds like you probably had issues connecting to the LSP

**Comment by sondreolav** [comment]
[mutiny-logs.txt](https://nostrhub.sondreolav.com/files/mutiny-logs.txt)

**Comment by benthecarman** [comment]
```
16:17:31.321 TRACE [lightning::routing::router:2460] Have now collected 0 msat 
(seeking 3000 msat) in paths. Last path loop did not find a new path. 0ada 
2023-11-09 16:17:31.321 TRACE [lightning::routing::router:2483] Ignored 84 
candidate hops due to insufficient value contribution, 0 due to path length limit, 
127 due to CLTV delta limit, 0 due to previous payment failure, 16462 due to 
htlc_minimum_msat limit, 448 to avoid overpaying, 4068 due to maximum total fee 
```

looks you are only trying to send 1 sat which is above a bunch of people's `htlc_minimum_msat` limit since the rise in fees.

The other reason the some of the routes failed is the expected fees being too high, we have an update going out soon that should help with that

**Comment by sondreolav** [comment]
Now sending works.  But it is still the case that if I try to create a lightning invoice, it thinks I want to generate a new lightning channel.  And increases the sum by 10k sats.

**Comment by sondreolav** [comment]
seems like everything is okay now 🤙

**Comment by TonyGiorgio** [comment]
We pushed up an update yesterday to address it. Thanks for the report.
