### ISSUE TITLE
Forced channel closure aftermath on chain showing 0

### ISSUE THREAD

**Issue by SoulReaver-SS** [MutinyWallet/mutiny-web#699]
It's similar to this:
https://github.com/MutinyWallet/mutiny-web/issues/668
I'm opening this because benthecarman asked.
my log:
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13326837/mutiny-logs.txt)

I had some minimal amount of sats that moved to on chin after trying to send to Zeus wallet force closed my channel or something some time ago. For a time it showed some on chain, now it shows nothing on chain.
Yes, I tried "resync wallet" from admin page.
Windows 10, chrome, I'm using it through https://app.mutinywallet.com/

**Comment by benthecarman** [comment]
![image](https://github.com/MutinyWallet/mutiny-web/assets/15256660/a1d77aa3-7c4b-4688-9499-dda2c9c35991)

You might be able to use this button, otherwise it's easier to just use it on desktop and you can drag and drop the file.

**Comment by SoulReaver-SS** [comment]
> ![image](https://user-images.githubusercontent.com/15256660/282536167-a1d77aa3-7c4b-4688-9499-dda2c9c35991.jpeg)
> 
> You might be able to use this button, otherwise it's easier to just use it on desktop and you can drag and drop the file.

Can you also write what file you're asking for?

**Comment by benthecarman** [comment]
your logs

**Comment by benthecarman** [comment]
oh sorry commented on wrong issue

**Comment by SoulReaver-SS** [comment]
> Did you only have one channel? This looks like the funding transaction and the channel was closed by your node due to HTLC timeout: https://mempool.space/address/bc1qqkpflpnvwyd03yuje8wye0ukyuepjnqnx6e5cl
> 
> How much is "minimal amount of sats"? Because from the looks of it, all but 607 sats went to one of the parties rightfully. If that's your minimal amount, that's far too low to actually be spent.

607 sounds about right. So what's the solution? What do you mean by "went to one of the parties rightfully"?
Is that like a channel closure reserve being refunded to Mutiny or something? I believe it happened after I tried moving some to Zeus wallet self custodial @zeuspay.com address they use it with that force closed my channel because it uses zaplocker or something?

**Comment by TonyGiorgio** [comment]
If you only had 607 sats, there's no way to redeem that on chain. There's not really anything actionable here.
