### ISSUE TITLE
Channel closed, sats not received

### ISSUE THREAD

**Issue by igreshev** [MutinyWallet/mutiny-web#703]
Hello, 

I had a force-closed channel  at 26.10, sats still not back in the wallet

`73b8b54c76d42d336b09632f8be9bb24555ffef737c89a44bfcc680b0964d431`

![IMG_1893](https://github.com/MutinyWallet/mutiny-web/assets/1061594/210ecc47-e4c7-468d-b9f6-059e89ac192a)

**Comment by benthecarman** [comment]
can you post your logs?

**Comment by afds3j8** [comment]
I have the same issue
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13345827/mutiny-logs.txt)

**Comment by afds3j8** [comment]
Channel ID 7831ccfb19c81526bee8ae9d316f7c4aaea4ec8ee6b55c77d091441fff2d1e80

"Channel closed because user manually force-closed the channel"

Channel closed Nov 10th

I have tried to resync on chain wallet to no avail. Logs attached in above comment.

**Comment by TonyGiorgio** [comment]
> Channel ID 7831ccfb19c81526bee8ae9d316f7c4aaea4ec8ee6b55c77d091441fff2d1e80
> 
> "Channel closed because user manually force-closed the channel"
> 
> Channel closed Nov 10th
> 
> I have tried to resync on chain wallet to no avail. Logs attached in above comment. 

Open up a separate issue.

**Comment by igreshev** [comment]
here, logs
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13715095/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Looks like the transaction was revoked. Have no idea why because your logs do not go back longer than a day or two. Can reach out to the LSP on your behalf. 
tx: https://mempool.space/address/bc1qgxncp2ka5e4uuwwj5la5jvhx8m5xufcvnx7tfy7n88tuqrh4av8qrt0zus

What is your node id? it should be in the admin settings.
