### ISSUE TITLE
Channel closed, sats not received 

### ISSUE THREAD

**Issue by afds3j8** [MutinyWallet/mutiny-web#704]
As reported here:
https://github.com/MutinyWallet/mutiny-web/issues/703

Channel ID 7831ccfb19c81526bee8ae9d316f7c4aaea4ec8ee6b55c77d091441fff2d1e80

"Channel closed because user manually force-closed the channel"

Channel closed Nov 10th

I have tried to resync on chain wallet to no avail. Logs attached in above comment.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13346064/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
No funds are missing, they're in the mempool waiting to confirm: https://mempool.space/tx/b5a0db9d562a20abf0629f939ba18415c5b294f225b70dcd4f2d85c613251a62

You can either wait or use a transaction accelerator.
