### ISSUE TITLE
Forced close hasn't swept funds for days

### ISSUE THREAD

**Issue by BBodemann** [MutinyWallet/mutiny-web#705]
Browser: PWA on iOS desktop (Safari).
Issue: Channel force closed after primal kept opening new tabs for NWC. It really messed things up pronto fast.

Log file:
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13353798/mutiny-logs.txt)

Node Id: 03a2bb5e1cdd0503c7f30dd85bc9f7238806564401074fff116554db202bd01274

Force close Tx: https://mempool.space/tx/9e8d8fd7074be2d560b01cab77f128c6590d7563427b40ed38b8065908205aad

**Comment by benthecarman** [comment]
> Channel force closed after primal kept opening new tabs for NWC. It really messed things up pronto fast.

Can you elaborate on this further?

**Comment by BBodemann** [comment]
When primal initiates the NWC flow to connect to mutiny, it opens new safari browser tabs each time. I mistakenly logged back into the new tab which led to me having mutliple tabs open. One of the tabs likely sent a zap which unsynced with my PWA Mutiny instance thus I ended up with a unsynced state and my channel was force closed by one of the instances.

**Comment by BBodemann** [comment]
My main concern is whether the sats are in the void or coming back some day.

**Comment by benthecarman** [comment]
> My main concern is whether the sats are in the void or coming back some day.

Looks like they have been swept by the LSP, if you provide an on-chain address we should be able to send it back

**Comment by benthecarman** [comment]
> When primal initiates the NWC flow to connect to mutiny, it opens new safari browser tabs each time. I mistakenly logged back into the new tab which led to me having mutliple tabs open. One of the tabs likely sent a zap which unsynced with my PWA Mutiny instance thus I ended up with a unsynced state and my channel was force closed by one of the instances.

Okay, this makes sense. Running multiple instances of mutiny often causes force closes. If you have the PWA installed you shouldn't run it in the browser as well.

**Comment by BBodemann** [comment]
bc1qghsanse5tzkfn8v4wsgs9wr7f74vd8yual2zu62krs53u3x6kdds9474gn

**Comment by BBodemann** [comment]
> > When primal initiates the NWC flow to connect to mutiny, it opens new safari browser tabs each time. I mistakenly logged back into the new tab which led to me having mutliple tabs open. One of the tabs likely sent a zap which unsynced with my PWA Mutiny instance thus I ended up with a unsynced state and my channel was force closed by one of the instances.
> 
> Okay, this makes sense. Running multiple instances of mutiny often causes force closes. If you have the PWA installed you shouldn't run it in the browser as well.

 What is best practice for using on iOS? I thought the PWA was a good idea but then Primal wouldn't open it through nwc, so I ended up having to use an Alby wallet

**Comment by TonyGiorgio** [comment]
They're removing support for it so probably don't link up with primal this way and use the wallet in multiple places.

**Comment by benthecarman** [comment]
PWA is the best practice, we'll be releasing the ios app soon that will be safer as well.

iOS doesn't support links to PWA so linking with primal isn't really doable. Normally the best flow is to create the NWC in mutiny and copy-paste it into the app you are linking.

**Comment by TonyGiorgio** [comment]
LSP sent the funds to your address.
