### ISSUE TITLE
Show additional on-chain reserve for user's that open channels

### ISSUE THREAD

**Issue by mikeyb233** [MutinyWallet/mutiny-web#718]
I am unable to pay any invoice and receive a "No route found" message when using PWA 0.4.34 using Android Brave version 1.59.124, Chromium 118.0.5993.117. I have tried resetting the router, restarting the app and phone with no change. I have attached my log file. 
[6bafa954-b002-41e9-aac9-c013b53926c6.txt](https://github.com/MutinyWallet/mutiny-web/files/13384423/6bafa954-b002-41e9-aac9-c013b53926c6.txt)

**Comment by TonyGiorgio** [comment]
What amounts are you sending out? And are these instant failures?

**Comment by mikeyb233** [comment]
21 sats, 100 sats, 1000 sats, 10000 sats all tested. And yes instant failure.

**Comment by TonyGiorgio** [comment]
There's some weird behavior happening right now due to htlc minimums/fees and mempool fees. 

Do you know if you were the one to open a channel through the on chain -> lightning swap functionality in Mutiny Wallet? Or if you would have done a lightning receive to have the channels opened? Trying to narrow down inconsistencies we're seeing.

**Comment by mikeyb233** [comment]
I think the most recent channel was opened via an on chain to lightning swap. I think the others were received.

**Comment by TonyGiorgio** [comment]
So it looks like with all of your channels, you were the channel opener. Channel openers have to pay the fee for the channel closing event to eventually occur. And with the rising fee costs, that becomes problematic for some of your channels, which are around 14k - 30k sats. There's no good immediate answer here besides that you technically do not have the funds to both pay for the invoices and the potential on chain fees that may rack up. We will investigate this further and see if there's ways we can make this more transparent the available funds that can be spent and the communication around fees. It's a bit vague to us, let alone the users.

**Comment by mikeyb233** [comment]
I see I see. Yeah there's no communication to the user about that because all I see in the Lightning channels area is an outbound of around ~48000 sats that it says I'm able to spend and a reserve of ~2700 sats

**Comment by TonyGiorgio** [comment]
Will try to show this better in the UI.

**Comment by TonyGiorgio** [comment]
We now show a much more accurate inbound/reserve/outbound display in the settings with a more accurate error code when this is ran into on sending.

**Comment by mikeyb233** [comment]
Thank you! Much improved having the channels broken out. The lightning balance on the home screen is still misleading or at least not intuitive as to what it represents (showing about 50k but can actually only send 6k) but now there's better explanation for why a payment may fail. Appreciate all your efforts!
