### ISSUE TITLE
Is it possible to deep link into the send workflow?

### ISSUE THREAD

**Issue by ckritzinger** [MutinyWallet/mutiny-web#723]
I'd like to be able to launch the Mutiny wallet with an invoice or address pre-populated, but I cannot find a way to achieve this.

Most wallets seem to support a url handler to handle `lightning:<invoice>` or `<app>:lightning:<invoice>`, allowing you to open the app with the invoice pre-populated.

I've tried to find a way to do this with the mutiny web app, but no luck. Tried various combinations of https://app.mutinywallet.com/send?invoice=xxx Also tried reading the code but could not see a way to do it (my react-fu is pathetic, so I might be missing it, if so, my humble apologies!)

Looking at the iOS and Android apps, I can see that you're taking the trouble to associate with app.mutinywallet.com, which is handy. It would be even better if one could augment that with a link to a workflow, and even better still to support the lightning: URL scheme as described in [Bolt11](https://github.com/lightning/bolts/blob/master/11-payment-encoding.md#encoding-overview)

**Comment by benthecarman** [comment]
Something we'd like to add but haven't gotten to yet!

**Comment by ckritzinger** [comment]
Would you be willing to consider an MR that only adds support for a lightning invoice as a send parameter? Or would you need a more comprehensive change (BTC/Lightning/other)?

I'm asking because all that I need is to be able to pre-populate a lightning invoice in order to provide a slick payment experience to our customers who use Mutiny.

**Comment by ckritzinger** [comment]
Would you be willing to consider an MR that only adds support for a lightning invoice as a send parameter? Or would you need a more comprehensive change (BTC/Lightning/other)?

I'm asking because all that I need is to be able to pre-populate a lightning invoice in order to provide a slick payment experience to our customers who use Mutiny.

**Comment by benthecarman** [comment]
Yes that'd definitely be accepted
