### ISSUE TITLE
Mutiny wallet able to recieve funds but not send

### ISSUE THREAD

**Issue by jmf393** [MutinyWallet/mutiny-web#734]
Hi,
I just setup a Mutiny wallet. I was able to receive funds twice. My activity
window shows two payments received. 

But I cannot send payments to any lightning wallet.  Tried to send to Strike, Phoenix,
Breez and lnd.  All fail with same problem: failed to find route.  

I may have accidentally set up two different channels.  First invoice was
delivered to Mutiny but took a long time.  The 2nd Mutiny invoice gave me the expected ~$15 setup
fee notice and seemed to go ok.  

Going by my best recollection of how all these the events occurred. 

I tried to send various amounts but all fail.  Also tried to recover wallet on another computer
and sends from that wallet.  But it fails in the same way.  The balance did show up ok on the 2nd box. 

Thanks for any help

Current balance is showing as:
lightning
505,075 SATS

I will upload my log.  

[mutiny-logs(1).txt](https://github.com/MutinyWallet/mutiny-web/files/13433395/mutiny-logs.1.txt)

**Comment by TonyGiorgio** [comment]
Thanks for the details. Unfortunately, the logs are only going back to one payment attempt, which failed somewhere in the network. It looked like at the beginning of the logs there was a lot of logs related to a possible connection issue. 

There's an option in the admin settings for "reset router", maybe try doing that, restarting the wallet, and trying a few payments again. If you have several failures and none are going through, we'd appreciate if you uploaded the logs again. Hopefully it either works now, or the logs show the payments and reasons.

**Comment by jmf393** [comment]
Hi Tony,
Thanks very much for the quick response!
I did try the reset router and wallet restart at one point but it did not seem to help. I can try again tomorrow.
I ran tests on two boxes and downloaded the logs twice on both boxes.  I will upload all the logs from both sets of tests. 

Hopefully this helps.

Box 1 logs
[mutiny-logs(1).txt](https://github.com/MutinyWallet/mutiny-web/files/13434201/mutiny-logs.1.txt)
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13434202/mutiny-logs.txt)

Box 2 logs
[mutiny-logs(1).txt](https://github.com/MutinyWallet/mutiny-web/files/13434215/mutiny-logs.1.txt)
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13434216/mutiny-logs.txt)

**Comment by jmf393** [comment]
Hi Tony,

Today I was able to successfully send a payment to a lnd node with a new
channel setup to voltage.  I set up a ch to voltage assuming that Mutiny would
be able to find the path easier.  Payment went through successfully today.  I
am not sure the new channel actually solved the problem or not.  My network
connection was wonky all day yesterday so that may have played a role in my
problem yesterday.

Thanks for your help

jmf393

**Comment by TonyGiorgio** [comment]
Good to know. Yeah, I think the connection issues could have played a part. If you opened a channel to voltage, I don't think it would have made it easier to pay your node due to the balance already being on your side.

But I do appreciate you bringing up that you had payment problems. If they continue, or get worse please let us know again. Thanks!
