### ISSUE TITLE
Unable to send outgoing payments

### ISSUE THREAD

**Issue by sachintr27** [MutinyWallet/mutiny-web#736]
I can receive incoming payments from other wallets but can't seem to send funds out of my Mutiny wallet. Error: Unable to find routes.

**Comment by benthecarman** [comment]
can you post your logs?

**Comment by sachintr27** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13464193/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Seems like you don't have enough balance to afford an HTLC right now with current on-chain fees. We outline this in our FAQ, hope that helps!

https://blog.mutinywallet.com/mutiny-wallet-faq/

Typically the way to fix this is to top up more or wait for fees to go down. 

We are working on solutions to better communicate this!

**Comment by sachintr27** [comment]
I'm not able to receive payments on Lightning to top up my wallet
![Screenshot_20231129-105124](https://github.com/MutinyWallet/mutiny-web/assets/14944732/6748e370-765d-44b7-9ec7-5876799c420b)

**Comment by sachintr27** [comment]
Hey, I've tried topping up my wallet but I keep getting the error that no routes are found even after that.

I just want to sweep my wallet but it seems like my funds are just stuck. What do I do?

**Comment by TonyGiorgio** [comment]
How much balance does it say you have available to spend in your channel view? 

Otherwise just close your channels if you want out.

**Comment by sachintr27** [comment]
I have enough outbound capacity.

There's no 'close channel' option anywhere. Where and how can I do that?

**Comment by TonyGiorgio** [comment]
It's there in the same screen as the channel info. Are you on the latest version?

**Comment by sachintr27** [comment]
Yeah I was using an older version. Updated the app and I can see it now.

But the fund balance I have in my wallet differs from the numbers in the channel information page. Half my funds are being shown as reserve.

**Comment by TonyGiorgio** [comment]
We do our best to explain some of that on that page and here https://blog.mutinywallet.com/mutiny-wallet-faq/

When you close, you'll get your "home page balance" minus on chain fees. It'll be somewhere between the two balances. The reserve you see now includes possible on chain fees that might occur if a force close happens while routing a payment.

**Comment by sachintr27** [comment]
It's a bit difficult to be onboard with how this whole thing works when I get to know about this after I deposited funds into the wallet. 

It's like I lost a portion of my funds the moment I deposited funds into the wallet. Will the amount of funds that's reserved get reduced as on-chain fees goes down? Or is it going to permanently be a part of the reserves?
