### ISSUE TITLE
Missing Funds

### ISSUE THREAD

**Issue by Bitcoinium** [MutinyWallet/mutiny-web#739]
I lost funds on my mutiny wallet and it is unclear where they went. I only had one transaction with this wallet, receiving funds which "enabled" the backup seed phrase button once the balance was non zero. For some reason, the funds disappeared and I could not figure out where they went. Please advise.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13465425/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Did you back up the seed phrase? Have you tried restoring from it?

**Comment by benthecarman** [comment]
It looks like the last time this current seed was used was September 9th

**Comment by Bitcoinium** [comment]
> Did you back up the seed phrase? Have you tried restoring from it?

Yes

**Comment by Bitcoinium** [comment]
> It looks like the last time this current seed was used was September 9th

Good to know, thanks.

**Comment by TonyGiorgio** [comment]
The funds you received, how long ago was that? And was it an on chain deposit or received via LN?

**Comment by Bitcoinium** [comment]
> The funds you received, how long ago was that? And was it an on chain deposit or received via LN?

I am not 100% sure but I checked my transaction history and it seems like I sent 0.0010 Bitcoin on August 8. I believe it was on chain actually. Does it show up in the log?

**Comment by TonyGiorgio** [comment]
No, your logs just show today. I'm guessing you had just done a restore?

You can try to click the resync chain option in the admin settings. Or if nothing shows up then try to restore your seed into a wallet like sparrow. There's some instructions here on the derivation path used: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery#on-chain

**Comment by Bitcoinium** [comment]
> No, your logs just show today. I'm guessing you had just done a restore?
> 
> You can try to click the resync chain option in the admin settings. Or if nothing shows up then try to restore your seed into a wallet like sparrow. There's some instructions here on the derivation path used: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery#on-chain

I tried to resync chain option and nothing happened. It looks like the button barely registers when I click on it, tbh. Not sure what's supposed to happen when you select that option but my funds still show 0. I imported my wallet into Blue Wallet and it is zero also. It said that it never had a transaction. Stange because I am pretty sure I got the funds and it confirmed. Definitely it was om chain. Good thing it was just 0.0010 BTC mistake, not 83 BTC ;)

**Comment by Bitcoinium** [comment]
> > No, your logs just show today. I'm guessing you had just done a restore?
> > You can try to click the resync chain option in the admin settings. Or if nothing shows up then try to restore your seed into a wallet like sparrow. There's some instructions here on the derivation path used: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery#on-chain
> 
> I tried to resync chain option and nothing happened. It looks like the button barely registers when I click on it, tbh. Not sure what's supposed to happen when you select that option but my funds still show 0. I imported my wallet into Blue Wallet and it is zero also. It said that it never had a transaction. Stange because I am pretty sure I got the funds and it confirmed. Definitely it was on chain. Good thing it was just 0.0010 BTC mistake, not 83 BTC ;)

**Comment by benthecarman** [comment]
Blue wallet doesn't support taproot, I'd recommend trying with sparrow.

**Comment by Bitcoinium** [comment]
> Blue wallet doesn't support taproot, I'd recommend trying with sparrow.

I did not know that, thanks. I'll get a sparrow wallet. So many wallets...hard to keep track sometimes.

**Comment by Bitcoinium** [comment]
> Blue wallet doesn't support taproot, I'd recommend trying with sparrow.

So....just learned that sparrow is a desktop wallet. My MAC is super old, OS v10. I will give it a try but usually desktop wallets don't install for me. Thanks for the info. I will let you know what happened.

**Comment by benthecarman** [comment]
Good luck!

**Comment by Bitcoinium** [comment]
> The funds you received, how long ago was that? And was it an on chain deposit or received via LN?

Tony, I found the exact transaction details. I was wrong, it was NOT on chain. It was a lightening invoice paid vua Strike, see attached. Does this help tracking down the funds? Is it a channel issue? Please advise.
![IMG_0601](https://github.com/MutinyWallet/mutiny-web/assets/152038074/b0969a57-2942-4150-b4d9-e9fd38178dda)

**Comment by TonyGiorgio** [comment]
Thanks for that. We'll send this info to the LSP on Monday and see if they can provide an update next week.

**Comment by Bitcoinium** [comment]
> Thanks for that. We'll send this info to the LSP on Monday and see if they can provide an update next week.

Thanks Tony.

**Comment by TonyGiorgio** [comment]
Forwarded the info, will provide an update when we hear back.

**Comment by Bitcoinium** [comment]
Random Github question. How do I change my profile picture? I changed it in settings but it changes only my public image but not my personal profile picture. Weird.

**Comment by benthecarman** [comment]
It is showing for me, github has been having issues today, could be that

**Comment by Bitcoinium** [comment]
Nevermind lol. Just need time to refresh I guess. My iPhone has been acting up and I am a bit on edge :)

**Comment by TonyGiorgio** [comment]
There's no record of any channels with your node and there's also no record of that invoice showing up on the LSP, which might have been expired out if it wasn't paid. Does Strike give you a payment hash for that payment? I didn't see one in the screenshot and that's the only way to prove payment. I also don't see a status for it.

**Comment by Bitcoinium** [comment]
Tony, I copied the Reference ID for the lightening transaction, see below:
be3e360c-05e5-498c-81cd-c63c17f1db0a

Is that the same thing as a payment hash? Weird, the message I got from Github via email says "payment hash" but your message here in the Github chat say "payment preimage." Nothing is making sense today.

**Comment by TonyGiorgio** [comment]
Sorry, yes I had to edit that. It's the preimage that proves the payment. That reference ID is their internal ID. Do your other lightning payments show it? I could have sworn that was something they expose to their users but maybe not... Might have to contact their support.

**Comment by TonyGiorgio** [comment]
Thank you. Sorry about this experience but let us know what they say and if they have the preimage.

**Comment by Bitcoinium** [comment]
Tony, here is the preimage. Let me know if you're able to track down my funds. Thanks.
![IMG_0690](https://github.com/MutinyWallet/mutiny-web/assets/152038074/1f9c5caa-0e1e-40dc-8be1-cfc550efc494)

**Comment by Bitcoinium** [comment]
> Thank you. Sorry about this experience but let us know what they say and if they have the preimage.

Hey Tony. I sent you the preimage. Any news?

**Comment by TonyGiorgio** [comment]
Can you paste it here? I am not trying to manually type that out to verify it.

**Comment by Bitcoinium** [comment]
> Can you paste it here? I am not trying to manually type that out to verify it.

Tony, of course. Here it is:

57cbaf16d1b3cdee00e8b370e9b02a838a4a37fb5bf7581249792786b2672028

Thanks,
Noha

**Comment by TonyGiorgio** [comment]
Thank you. This took awhile to investigate and track down. But essentially, the wallet that you currently have loaded up is not the same wallet that received that payment. The LSP did verify that the invoice was paid and that a channel was opened to a different pubkey. 

Have you tried restoring with your original seed words? Sometimes browser storage/cache gets cleared which is why it's important to back up the seed words. If you can double check, is your current browser seed words the same ones that you have backed up?

**Comment by Bitcoinium** [comment]
Tony, this is interesting. I do have my seed phrase but my wallet shows up empty. I suspect that my browser reloaded somehow before I got the seed phrase for the wallet that received sats, and I ended up grabbing the seed for a new wallet, thinking I have my wallet seed phrase. Does that make sense? In this case, I do not have access to that original wallet. Bummer :( Donation to the network then. Right??

**Comment by TonyGiorgio** [comment]
I was hoping that wasn't the case. Do you remember if you backed up your seed words WHILE you had a balance that was shown? Because if it was after it disappeared then this is due to browser policies after awhile. It's why we prompted after a balance was there but then switched to always prompting.
