### ISSUE TITLE
Channel close issue 

### ISSUE THREAD

**Issue by jpwandee** [MutinyWallet/mutiny-web#740]
I tranfer via LN to create channel for 1st time, it's wait over 20 hr and then i've this responded
![Screenshot_20231126_105146_Mutiny Wallet.png](https://github.com/MutinyWallet/mutiny-web/assets/21179142/8cec3dda-4c21-4e33-8c07-1d4f38a1e9ed)

Channel ID:
2842f5dea55629a5bbf9ebb2c0c379d859fdf54c7134da91a8bfcbfc4e154a66

**Comment by benthecarman** [comment]
Can you post your logs

**Comment by benthecarman** [comment]
It is possible the channel just failed to open and you ran into this, do you still have your onchain balance 

https://github.com/lightningdevkit/rust-lightning/issues/2096

**Comment by jpwandee** [comment]
Payment hash:
f501aaf05daac9cbe047e4f5e07a67ddf8353948177dc68de4ee7ecb1f2fd231

Invoice:
lnbc4670u1pjkr9e5sp5cz368emj9k0dzze9a552sty4qkrwjys7ewvedqq2hfd4trws6nxspp575q64uza4tyuhcz8un67q7n8mhur2w2gza7udr0yaelvk8e06gcsdqqnp4qwh05slmksqfkgdyz2wst9fewjmah2amldg3jg2pqzqgvr723mslqxqrrsxcqzzn9qyysgqk35nplft7z3qaw4qfru582lay5gpxn4p68t53zphc37cgm457qpqq5dv6l0j32d7wusvvhsyg3enj9hc0wsxklztgg4m2pm8ygfhp5gqshnf7l


I'm still don't get my sats back (to Phoenix wallet). I don't know where&how  to provide my 'log' to you

**Comment by jpwandee** [comment]
![Screenshot_20231126_154002_Phoenix.png](https://github.com/MutinyWallet/mutiny-web/assets/21179142/7b93e4ee-7e39-46d4-aecb-4dc0d6c880c2)

**Comment by benthecarman** [comment]
in settings if you go to emergency kit and can download your logs and drag and drop the file here

**Comment by jpwandee** [comment]
https://drive.google.com/file/d/1Ggp5pnPcmfDCLvqgbyC6NalRshBAwayP/view?usp=drivesdk

**Comment by benthecarman** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13466323/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Looks like the channel failed to open on receive when you sent from phoenix, in phoenixit says the payment is pending so it should fail back eventually

**Comment by jpwandee** [comment]
Should I get my money back?  Or will it disappear altogether?  

And will you advise me on how to successfully open the channel?

**Comment by benthecarman** [comment]
The sats should appear back in phoenix in the next couple days

> And will you advise me on how to successfully open the channel?

This is a really edge case bug, shouldn't be common. Once you initate the send to mutiny you should open mutiny and leave it open until you get the success screen

**Comment by benthecarman** [comment]
Closing for now, you can reopen if the money doesn't appear back in phoenix in the next couple days
