### ISSUE TITLE
Channel failed to open with mandatory 100.000 sats and only 90.072 sats remained onchain

### ISSUE THREAD

**Issue by ButtercupRobrts** [MutinyWallet/mutiny-web#742]
![Mutiny](https://github.com/MutinyWallet/mutiny-web/assets/102489320/011ab43d-ff9e-4995-904b-252beb0ce6fa)

Hello,
I downloaded the app a couple of days ago, transferred 100.000 sats onchain and used them to open a channel. It remained pending for a few days until a couple of days ago the pending channel was closed and i have less remaining sats as a result.

Any idea on what happened and how to fix it?
Thank you!

**Comment by benthecarman** [comment]
Can you post your logs

**Comment by ButtercupRobrts** [comment]
I'd love too but I'm not a very technical person. How do I extract the logs?

**Comment by TonyGiorgio** [comment]
In the settings, in the emergency toolkit, there's a download logs button.

**Comment by ButtercupRobrts** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13477798/mutiny-logs.txt)

Here they go,
Thank you!

**Comment by TonyGiorgio** [comment]
The error was `Unknown channel for WIRE_CHANNEL_REESTABLISH` and I think it's due to a bug that sometimes happens with Safari. Is that what you were using and did you install it as a PWA?

**Comment by ButtercupRobrts** [comment]
It's on IOS, it's safari default. Didn't install as PWA that i know off, it's directly from iphone browser

**Comment by ButtercupRobrts** [comment]
Is there anything i need to do on my part to solve this issue? Thank you!

**Comment by TonyGiorgio** [comment]
No, this happens sometimes and we've pushed a few updates to try to cut down on it happening. Maybe try again when you're able to? Otherwise if it happens again feel free to submit logs again and we can check how it happened.
