### ISSUE TITLE
force closes

### ISSUE THREAD

**Issue by bndw** [MutinyWallet/mutiny-web#752]
I've had 2 force closes in the last ~week. Kind of rough given the fees. Is there anything I can do on my side to avoid this?

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13532113/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Looks like the force closes are from HTLCs timing out. If you have pending payments and close the app it can cause this.

**Comment by bndw** [comment]
Hey Ben, thanks for the reply. Here's how I use the app:

From damus with NWC:
1. zap some notes
2. open Mutiny and wait for the zaps to show up and auto approve
3. close Mutiny

I generally try to open mutiny after zapping because I don't know how it actually works and assume I need to "wake it up".

Do I need to adjust the above workflow for better success?

**Comment by bndw** [comment]
Thanks for the help, will be more diligent on keeping the app open.
