### ISSUE TITLE
Mutiny Sats gone missing 

### ISSUE THREAD

**Issue by PaulGithubjoder** [MutinyWallet/mutiny-web#755]
I opened a Wallet, sent the Sats on the Bitcoin baselayer.  saw the fee was taken and that I had a balance and then the next time I logged in there was nothing there.
Before I erase everything and try to reset the account with my seed phrase... Can you help me?
Thank you!

**Comment by TonyGiorgio** [comment]
Please provide logs, it is in the admin section of the settings.

**Comment by benthecarman** [comment]
In the admin settings there is a resync wallet button. Try pressing that and reloading. It will look up a balance for all your addresses

**Comment by PaulGithubjoder** [comment]
blob:https://app.mutinywallet.com/12751abd-e4cc-4369-90cb-4ea0f8708dce

**Comment by TonyGiorgio** [comment]
Doesnt look like that worked. Need to attach the file and drag it into the comment box.

**Comment by PaulGithubjoder** [comment]
[mutiny-logs(1).txt](https://github.com/MutinyWallet/mutiny-web/files/13550557/mutiny-logs.1.txt)

**Comment by TonyGiorgio** [comment]
Not seeing anything indicating that a payment was received on chain. Are you sure on the sending side that it went through? Do you have the transaction ID and can you check mempool.space that it was actually confirmed?

**Comment by PaulGithubjoder** [comment]
Hello Tony,
   
  
    
   
  
   I will check now. Thanks
   
   
   
    El 04/12/2023 20:39 CET Tony Giorgio ***@***.***> escribió:
    
   
     
    
   
     
    
     
   Not seeing anything indicating that a payment was received on chain. Are you sure on the sending side that it went through? Do you have the transaction ID and can you check mempool.space that it was actually confirmed? 
   —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
   
  
    
   
   
   Paul ReyburnDirector ComercialAcademia de Idiomas Well and ***@***.***óvil 661 574 822  Oficina 943 317 999

**Comment by PaulGithubjoder** [comment]
Hello, 
    
   
       
    
   
     Above it says sent and finalized 
    
     
   Not seeing anything indicating that a payment was received on chain. Are you sure on the sending side that it went through? Do you have the transaction ID and can you check mempool.space that it was actually confirmed? 
   —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
   
  
      
   
   
   Paul ReyburnDirector ComercialAcademia de Idiomas Well and ***@***.***óvil 661 574 822  Oficina 943 317 999

**Comment by TonyGiorgio** [comment]
Not seeing anything. Do you have a transaction id?

**Comment by PaulGithubjoder** [comment]
Hello Tony, Ok, It says it was sent back..

**Comment by TonyGiorgio** [comment]
If it was on chain, whoever sent your transaction must not have paid a high enough fee and it never confirmed. Glad we found out the issue.

**Comment by PaulGithubjoder** [comment]
Shit!
Super diffficult to make it happen.
Sorry for the hassle.
But this was going to be my first lightening wallet!
