### ISSUE TITLE
Sats from Alby wound up as on chain.

### ISSUE THREAD

**Issue by crrdlx** [MutinyWallet/mutiny-web#757]
Hi, on 12/3 I sent 100k sats from Alby to set up a first channel, pretty sure I chose Lightning. However, it 70857 went through as on chain. As soon as I opened Mutiny, it reported I had just closed a channel. End result was 70k on chain, 0 in Lightning, and no channels open. Logs attached. I'd like to open a channel, but am hesitant to send another 100k to have the same result.
![screenshot-2023,12,04-16 15 50 344](https://github.com/MutinyWallet/mutiny-web/assets/40270030/f2d4a1e0-97de-47b3-b330-b7ed6f57f5a4)

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13551444/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
What browser/device are you using?

**Comment by TonyGiorgio** [comment]
You used the same seed on both? Do you have the logs for the other browser? I'm guessing these are the logs for the mobile samsung browser one?

**Comment by crrdlx** [comment]
Yes, same seed. No, the logs were from desktop (I thought they'd be the
same). Tried to download logs on mobile but no luck...recommended a link.
Maybe this works yntil tomorrow:
https://quickshare.samsungcloud.com/sk1wkb76mdyg

**Comment by benthecarman** [comment]
Yeah this looks like an issue from running Mutiny on multiple devices, we try to prevent you from doing this but there are some edge cases. If you run mutiny on multiple device it often causes force closes like this.

**Comment by crrdlx** [comment]
Hmm. Thanks for your help and responses. Any suggestions? I'm just trying
to open a channel. Should I try again and stay on one device? Any way to
convert those on chain sats to LN?

**Comment by benthecarman** [comment]
>  Should I try again and stay on one device?

Yes, you should only use Mutiny on a single device at a time.

> Any way to convert those on chain sats to LN?

Once the force close is swept to you, you should see a swap button next to your on-chain balance that you can use to open a channel.
