### ISSUE TITLE
Can't receive bitcoin over lightning.

### ISSUE THREAD

**Issue by sondreolav** [MutinyWallet/mutiny-web#759]
Can't receive bitcoin over lightning. The wallet thinks it needs to open a new channel even though I have plenty of inbound liquidity.

[mutiny-logs.txt](https://nostrhub.sondreolav.com/files/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Check your channels on the settings. Is your inbound enough for the invoice you're trying to create?

**Comment by sondreolav** [comment]
I have about 70k inbound liquidity, but no matter how small an invoice I make, it wants to create a new channel.

**Comment by TonyGiorgio** [comment]
How big does it show the reserve right now? What's the channel size in general? A screenshot would help.

**Comment by sondreolav** [comment]
[Screenshot](https://nostrhub.sondreolav.com/files/mutiny-screenshot.png)

[Screenrecording](https://nostrhub.sondreolav.com/files/mutiny-video.mp4)

**Comment by TonyGiorgio** [comment]
This is definitely strange. If you go to the admin tools in the settings, can you click on your channel and copy and paste the details that show up for it? Should have your channel id and a few other details there we can investigate.

**Comment by sondreolav** [comment]
Nodes:
0288bd740b8ff67ea8a9a76fe35e396fbf5f2bff098e9ae2a9226fd20556af9b5c

Peers:
`{
  "pubkey": "03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0",
  "connection_string": "03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0@52.88.33.119:9735",
  "alias": "Voltage Flow 2.0",
  "color": "ff5000",
  "label": null,
  "is_connected": true
}`

Channels:
`{
  "user_chan_id": "68442a18cf26c11d190a44b49adc60c9",
  "balance": 69798,
  "size": 141415,
  "reserve": 546,
  "inbound": 69656,
  "outpoint": "2e267fdafeaa0daaced0bd29d94f85a96c4859485d60dd142d4645b7883ddda3:0",
  "peer": "03aefa43fbb4009b21a4129d05953974b7dbabbbfb511921410080860fca8ee1f0",
  "confirmations_required": 0,
  "confirmations": 4520,
  "is_outbound": false,
  "is_usable": true
}`

**Comment by TonyGiorgio** [comment]
What do you mean refresh the channel? It'll take a couple seconds anyways for it to come online.

**Comment by sondreolav** [comment]
[screenshot](https://nostrhub.sondreolav.com/images/2023/12/07/screenshot.png)

**Comment by TonyGiorgio** [comment]
That just shows you your current status of the channel. The view. It doesn't actually do anything. The online/offline indication on the normal channel view (not the admin tools section) is a live indication. 

After you load the wallet, check that one. Wait for it to come online (may be a few seconds, let us know if it's very long) and then leave it opened for a little bit. If it switches between online and offline back and forth, let us know and submit logs. Otherwise, try to receive a small amount and if it gives you the same problem. 

Trying to pinpoint it.

**Comment by TonyGiorgio** [comment]
Actually the clue is here. 

 "balance": 69798, "size": 141415, "reserve": 546, "inbound": 69656

The normal channel view tries to reflect real inbound but from your screenshot, it showed about the same. I can tell you right now, there must be a bug in the inbound. You definitely don't have 69k inbound if the channel size is 141k and half of it is your balance. We need to fix this screen but yeah with on chain fees spiking, the lsp needs to be able to potentially close the channel.

**Comment by sondreolav** [comment]
I opened the channel during a fee spike, when there was still a static fee of 10k sats. And the onchan fee was 11 184 sats.

**Comment by TonyGiorgio** [comment]
In addition to on chain fees taking up the rest of the inbound, this can also happen if there's connection problems with the LSP. We just pushed up an update that might resolve that. Let us know if it's still an issue.
