### ISSUE TITLE
Stats and balance disappearance 

### ISSUE THREAD

**Issue by PinataPokey** [MutinyWallet/mutiny-web#760]
Hello! I was checking my wallet om Tuesday and realized that my stats and money balance have disappeared randomly. I had 195 stats and $75 dollars in Canadian. My significant other gave me the stats/balance on Sunday via Lighting.

**Comment by PinataPokey** [comment]
![Screenshot_20231203_162146_Chrome](https://github.com/MutinyWallet/mutiny-web/assets/153141636/71b873e9-0248-4a2a-ba28-436b46a7a4a9)
![Screenshot_20231203_162301_Chrome](https://github.com/MutinyWallet/mutiny-web/assets/153141636/e316defe-9ca6-4e8a-b142-f33b902bac78)
![Screenshot_20231206_171658_Chrome](https://github.com/MutinyWallet/mutiny-web/assets/153141636/d52dee2a-916d-4f90-99d5-017e7c61f2d5)

Here! Screenshots in order: 
Payment details 
Me receiving payment 
After Sunday, my stats disappeared.

**Comment by benthecarman** [comment]
Can you provide logs? It is in the Settings > Emergency Kit

Also have you tried restoring from seed?

**Comment by PinataPokey** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13593128/mutiny-logs.txt)

**Comment by benthecarman** [comment]
I don't see you ever creating an invoice in your logs. Are you sure this is the original wallet you used to receive? Have you tried restoring from your seed words?

**Comment by benthecarman** [comment]
Also I see you have hodl invoices enabled, that is not recommended

**Comment by PinataPokey** [comment]
> I don't see you ever creating an invoice in your logs. Are you sure this is the original wallet you used to receive? Have you tried restoring from your seed words?

Yes, it is the original wallet I used to receive but I haven't tried restoring.

**Comment by PinataPokey** [comment]
Ben, I restored my wallet as you mentioned and it worked.
