### ISSUE TITLE
Pending requests not clearing and channels bounce between on- and offline (on iOS)

### ISSUE THREAD

**Issue by rkuester** [MutinyWallet/mutiny-web#761]
On iOS TestFlight, I have a large number of pending requests (zaps from Damus TestFlight) which are not clearing despite approval. I have channels with much capacity, but they bounce between on- and offline in the UI. I've tried restarting, rebooting, etc. I'm not sure how to troubleshoot further.

[Log attached.](https://github.com/MutinyWallet/mutiny-web/files/13594551/mutiny-logs.3.txt)

**Comment by benthecarman** [comment]
How much is "much capacity"? Might be helpful to post a screen shot of your lightning channels page

**Comment by TonyGiorgio** [comment]
I see a lot of things related to network requests timing out and remote storage not saving in a timely matter. I see some payments being attempted though with some payment failures. 

Is your network connection okay? That's one thing that's definitely causing some issues.

**Comment by rkuester** [comment]
> How much is "much capacity"? Might be helpful to post a screen shot of your lightning channels page

![Screenshot 2023-12-06 at 22 41 31](https://github.com/MutinyWallet/mutiny-web/assets/536695/4cde1eb0-020c-4bb2-9dfd-8d488463d9a4)

**Comment by rkuester** [comment]
> Is your network connection okay? That's one thing that's definitely causing some issues.

Hmm, I'll go off WiFi and leave it on the cell network for a bit.

**Comment by TonyGiorgio** [comment]
Okay, try a restart again too when you do it.

**Comment by rkuester** [comment]
The channels still seem to be bouncing on and offline, now with the phone on the cell network. I'll leave it overnight, but here is a [fresh log](https://github.com/MutinyWallet/mutiny-web/files/13595318/mutiny-logs.5.txt) for now.

**Comment by rkuester** [comment]
> FWIW, also seeing this in the GUI and log now. Perhaps a secondary issue with recovering from this funky state?
>````
> 0d39 2023-12-07 16:53:24.590 ERROR [mutiny_core::nostr::nwc:336] failed to pay invoice: An invoice must not get payed > twice.
>````

I decided to hit *deny all* on the pending requests list (about 10 long) and things seem back to normal. I can zap via Damus presently. I thought everything was wedged because of the occasionally offline channels, but maybe that was not really an issue.

Interestingly, the pending requests were all payments to Damus—the percentage of each zap I've selected to send to Damus as support. Maybe something was up with them receiving recently (@jb55), and that kicked all this off? Maybe they were just the unlucky receiver when some wedging in Mutiny started, since I send them a lot of payments (one for every zap, it seems).

Closing for now and I'll keep an eye on it. Maybe there's something in Mutiny to improve about the reporting or recovery of stuck payments like this. It showed them as needing approval, which was kind of unexpected. Thanks guys!

**Comment by TonyGiorgio** [comment]
Ah, yeah if that was part of the "pending keeps saying failed to route" problem, there is some occasional behavior where those get kicked back to "Pending Requests" and then might get an "invoice can't be paid twice" problem. We currently aren't probing his node, we can look for it and try to get a network view of it for better success. 

There was definitely some weird race condition at some point with your device though, related to network connectivity at least once. If it does happen again though, please reopen and provide logs again and we can take a look to see what common occurrences happened. 

Thank you for the report and investigation!
