### ISSUE TITLE
Unable to Recieve initial lightning payment

### ISSUE THREAD

**Issue by BitcoinBastiat** [MutinyWallet/mutiny-web#762]
Trying to send btc over lightning to my new mutiny wallet and the payment either fails (when sent from WoS) or is still Pending after 24 hours (when sent from Phoenix). Tried sending anywhere from 100,000-120,000 sats multiple times.

**Comment by benthecarman** [comment]
Make sure you have mutiny open after you initiate the payment. If you don't have the wallet open then it is not able to receive

**Comment by TonyGiorgio** [comment]
If this problem persists, please submit logs so we can investigate.
