### ISSUE TITLE
Balance Zero: Channel Force-Closed

### ISSUE THREAD

**Issue by mushintrader** [MutinyWallet/mutiny-web#768]
Hi, I just checked my wallet balance and it says that it zero and that my channel was closed 2 days ago. Reason is given as "Channel Closed because user manually force-closed the channel". I would not have done this, I had no reason to.

It says that "funds may take a few days to be swept back into the wallet". Is there anything I should do? Did I do something wrong? Thank you for your help.

Screen shots log attached.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13655395/mutiny-logs.txt)
![Screenshot_20231213-101228](https://github.com/MutinyWallet/mutiny-web/assets/153698389/6f4c6ca4-7942-44bd-89e1-be341ca19fab)
![Screenshot_20231213-101219](https://github.com/MutinyWallet/mutiny-web/assets/153698389/036fe4b2-9fcc-4bb0-b9a5-5da522292ba0)

**Comment by benthecarman** [comment]
Normally this indicates that you had a stuck HTLC, were you paying any hodl invoices or zeus lightning addresses?

**Comment by benthecarman** [comment]
This was the closing transaction: https://mempool.space/tx/760f184f48a45ee13b5cbffc1e30667517f07c4ae98c89bd82ecdce442fd8c06

**Comment by TonyGiorgio** [comment]
I see the following: 
1. Payment attempt
2. Spotty internet, causing peer communication issues
3. Closing app before payment or internet/communication resolves itself
4. Multiple days gone by while payment was left in pending
5. Some weird LDK errors I have not seen before
6. Failure to broadcast specific transaction
7. Revoked funds 

What version of the wallet were you on (located at the bottom of settings) and how were you running the app? Web browser (which one?) or native android app? Were you running on multiple devices or browsers at the same time?
