### ISSUE TITLE
Gap limit too low and not finding the balance

### ISSUE THREAD

**Issue by GoldenrodScript** [MutinyWallet/mutiny-web#769]
My on chain wallet balance went to zero which is strange. I went to admin page to resync the on chain wallet but still nothing. The on chain transaction I received a few weeks ago (11/24) is now gone from my activity as well, and an on chain transaction that confirmed this morning in the mempool doesn’t show in my balance either.

Did a restore from seed 
Lighting balance looks good but onchain is still 0 sats, it should be about 107,008 sats. 

Logs attached below. 

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13677007/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
If you try to import the seed into a wallet like Sparrow, does that show those on chain transactions and balances? Here is the restore process: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery#on-chain

**Comment by GoldenrodScript** [comment]
Imported the seed into sparrow, node scanned wallet history but didn’t find an on chain balance. 

I made sure to follow the restore process with taproot, derivation path m/86'/0'/0’ and scanned from October 2023

<img width="1305" alt="Screenshot 2023-12-14 at 2 26 32 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/153857781/f668ded9-34a8-4861-8f76-d188ef348f2b">

**Comment by GoldenrodScript** [comment]
If it helps, I’m on wallet version Version: 0.4.39 and I’ve only used it on my phone.

**Comment by TonyGiorgio** [comment]
The logs in your screenshot show that it's still scanning, has that completed? 

If you go to the address list in sparrow, does it show the same address you have sent to? If you create a new address in mutiny, does it match one of those in the sparrow address list? 

Are you sure you've had both balances there in your wallet at once? And that you didn't send via LN instead of on chain?

**Comment by GoldenrodScript** [comment]
Yea the screening completed. Sorry I didn’t scroll lower to show that it was finished. 

It doesn’t show the address that I sent it to on sparrow which is odd, scrolled through as many of the addresses as I could see, 

Yea, when I create a new receive address in Mutiny, the address matches with Sparrow.

Yea, I had both balances at different times. One on chain came for 82,008 sats on November 24th https://mempool.space/address/bc1pumvg6n2plhswr3tdk4c52my568xdvdr8lptxtlhuyqt9xrw8k8lq23xefc

The other one was sent from strike with no fee cost, but a 24 hour wait and that arrived this morning at the address for 25,000 sats https://mempool.space/address/bc1pj9xekdqnt4y27ezk82huuty02ats66f65sxeunn5gnvh8ay5lalsjhe3hf

Definitely sent both via on chain.

**Comment by TonyGiorgio** [comment]
> Yea, I had both balances at different times. 

Both balances at different times or both at the same time? The reason for this questioning is whether or not the same seed you're using for your current wallet (which has the lightning funds) is the same that you've sent the funds to originally. When did you back up the seed words? It's very possible the browser has wiped it's storage (if you're using the browser) or if you're using the PWA version vs the Safari version which has different storage. 

What device are you using and what browser and is it installed as a PWA or through the normal browser window? Have you ever used anything different?

**Comment by GoldenrodScript** [comment]
I backed up the seed words the second I opened the wallet, didn’t want any issues :)

I’ve had my lightning balance and the 82,008 on chain balance at the same time for the last few weeks. I only noticed an issue when I woke up this morning, saw the funds confirm in the mempool from strike and checked my mutiny like I do everyday, only to see the onchain balance didn’t update. 

When I did the transaction from strike, I scanned the mutiny QR code.

It’s definitely the same wallet that I sent the lightning funds as I’ve only ever used one seed for Mutiny. I’ve been using the PWA version, I believe on Duckduckgo as that’s my default browser on the iPhone but it could have also been Safari. I’d be lying if I said I was 100% sure.

**Comment by TonyGiorgio** [comment]
Could you double check the non-pwa version of mutiny on both DDG and safari? Just load them up as a new browser tab for both?

**Comment by GoldenrodScript** [comment]
Loaded up both non-pwa versions in Safari and DDG, both show the lightning balance, but 0 sats on chage. So strange. When I go to receive on chain to generate an address, it still matches with sparrow.

**Comment by TonyGiorgio** [comment]
I just don't see how it would be possible that with the same wallet, it generated addresses that did not belong to the wallet from the point of view of Mutiny & Sparrow. But yet at the same time, it showed up in your same mutiny wallet like they were there up until today.

**Comment by GoldenrodScript** [comment]
This was my wallet balance as of a couple of days ago before everything happened. Didn’t do anything special other than attempt to get the 25,000 sats that confirmed but just didn’t update the on chain balance. 

![IMG_7033](https://github.com/MutinyWallet/mutiny-web/assets/153857781/945806eb-6103-4538-96bc-21dbbed043bd)

**Comment by TonyGiorgio** [comment]
I don't know what else to troubleshoot. If you've confirmed that your mutiny wallet is generating the same addresses as your sparrow wallet, yet the addresses you sent to don't show up in Mutiny and don't show up in Sparrow, then the funds aren't accessible by your seed/wallet. Nothing showing up in the logs either. I'll see if I can think of anything else over the next few days.

**Comment by GoldenrodScript** [comment]
Appreciate it. Will have a think as well to see what I’m missing.

**Comment by GoldenrodScript** [comment]
One last thought as I’m sure you guys are plugging away but in the screen shot that I sent over (below), since the lightning funds in the picture are associated with the 82,008 sats that are on chain, in theory whenever I would restore the wallet both those balances would appear together.

![IMG_7033](https://github.com/MutinyWallet/mutiny-web/assets/153857781/03cad9d2-4d98-4fce-a112-3cce6470974c)


The only things that I did before the on chain balance just went bye bye was start and stop the nodes which probably was pointless and resync the onchain wallet. I cleared my browser cache from Safari and DDG afterwards, but that shouldn’t affect seed restoration right?

If the seed I used was the wrong seed, I figure it wouldn’t show any funds on lightning as well. But let me know what you guys think. It’s not like it’s a lot of sats but I haven’t lost sats before so now my confidence is a bit shot!

**Comment by TonyGiorgio** [comment]
Yeah none of those things should be an issue. Your assumptions are correct, but thanks for providing more info. 

I don't think this is it, but could you crack up the gap limit on sparrow? Not sure what the default is and not at the computer at the moment to check how.

**Comment by GoldenrodScript** [comment]
Default is 20, put it to 40, still scanning.

Will keep you posted.

**Comment by TonyGiorgio** [comment]
Have you received a lot over LN? If you can, maybe even try 100.

**Comment by GoldenrodScript** [comment]
I would say more than 10, less than 20 in terms of LN received. I’ve mostly sent out on LN with Nostr Wallet Auth / Connect

I’ll pump it up to 100, it hasn’t gotten far in terms of scanning which is surprising.

**Comment by GoldenrodScript** [comment]
I’ll be damned, I pumped the gap limit to 150 and both transactions appeared!

Would the funds now appear on my mutiny wallet you think?

<img width="1284" alt="Screenshot 2023-12-14 at 8 14 53 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/153857781/68339ddc-7e7c-43a4-860c-d887e1fbcd03">

**Comment by TonyGiorgio** [comment]
Great to hear. I'm surprised it was so high. We need to make changes on our side to support this but no ATM Mutiny would still be unaware it exists. We should probably make the rescan button go much higher and we should also cycle back in unused addresses. A missight on our part, sorry it took awhile to think of it.

**Comment by GoldenrodScript** [comment]
No worries at all. Big fan of you guys and what you’re doing at Mutiny. Also a Paul Miller fan since before the verge days and happy to see he’s a bitcoiner!

And copy that, since Mutiny would be unaware this balance exists, I’m guessing one of my options is to send from Sparrow and open up receive on mutiny on my phone to get it back there?

**Comment by TonyGiorgio** [comment]
Thanks!

That is definitely an option, didn't want to recommend it as the first one though since a good chunk of it will go away to chain fees. I'll see if we can get a quick fix in for the next release. I'll change the title of this issue and use it for tracking it for a code change.

**Comment by GoldenrodScript** [comment]
Ok cool. I’ll sit my ass down and leave the sats be for awhile then haha. Excellent point. 

Thanks again, really appreciate it.

keep stacking 🫡

**Comment by benthecarman** [comment]
Latest release increased the gap limit

**Comment by GoldenrodScript** [comment]
Amazing as usual 🙌🏾

On December 30, 2023, Tony Giorgio ***@***.***> wrote:
> Latest release increased the gap limit
>

—
Reply to this email directly, view it on GitHub
<https://github.com/MutinyWallet/mutiny-web/issues/769#issuecomment-
1872589448>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/BEV255M2NCF5RWZE5ETSUOTYMBTZ5AVCNFSM6AAAAABAVJRQ6OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZSGU4DSNBUHA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by TonyGiorgio** [comment]
You may need to manually hit the resync chain button again, but it should go up to 150 addresses. Let us know if it doesn't work.

**Comment by GoldenrodScript** [comment]
Checked and it's all looking good.  So READY for Fedimint! Sending you
guys good vibes for 2024 and beyond 🫡

On December 30, 2023, Tony Giorgio ***@***.***> wrote:
> You may need to manually hit the resync chain button again, but it
> should go up to 150 addresses. Let us know if it doesn't work.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/MutinyWallet/mutiny-web/issues/769#issuecomment-
1872611114>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/BEV255NI7JNDWARW24RWPWDYMCCFTAVCNFSM6AAAAABAVJRQ6OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZSGYYTCMJRGQ>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by TonyGiorgio** [comment]
> Checked and it's all looking good.  So READY for Fedimint! Sending you guys good vibes for 2024 and beyond 🫡
> On December 30, 2023, Tony Giorgio ***@***.***> wrote: You may need to manually hit the resync chain button again, but it should go up to 150 addresses. Let us know if it doesn't work.
> — Reply to this email directly, view it on GitHub <[#769 (comment)](https://github.com/MutinyWallet/mutiny-web/issues/769#issuecomment)- 1872611114>, or unsubscribe <https://github.com/notifications/unsubscribe- auth/BEV255NI7JNDWARW24RWPWDYMCCFTAVCNFSM6AAAAABAVJRQ6OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZSGYYTCMJRGQ>. You are receiving this because you authored the thread.Message ID: ***@***.***>

Thank you for the patience and support! Happy new year.
