### ISSUE TITLE
Lightning setup fees despite inbound capacity

### ISSUE THREAD

**Issue by GyroJack** [MutinyWallet/mutiny-web#770]
Hi, I just recently noticed when I try to make any transaction I'm being warned about a lightning setup fee even though I have two good channels with plenty of inbound. 
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13680503/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
How much is "plenty of inbound"? Can you share the channels screenshot?

**Comment by GyroJack** [comment]
![image](https://github.com/MutinyWallet/mutiny-web/assets/96702919/efb8db1e-b08a-444f-8323-14b12439d3ce)

**Comment by TonyGiorgio** [comment]
Okay I see, thank you. Yeah something must be going on. I'll be able to take a look at the logs more tomorrow.

**Comment by GyroJack** [comment]
Thank you so much!

**Comment by TonyGiorgio** [comment]
I see a lot of disconnect peer messages in your logs. Have you tried restarting mutiny?

**Comment by GyroJack** [comment]
I restart it all the time. I usually close the PWA once I'm done using it.

**Comment by TonyGiorgio** [comment]
Could you restart it again, generate another invoice for like 1k sats, and if it happens again could you resubmit logs?

**Comment by GyroJack** [comment]
Just logged back in today and my channels are closed 😭
![image](https://github.com/MutinyWallet/mutiny-web/assets/96702919/ae2442b1-10fd-485e-841e-0e6798d2a99b)
[mutiny-logs (2).txt](https://github.com/MutinyWallet/mutiny-web/files/13688923/mutiny-logs.2.txt)

**Comment by GyroJack** [comment]
![image](https://github.com/MutinyWallet/mutiny-web/assets/96702919/2266571b-0f2a-4313-9631-befeaa620fb5)

**Comment by TonyGiorgio** [comment]
Are you using this on multiple devices at the same time?

**Comment by GyroJack** [comment]
No, only iOS.

**Comment by TonyGiorgio** [comment]
Something is definitely broken because it's acting like it's running multiple times. We'll have to circle back to this after the next few days because your funds are probably going to be swept by the LSP.

**Comment by GyroJack** [comment]
That stinks, alright.

**Comment by GyroJack** [comment]
Hey, funds have been swept. Yesterday I had to delete the bookmark and restore because when trying to login the PWA would not let me input my password. That has never happened before. Attached new logs in case they are valuable. I imagine they don't persist through new browser instances. 
[mutiny-logs (3).txt](https://github.com/MutinyWallet/mutiny-web/files/13694781/mutiny-logs.3.txt)

**Comment by benthecarman** [comment]
What do you mean by it wouldn't let you input your password? The text box wouldn't work or it was giving you an error after the password

**Comment by GyroJack** [comment]
The textbox wouldn't work. Keyboard never showed up. Tried multiple restarts. Also restarted phone.

**Comment by GyroJack** [comment]
I have an iPhone 8 which no longer receives the newest iOS versions. I'm stuck on 16 with security updates. That probably doesn't play a role since this is browser based but just wanted to share it in case.

**Comment by hex17or** [comment]
I am having this problem as well. Any idea why this is so?

`Amount I want to receive with notice of channel creation fee:`
![2023-12-28 14 21 26](https://github.com/MutinyWallet/mutiny-web/assets/48261276/2d8bd9a0-449c-4a54-a53e-7e3e915ea77a)

`Inbound capacity:`
![2023-12-28 14 21 34](https://github.com/MutinyWallet/mutiny-web/assets/48261276/c9632a1c-5a0f-4d3d-97b0-aedb75e95379)

**Comment by TonyGiorgio** [comment]
Sometimes this can cause issues if there's connections problems with the LSP. We pushed up an update to improve that. Let me know if it's not fixed.
