### ISSUE TITLE
Question: Will the amount of funds allocated as my channel's reserve balance vary according to prevailing on-chain fee rates?

### ISSUE THREAD

**Issue by sachintr27** [MutinyWallet/mutiny-web#772]
For eg, let's say I have 30k sats as reserve right now because of prevailing on-chain fee rates right now. 

But if fee rates go back down to 10 sat/vbyte, will the reserve balance be reduced to reflect that? 

Will the reserve funds then be freed up for me to use for regular spending transactions?

**Comment by benthecarman** [comment]
Yes, the reserve is dynamic based on current on chain fees
