### ISSUE TITLE
Transaction confirmed, but mutiny still empty

### ISSUE THREAD

**Issue by karpiCz** [MutinyWallet/mutiny-web#773]
Hello, I have sent bitcoins to required addres, but fee was set too small.
https://mempool.space/cs/tx/0c748b5489bb8aac3805d6d209099606c58300b580000e14dc17f3af97303c86

I increased fees (even two times) and transaction finally was confirmed and bitcoins landed on your wallet.
https://mempool.space/tx/76a208557e8e560596a819a77b0b766e8699ce5bd67e8866345c48cc0fbe87ce

But mutiny is still empty and 200000 sats still "pending"

I have also sent feedback by web form, but no response either...

**Comment by benthecarman** [comment]
> I have also sent feedback by web form, but no response either...

the feedback form is not for support

**Comment by benthecarman** [comment]
In the admin settings there is a resync wallet button, have you tried hitting that? You can also import your seed into sparrow wallet to make sure it arrived.

**Comment by karpiCz** [comment]
Settings - Admin Page - Resync wallet -- solved.
Thx
