### ISSUE TITLE
channel management?

### ISSUE THREAD

**Issue by hurleyburt** [MutinyWallet/mutiny-web#774]
I'm having a new issue where invoices go pending but end up unpaid. Having a look at my active channels shows I've got a bunch, with some having low amounts. 5/6 are low or empty send capacity. Is it recommended to do your own channel management and close smaller channels? Wondering if the small channels are the reason for the payments going unpaid. Strange how it's not coming up as no route or timeout. I also notice my un-spendable reserve balance is quite high compared to my total outbound liquidity.

**Comment by hurleyburt** [comment]
I can't send anything out of my mutiny wallet. Tried sending even small amounts to several different wallets and payment services

**Comment by benthecarman** [comment]
If you could provide logs and a screen shot of your lightning channel screen we could better debug.

It sounds like you are just running into channel reserve issues which happens when you have small channels and on-chain fees are high

**Comment by hurleyburt** [comment]
<img width="748" alt="Screenshot 2023-12-20 at 10 12 37 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/149074391/af101772-e05d-4eb1-b1cd-605085b4121f">
[mutiny-logs (1).txt](https://github.com/MutinyWallet/mutiny-web/files/13734690/mutiny-logs.1.txt)

**Comment by hurleyburt** [comment]
Seems to be working now. Did you do something on the back end?

**Comment by benthecarman** [comment]
On chain fees may have just gone down
