### ISSUE TITLE
On-chain and lightning balances being shown as 0

### ISSUE THREAD

**Issue by hex17or** [MutinyWallet/mutiny-web#776]
So I have Mutiny installed as a PWA on my Android phone. I had both an on-chain and a lightning balance with a handful of transactions. I didn't use the app for a few months and when I open the app now, I do not see either of my balances nor do I see any of my past transactions. Any reason why this is so? I have not cleared the cache or storage of the app - just that I did not open the app for some time. Any help appreciated.

Edit: Attaching logs 
[mutiny-logs (1).txt](https://github.com/MutinyWallet/mutiny-web/files/13742466/mutiny-logs.1.txt)

**Comment by TonyGiorgio** [comment]
Your browser may do that automatically. Restore from your seed words to recover things.

**Comment by hex17or** [comment]
Is it normal that this happens if I don't use the app for one day? I restored from seed successfully and was able to see my on chain and lightning balance. However after not using the app for just one day, I no longer see any balance or transactions? Do I have to restore from seed every time I need to use the app?

**Comment by benthecarman** [comment]
You shouldnt need to always restore. Your privacy settings in your browser might be wiping your state. It is recommended to use the native app or install as a PWA to prevent this.

**Comment by hex17or** [comment]
Thanks, I did not know that there was a native app. I have migrated my PWA to the native app now and will let you know if I face any other issues.
