### ISSUE TITLE
NWA "failed to load profile"

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#777]
the nwa string I have for automated testing is resulting in a "failed to load profile error": https://signet-app.mutinywallet.com/settings/connections?nwa=nostr%2Bwalletauth%3A%2F%2Fe552dec5821ef94dc1b9138a347b4b1d8dcb595e31f5c89352e50dc11255e0f4%3Frelay%3Dwss%253A%252F%252Frelay.damus.io%252F%26secret%3D0bfe616c5e126a7c%26required_commands%3Dpay_invoice%26budget%3D21%252Fday%26identity%3D32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245

I should handle this error better but also what is causing the error? @benthecarman

**Comment by futurepaul** [comment]
(probably our primal server actually)

**Comment by benthecarman** [comment]
We should probably fail gracefully here
