### ISSUE TITLE
Transaction completed..but not reflected in app wallet

### ISSUE THREAD

**Issue by AJMattt** [MutinyWallet/mutiny-web#782]
Completed an onchain transaction..but updated balance is not reflecting in app wallet

e8eff4d84262762a968465d220dec8985c80b43c9e77a42fc2abe684a0e939b1

**Comment by benthecarman** [comment]
There is a resync wallet button in the admin settings, can you try pressing that?

**Comment by AJMattt** [comment]
Tried pressing resync wallet.. it did not help..

**Comment by AJMattt** [comment]
Tried multiple time..did not help..a couple of time "recursive error ....aliasing in rust"..msg came up..pressed the Dangit button and wallet was up again..with the wrong balance though..

**Comment by AJMattt** [comment]
Put in the seed words in sparrow..zero balance..no utxos..no sats...mutiny app shows at least some balance..cannot understand at all..

**Comment by AJMattt** [comment]
Changed wallet settings to Taproot...saw the 1st UTXO..but the 2nd(2of2) is missing..shows an adress which is not in the list of addresses in sparrow..if it is lost..kindly let me know directly..

**Comment by TonyGiorgio** [comment]
Increase the gap limit.

**Comment by AJMattt** [comment]
Found all coins!! 
Increased Gap limit from 20 to 50..now i hiw to make the app see these sats?

**Comment by TonyGiorgio** [comment]
There's an open issue for this to be fixed.
