### ISSUE TITLE
Unable to disconnect peers

### ISSUE THREAD

**Issue by shyfire131** [MutinyWallet/mutiny-web#788]
Context:
I've been testing opening channels with peers using self-hosted Mutiny (no luck thus far, they all get closed but I'm testing it again now). My peer list is getting a bit long and I want to clean it up, but it's not a trainsmash. Trivial workaround for this issue is to scroll down :P

Steps to reproduce:
- Connect Peer in the admin page
- Wait for peer to show up under "Peers"
- Expand the peer
- Click "Disconnect"

Result:
- The button changes state but other than that nothing happens. Peer isn't removed and no errors.

**Comment by benthecarman** [comment]
Did you hit `refresh peers` afterwards, it should remove it from the list

**Comment by shyfire131** [comment]
OK cool, after clicking refresh peers and reloading mutiny it seems disconnected.

Is there a reason why the disconnect button doesn't automatically call refresh peers?

**Comment by benthecarman** [comment]
We didn't spend too much time on these as it's not expected to be used by end users. Can probably clean it up a little.
