### ISSUE TITLE
Can't receive a single SAT without incurring a 2nd setup fee

### ISSUE THREAD

**Issue by KruyKaze** [MutinyWallet/mutiny-web#791]
Just started using Mutiny and I have a channel with over 100k of inbound capacity . 
Yet i get this message when i try to receive a single SAT:
"A lightning setup fee of 77,764 SATS will be charged if paid over lightning."

Note that i have sent a couple of txs last 24hrs that only cost the normal LN fees.

Please let me know if you need further info.
Thanks for making Mutiny!

**Comment by KruyKaze** [comment]
Tried again today and I was able to move sats around no issues. 
Any idea why this is happening?

**Comment by benthecarman** [comment]
Some of your inbound capacity is part of the LSPs fee reserve, so it may look like you have 100k inbound but it's actually 100k minus the cost of closing the channel with current fees
