### ISSUE TITLE
iOS PWA completely unusable

### ISSUE THREAD

**Issue by davidohayon669** [MutinyWallet/mutiny-web#793]
this happened after the last update (offered inside the app)

receiving is stuck after "set amount"
sending is stuck on payment spinner
"channels" page is empty and then main page loads forever
basically after every action the main page goes into loading state forever

this is vanilla iOS safari PWA. no problems on android

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13824429/mutiny-logs.txt)

![signal-2024-01-04-014622_002](https://github.com/MutinyWallet/mutiny-web/assets/7001025/0e0f6c26-e257-4973-b92e-ab357caa9be1)
![signal-2024-01-04-014622_003](https://github.com/MutinyWallet/mutiny-web/assets/7001025/a5541bb1-2dcb-44a2-bdbd-c63b8979ced4)
![signal-2024-01-04-014622_004](https://github.com/MutinyWallet/mutiny-web/assets/7001025/43eb53f1-89c6-46d1-9e50-7f1c93d3dba5)
![signal-2024-01-04-014622_005](https://github.com/MutinyWallet/mutiny-web/assets/7001025/78021a0e-77bb-4a28-ad71-ac3afcf0a87c)

**Comment by TonyGiorgio** [comment]
Seems network related. Have you restarted the app and tried with different networks?

**Comment by TonyGiorgio** [comment]
I can't tell why this would be happening. Try restoring on a new device or on your device to see if it persists.

**Comment by davidohayon669** [comment]
@TonyGiorgio just to be clear. i do it with the emergency kit?

**Comment by TonyGiorgio** [comment]
No, there's a setting near the top of settings for 'restore'

**Comment by davidohayon669** [comment]
@TonyGiorgio do i restore it from the emergency kit from the current installation?

**Comment by benthecarman** [comment]
Just restore from seed, there is a red restore button in the settings

**Comment by davidohayon669** [comment]
@benthecarman doesn't it kills the channel? what was the emergency kit made for then?

**Comment by benthecarman** [comment]
it does not, emergency kit is for when your wallet for when wallet is in a irrecoverable state

**Comment by davidohayon669** [comment]
@benthecarman @TonyGiorgio the same exact behavior occurs on two different desktop browsers

on both instances a restore didn't end and the app loaded only after a refresh

getting this error if it can help:
<img width="379" alt="Screenshot 2024-01-06 at 3 55 12" src="https://github.com/MutinyWallet/mutiny-web/assets/7001025/6df4538a-fab0-4aab-9459-15b947f74c7c">

**Comment by benthecarman** [comment]
Can you post a log file, otherwise we have nothing to go off of

**Comment by davidohayon669** [comment]
@benthecarman this is the log from now. newly installed on a chromium on mac

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13850485/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Thanks for the insights @davidohayon669 we found the underlying issue and our next release will fix

https://github.com/MutinyWallet/mutiny-node/pull/953

**Comment by davidohayon669** [comment]
@benthecarman great. thanks

**Comment by benthecarman** [comment]
We just pushed the release, let us know if you run into any issues

**Comment by davidohayon669** [comment]
@benthecarman wallak working... was i the only one with this issue?

**Comment by benthecarman** [comment]
We had a few other people report, was pretty niche though
