### ISSUE TITLE
Just recently updated my Mutiny mobile wallet and my funds aren't there anymore...

### ISSUE THREAD

**Issue by chamoBtC** [MutinyWallet/mutiny-web#801]
Please see attachments

![IMG_3692](https://github.com/MutinyWallet/mutiny-web/assets/151878066/cc1ee1c6-d517-48d6-857f-0af1c5c4d34f)
![IMG_3693](https://github.com/MutinyWallet/mutiny-web/assets/151878066/1e2acf63-7fb0-49f0-a0bd-e65f7eeb2cbe)

Please advise

**Comment by chamoBtC** [comment]
Can you tell me how to do that?


Sent from Yahoo Mail for iPhone


On Friday, January 5, 2024, 12:48 PM, Tony Giorgio ***@***.***> wrote:




Can you submit logs?

**Comment by TonyGiorgio** [comment]
It's in the settings, in the emergency toolkit.

**Comment by chamoBtC** [comment]
See link 
mutiny-logs.txt 


  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
mutiny-logs.txt
 
Shared with Dropbox
  |   |

  |

  |

  



Sent from Yahoo Mail for iPhone


On Friday, January 5, 2024, 1:08 PM, Tony Giorgio ***@***.***> wrote:




It's in the settings, in the emergency toolkit.

**Comment by TonyGiorgio** [comment]
That didn't work. Please log into github and upload the file.

**Comment by chamoBtC** [comment]
Okay give me a few that I am at work 


Sent from Yahoo Mail for iPhone


On Friday, January 5, 2024, 1:18 PM, Tony Giorgio ***@***.***> wrote:




That didn't work. Please log into github and upload the file.

**Comment by chamoBtC** [comment]
See below. 

Let me klnow if that works 


[mutiny-logs 2.pdf](https://github.com/MutinyWallet/mutiny-web/files/13845987/mutiny-logs.2.pdf)

**Comment by TonyGiorgio** [comment]
No, that's a pdf somehow?

**Comment by chamoBtC** [comment]
yes it is a PDF with all the logs

**Comment by TonyGiorgio** [comment]
Why did you convert it to a PDF? It should be just the text log file.

**Comment by chamoBtC** [comment]
here you go 

Let me know if that works

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13846037/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Thanks. Are you using this same wallet on multiple devices at the same time? I see you have some force closed channels that are recent and those require a couple days to sweep back to your on chain wallet. There are missing logs and an indication that you were using a different device at some point over the last few days, and the reason for the channel closes are probably on the other device. 

I'd wait a few days and let us know if the funds don't get swept back. Usually there's an indication about this on the device that resulted in closed channels.

**Comment by chamoBtC** [comment]
Yes I download it Mutiny on my start9 server before but I closed it because for some strange reason even though I was using the same wallet(meaning same seeds back up ) the balance was Zero in star9 mutiny wallet. it didn't reflect the amount in Mutiny Mobile which it was $80

**Comment by benthecarman** [comment]
Restoring seed from our instance to a self hosted instance does not restore channels.

**Comment by chamoBtC** [comment]
Understood 

So we just wait few days and see?

**Comment by TonyGiorgio** [comment]
Yes

**Comment by chamoBtC** [comment]
Thank you

**Comment by chamoBtC** [comment]
Hi Tony,

FYI- Still no balance in my Mutiny mobile wallet 

Please advise

**Comment by TonyGiorgio** [comment]
Sorry this was missed. Opened the issue back up. Please submit logs again.

**Comment by chamoBtC** [comment]
okay will submitt the logs again. Give me a few

**Comment by chamoBtC** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13944104/mutiny-logs.txt)

here you go

**Comment by TonyGiorgio** [comment]
This looks like a brand new node that has no log history beyond a couple minutes ago and does not have a channel. Make sure you're restoring from the same seed words you had originally. If you're absolutely sure it is, then did you recently restore? There's no history, and our ability to help you goes down significantly. I can reach out to the LSP with your node id if you're sure you're using the same seed words.

**Comment by chamoBtC** [comment]
Yes I  just restored this wallet in my start9(I deleted before)  just now with the same seeds with my mobile mutiny wallet

Below is the logs I sent you 
before
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13846037/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
> Restoring seed from our instance to a self hosted instance does not restore channels.

Okay well there's this that ben said earlier. So you'll need to use your start9 instance again if you want to restore your start9 funds.

**Comment by chamoBtC** [comment]
How I  can do that?

**Comment by chamoBtC** [comment]
FYI- My funds was first from my Mobile Mutiny wallet. it wasn't in my start9. When Mutiny was available in start9, I  decided to download it and have it there as well with the same seeds. I had never since my balance in start9 from the get go. then, when mutiny release a new update I believe few weeks ago, after  I updated the new release my balance went $0. Not sure how that happend(all this happened before I download it Mutiny on start9) everything was a bit confusing to me.

**Comment by chamoBtC** [comment]
<img width="607" alt="Screenshot 2024-01-15 at 8 12 32 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/151878066/74477e90-49ba-44e5-aa1a-32d760b582a2">

**Comment by chamoBtC** [comment]
That attachment a from my current Mutiny at start9

below is from Mutiny mobile 


![IMG_3714](https://github.com/MutinyWallet/mutiny-web/assets/151878066/165efcb2-32e8-48be-ae86-8845b38312cd)

**Comment by chamoBtC** [comment]
Sorry if I wasn't clear. I have been using Mutiny in my mobile for a while. All was fine until I uploaded the new realese update from Mutiny in my mobile. Afterwards, my balanve went to $0. I  knew something wasn't quite right so I decided to download Mutiny in start9 with the same seeds and see what ws going on.  After I did that, the balance was $0 just as my Mobile Mutiny wallet. I  believe all these happened after I updated the mutiny mobile wallet. That's pretty much how it happened

**Comment by chamoBtC** [comment]
Appreciate your time and help

**Comment by TonyGiorgio** [comment]
That makes more sense. Will wait a few days for what the LSP says, but don't use the start9 version anymore since the funds were not there originally.

**Comment by chamoBtC** [comment]
Okay, Will do

Thank you

**Comment by chamoBtC** [comment]
just strange 'cause I don't recall closing and spending those channels on my end. How can I  do the "rescan" in my settings? Will check Sparrow as well

Thank you for your help

**Comment by TonyGiorgio** [comment]
If you look at your activity list, you have 3 on chain transactions showing up. You have two transactions that add to your balance from the channel closes, and you have on transaction that spends them. It doesn't show in the correct order but those are actually the total. Do you remember withdrawing 185k sats on 1/4? 

The reason you show 0 balance is because you indeed have 0 balance. So there's nothing left for us do here.
