### ISSUE TITLE
Closed channel and no on chain Bitcoin

### ISSUE THREAD

**Issue by G23N** [MutinyWallet/mutiny-web#802]
I have used Mutiny wallet for some time. At some point I was trying to send a transaction and the channel was closed. Now I see my funds supposedly are on chain but when trying to send them the wallet displays no balance, if I try to set an amount the wallet gets stuck.

I have tried to restore the wallet but nothing works, I have also tried to receive some sats via lightning network. The wallet gets stuck.

How can I get back control of my funds?

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13853511/mutiny-logs.txt)

![Screenshot_20240107-130141](https://github.com/MutinyWallet/mutiny-web/assets/105127925/2ee53a21-1f71-4014-a28b-103aa4372357)
![Screenshot_20240107-130223](https://github.com/MutinyWallet/mutiny-web/assets/105127925/801eb0ec-54e9-4e18-b371-2b4db332a714)
![Screenshot_20240107-130230](https://github.com/MutinyWallet/mutiny-web/assets/105127925/6c0a6076-4181-4d60-838e-e59259f62ff9)

**Comment by G23N** [comment]
5 days

**Comment by G23N** [comment]
> How long has it been since the channel closed?

What should I do to get the funds back?

**Comment by TonyGiorgio** [comment]
Please submit logs again, the latest should have additional information for us to work with.

**Comment by G23N** [comment]
There you go
[mutiny-logs_1.txt](https://github.com/MutinyWallet/mutiny-web/files/13892059/mutiny-logs_1.txt)

**Comment by TonyGiorgio** [comment]
Nodeid: `03e50f0981724fcca6f4f0b63447ab06a69a8c0f91c55cad0986f4a715a0123aca`

I'll reach out to the LSP to see if anything is going on on there end. It seems like there's communication problems back and forth between you two.

**Comment by TonyGiorgio** [comment]
Okay, it looks like the problematic channel closed properly and got confirmed: https://mempool.space/address/bc1q2y7zyk40uqjv34gu30nlpewlf5vwnc2tvmfkmskka0azkfwnns8quqr9v9

Since it was a force close, it might *now* take a few days for the funds to sweep back. Perhaps our update did fix things and it allowed the channel closure process to start. So if you can check up on it in 3 days, wait a minute or so to see if a "swept" transaction happens, you should have your funds available to spend again. Let us know if there's anything else weird going on besides that.

**Comment by G23N** [comment]
Thanks for helping out. I will write here again if the funds will not be spendable in 3 days or so. Will I have them on chain or on a new lightning channel?

10 Jan 2024 20:20:50 Tony Giorgio - notifications(a)github.com ***@***.***>:

**Comment by TonyGiorgio** [comment]
They will appear on chain. Not sure why it closed but it looks like you had a couple other channels that are still active.

**Comment by G23N** [comment]
I have had much more difficulty to pay lightning invoices on bitrefill then I had using Wallet of Satoshi. I am trying to transition to a non custodial lightning wallet but there are too many problems for my taste. Lightning network manages to be even worse then the banking/debit card system!

10 Jan 2024 20:45:01 Tony Giorgio - notifications(a)github.com ***@***.***>:

**Comment by TonyGiorgio** [comment]
Sorry about that. Let me know if there's anything else you need assistance with.

**Comment by G23N** [comment]
No problem it is not your fault, it seems hard to deal with lightning network in general. You closed the issue but I do not have my money yet :D.

10 Jan 2024 22:06:37 Tony Giorgio - notifications(a)github.com ***@***.***>:

**Comment by TonyGiorgio** [comment]
I expect things to resolve in a few days but comment again or open it back up if they don't.

**Comment by G23N** [comment]
I did not get my sats yet.

10 Jan 2024 22:20:46 Tony Giorgio - notifications(a)github.com ***@***.***>:

**Comment by G23N** [comment]
I still need help my money is stuck.

**Comment by TonyGiorgio** [comment]
Submit logs again, the funds should have swept back.

**Comment by G23N** [comment]
[mutiny-state.json](https://github.com/MutinyWallet/mutiny-web/files/14015607/mutiny-state.json)

**Comment by TonyGiorgio** [comment]
You did not upload your logs, you just uploaded your entire state. Your seed has been compromised and you need to withdrawal all funds off.

**Comment by G23N** [comment]
[Uploading mutiny-logs (1).txt…]()

**Comment by G23N** [comment]
> You did not upload your logs, you just uploaded your entire state. Your seed has been compromised and you need to withdrawal all funds off.

Well, I would if I could. I just uploaded the logs

**Comment by benthecarman** [comment]
> Uploading mutiny-logs (1).txt…

this is a link to the issue, not the logs

**Comment by G23N** [comment]
> > Uploading mutiny-logs (1).txt…
> 
> this is a link to the issue, not the logs

Updated, now it is logs.

**Comment by benthecarman** [comment]
Looks like you might just have bad internet or something. Maybe try refreshing
