### ISSUE TITLE
Keyboard won't pop up on PWA

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#804]
Submitted via twitter. Keyboard won't pop up on the seed restore screen on iOS PWA. This is pretty important to fix asap @futurepaul 

<img width="490" alt="Screenshot 2024-01-08 at 9 42 53 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/101225832/5333dbb2-5ed9-4456-944e-172500e055f3">

**Comment by futurepaul** [comment]
Can't repro on my phone. Looks like they maybe have a bluetooth keyboard connected or are using it in the simulator?

**Comment by TonyGiorgio** [comment]
> Can't repro on my phone. Looks like they maybe have a bluetooth keyboard connected or are using it in the simulator?

I asked just now, will let you know what they say.

**Comment by TonyGiorgio** [comment]
They said no, so I redirected them here to provide more info.

**Comment by TonyGiorgio** [comment]
Closing unless we have more information to go off of or someone else reproduces.
