### ISSUE TITLE
Channel open issue with Cashu

### ISSUE THREAD

**Issue by satssuperstore** [MutinyWallet/mutiny-web#812]
I tried to open a channel by paying the invoice from a Cashu wallet. I got some sort of input/output mismatch error and now I have 0 sats in the Cashu wallet and no sign of the invoice being paid in Mutiny. 
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13896800/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Which cashu wallet are you using? Does a preimage show up on your sending wallet? That's the proof of payment. If there is none then it proves there's not a payment that made it to you. 

I don't see any indication in the logs that a payment made it to your mutiny wallet at all. No channels created, no invoice paid, etc. I don't think there's anything we can do on our end. You may have to go to the cashu wallet provider and ask them what happened.

**Comment by satssuperstore** [comment]
I'm using Cashu.me. There doesn't seem to be much info unfortunately. Don't see anything about primates either. 
![Screenshot_20240110-211116_Chrome](https://github.com/MutinyWallet/mutiny-web/assets/156273532/f221a218-48c5-4a8b-8303-f2ba30fdc71c)

**Comment by TonyGiorgio** [comment]
You might want to hit up their github for further support: https://github.com/cashubtc/cashu.me

With no proof of payment and no logs that indicated a successful receive (I see the pending invoices and stuff, there's just not a payment that made it to your wallet), I am afraid there's nothing we can do on the mutiny side. 

Perhaps their ecash refund flow isn't working correctly for payments that fail.

**Comment by satssuperstore** [comment]
Thanks Tony. Really appreciate it. I'll go try to get some help over there.

**Comment by Kodylow** [comment]
@TonyGiorgio hey I'm helping out cashu side, is there a way to get the specific invoice mutiny side and see whether it was paid? Need it to give to the mint operator to look up, trying to figure out how to get it from nutshell but it's on his phone so hard to extract

**Comment by TonyGiorgio** [comment]
The unwrapped invoice should be in the logs. We don't log the wrapped invoice. Do you need the whole invoice or just the payment hash ? If it's just the payment hash then it would be fine. Otherwise I need to reach out to our LSP to get the whole invoice.

**Comment by Kodylow** [comment]
Payment hash should be good to go

**Comment by TonyGiorgio** [comment]
```
3d99 2024-01-10 20:22:46.793 TRACE [lightning_invoice::utils:537] Creating invoice with payment hash 0d4ae87b14ea8425f4dd2cb0e498e51f2363c24eb0110342bdc4d33e5b5f8dac
3d99 2024-01-11 01:28:01.173 TRACE [lightning_invoice::utils:537] Creating invoice with payment hash d5d253a5112dd85835691a7c2a1610797bd1a8fed12f36d2572fbe3537e5dabb
3d99 2024-01-11 01:29:40.429 TRACE [lightning_invoice::utils:537] Creating invoice with payment hash 91f42c7ecfcc117087927734cb88fb0ec1e7101de75ec452886b1ec52d5f27ef
3d99 2024-01-11 01:30:26.213 TRACE [lightning_invoice::utils:537] Creating invoice with payment hash 97091f43f7b4f74139a34ec42cedda33e6f365d0ed3db487e1c1816eb367a4e7
```

**Comment by callebtc** [comment]
Checked all of these and haven't found any of them in the db

**Comment by satssuperstore** [comment]
Hey @TonyGiorgio. Is there anything else you can do to help?

**Comment by TonyGiorgio** [comment]
No unfortunately not, it is not our wallet that failed here. The payment never came from your other wallet. You'll have to talk to them if you're missing funds there.
