### ISSUE TITLE
feature: add language options on settings page

### ISSUE THREAD

**Issue by oleonardolima** [MutinyWallet/mutiny-web#830]
## What
I've discussed this with @futurepaul and @benthecarman in the past few days, and I think it would be useful to be able to change the language through the settings page as well, instead of just relying on the browser/phone default language.

## Why
It's useful for users who would like to have different languages on their devices for different purposes or are abroad and another language would be suitable in that situation.

## How
Something alongside the style and options for currency selection, nothing else would be needed to change in my opinion.

--

**note:** I'm open to trying this one but would like to know your views and opinions beforehand.

**Comment by futurepaul** [comment]
Yeah that would be great. Can default to region detection and then if they manually set a language we can remember that.

**Comment by oleonardolima** [comment]
Great! I'll work on that then.
