### ISSUE TITLE
Ubable to find route

### ISSUE THREAD

**Issue by BrutusBondBTC** [MutinyWallet/mutiny-web#836]
Hi. I opened u[p a lightning channel on mutiny wallet using my Start9 server. It says I have an  open channel, but when I send a payment it says "unable to find route." How do I fix this?

**Comment by TonyGiorgio** [comment]
Does it have 6 confirmations yet? Does it show that the activity item for the channel open is still pending?

**Comment by BrutusBondBTC** [comment]
the on chain transaction has 265 confirmations according to the log. I double checked it on mempool.space too, but are you talking about the 2-of-2 multi-sig required for the lightning channel?  I'm not sure where to find that.

**Comment by BrutusBondBTC** [comment]
Okay. It looks like the locktime is set until block ‎825,936.  I'll try after that. Thank you. 

![locktime](https://i.nostr.build/QraK.png)

**Comment by BrutusBondBTC** [comment]
Wait it's block 826,191 😰 Now what?

**Comment by TonyGiorgio** [comment]
Just wait until 6 blocks and it will be usable

**Comment by BrutusBondBTC** [comment]
Ok. I'll try tomorrow. Thanks.
