### ISSUE TITLE
oof. another force close

### ISSUE THREAD

**Issue by davidohayon669** [MutinyWallet/mutiny-web#839]
this time i don't remember having any pending HTLCs, i make sure to notice this all the time

the channel was closed yesterday (18)

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/13994113/mutiny-logs.txt)

what happened and what should i to to make sure this don't happen?

**Comment by TonyGiorgio** [comment]
> Force-closing channel due to outbound HTLC timeout, HTLC expiry is 825928

Not have a pending transaction

**Comment by davidohayon669** [comment]
can i know what was the payment?

**Comment by TonyGiorgio** [comment]
According to the logs it was some payment you made on 1-13-24 to the "Forever Laura" node. You didn't open the app again until ~5 days later so yeah it needed to be closed.

**Comment by davidohayon669** [comment]
@TonyGiorgio thank's. that's my personal node, i don't this it was the one to withhold the htlc

**Comment by TonyGiorgio** [comment]
It looked like it was just still finding routes to it until the application was backgrounded/closed. Went down a few routes that had failed.

**Comment by davidohayon669** [comment]
@TonyGiorgio seems like it's critical to let the user know something is still pending so leaving the app closed a few days will rug the channel

i thought i'm on top of it but it got me again
