### ISSUE TITLE
Error: Incorrect expected network.

### ISSUE THREAD

**Issue by snuglypursuit** [MutinyWallet/mutiny-web#846]
Getting this error after upgrading to v0.5.5

Have tried the deleting everything option.
Have also tried uninstalling and reinstalling the apk.

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14016799/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Did you add a signet federation to your mainnet wallet?

**Comment by snuglypursuit** [comment]
Yes

**Comment by TonyGiorgio** [comment]
Not sure why you did that but that's the problem. 

Were you using your mainnet wallet with funds on it? Having a signet based federation configured in your mainnet wallet would have rendered it useless anyways.

**Comment by benthecarman** [comment]
If you're using the android app you can downgrade and remove the federation, then upgrade the app again

**Comment by snuglypursuit** [comment]
@TonyGiorgio I did it. I had not realized it was a signet federation at first. Is there a way to detect when a federation string is signet to prevent mixing?

@benthecarman restoring works after downgrading. But, I think that version is before the federation persistence. The list of federations is empty. I do not see anything that would flush any stored values. I'll just close the channels and withdraw on-chain.

**Comment by benthecarman** [comment]
Let us know if that works, sorry about the confusion
