### ISSUE TITLE
I just wanna get on with my life

### ISSUE THREAD

**Issue by SilverLenZ** [MutinyWallet/mutiny-web#848]
I look at the kightning channel and I have outbound 147117 sats available to withdraw. But when I try to do that I keep reducing and reducing the 1% more and more and cannot send out. 

I'm done with mutiny. I already lost money. 

Why can't I withdraw it 
![Screenshot_20240124-054140_Brave - Nightly](https://github.com/MutinyWallet/mutiny-web/assets/107519663/ca78c36c-8899-4a95-86dc-5df9f992ac10)
![Screenshot_20240124-054028_Brave - Nightly](https://github.com/MutinyWallet/mutiny-web/assets/107519663/860f50d8-d6f9-4ab1-8f69-1dec6e2b3490)

**Comment by TonyGiorgio** [comment]
Close the channel and move the funds to a different wallet. Move on.
