### ISSUE TITLE
Failed to create channel (Chrome)

### ISSUE THREAD

**Issue by Boogyinkid** [MutinyWallet/mutiny-web#856]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14076872/mutiny-logs.txt)

I've certainly swapped from on-chain to lightning before without issue. Just looking to open a small channel for Nostr/to get a feel for the app again now that I have time, before subscribing to + to get TestFlight access.

Many thanks.

**Comment by benthecarman** [comment]
Looks like you might have had some connectivity issues, it is continually trying to create the channel

**Comment by Boogyinkid** [comment]
> Looks like you might have had some connectivity issues, it is continually trying to create the channel

Strange. Every else/other devices appear to be running as normal. I'll reboot and try again.

**Comment by Boogyinkid** [comment]
No dice on Mac or iOS via Chrome.

I'll try again in a few days.

**Comment by Boogyinkid** [comment]
Moved my off-chain balance out and created a new Mutiny wallet. Worked as intended. All resolved.
