### ISSUE TITLE
wallet failed to load

### ISSUE THREAD

**Issue by Virbac32** [MutinyWallet/mutiny-web#860]
Hi, I can't get into my wallet. See screenshot below, and I have attached the logs. I have been using it ok for past 5 or so months. When I logged into the laptop browser 2 weeks ago, it requested an update. I then made a transaction, which worked fine. Today I initially forgot my password. So I hit forgot password, and thats when I started getting the screenshot message below. I did attempt to export wallet state into a new browser. But that didn't work either. Unsure if I executed that correctly though. I'm not great at this tech. Any assistance would be much appreciated. It won't work on my phone. I keep getting the screenshot below as well. 

![image](https://github.com/MutinyWallet/mutiny-web/assets/113769157/c3ae04f2-3ac6-4a7e-a8af-b58e1dcfc833)
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14106773/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
If you forgot your password then just do a normal restore from seed words.

**Comment by Virbac32** [comment]
Tried that. Entered my seed words and that didn’t work. I get the same screenshot I sent.

**Comment by benthecarman** [comment]
This error normally means you're unable to access mempool.space 

Possibly your internet is shotty?

**Comment by TonyGiorgio** [comment]
Not seeing a problem in the downloaded logs. Try opening the console logs of your browser and seeing what errors show up there.

**Comment by Virbac32** [comment]
I haven’t had any issues with my internet. I’ve been using Mutiny for 4-5 months on my existing wifi, with no problems until today

**Comment by Virbac32** [comment]
How do I access those logs if I can’t login to my wallet please?

**Comment by benthecarman** [comment]
> I haven’t had any issues with my internet. I’ve been using Mutiny for 4-5 months on my existing wifi, with no problems until today 

your log file indicates slow/bad internet

> How do I access those logs if I can’t login to my wallet please?

press f12

**Comment by benthecarman** [comment]
Any updates here?

**Comment by Virbac32** [comment]
It’s working ok now. Thanks
