### ISSUE TITLE
[Feature] coin control for on-chain spends

### ISSUE THREAD

**Issue by shyfire131** [MutinyWallet/mutiny-web#864]
I know the current focus is higher layers, but seems like an important feature for a privacy wallet: give users visibility into UTXOs in the wallet. At least for the next few years anyway....

**Comment by benthecarman** [comment]
We can do it without changes from BDK, just haven't gotten around to adding it to mutiny-node yet since most users just use lightning primarily

**Comment by shyfire131** [comment]
Ah this should have been on mutiny-node, my bad.
