### ISSUE TITLE
First lightning transaction did not open channel

### ISSUE THREAD

**Issue by bronco1** [MutinyWallet/mutiny-web#889]
I created an invoice, and paid it via lightning.   I can see the payment completed.  I can see the transaction in the activity,

But there isn't a channel open, no balance, not able to send.    

What should be done to resolve the issue?

**Comment by benthecarman** [comment]
Can you submit logs and screenshots, otherwise we aren't able to help you

**Comment by TonyGiorgio** [comment]
Something went wrong with the channel. The logs also do not go very far back. Are you using this wallet on multiple devices at the same time?

**Comment by bronco1** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14320093/mutiny-logs.txt)
Yes.  I imported the state to a different browser, hoping it would refresh properly or something.    Here's the log from the original browser.

**Comment by bronco1** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14320137/mutiny-logs.txt)
Yes, I imported the state to a different browser, hoping it would reset.   Here's the log from the original browser

**Comment by TonyGiorgio** [comment]
The logs aren't going back far enough to see what the original issue is. We'll reach out to the LSP to see if the channel appears on their end and what the status of it is. 

node: `03a9f16b52e71baeac05102fa112302f3d20890052dee4151703ce51c99d8147f8`

**Comment by TonyGiorgio** [comment]
Does anything show up in the channel view in the settings?

**Comment by bronco1** [comment]
The channel page is empty


![Screenshot_20240217-160521.png](https://github.com/MutinyWallet/mutiny-web/assets/47600049/d7d0e4c0-7797-41b1-9727-038b934e2a33)

**Comment by TonyGiorgio** [comment]
Are you using the original browser to check this? Is there anything if you go to admin tools and look at the channel list there? 

It's never been the case previously that channels just disappear on the mutiny wallet side. It shows that the channel exists on the LSP side. So I'm very unsure what happened to cause this and if it's the result of bouncing between multiple devices.

**Comment by TonyGiorgio** [comment]
One problem I notice is that there seems to be multiple "node managers" that have been initialized and created, but the channel does/should exist. We'll have to spend some time thinking about this problem and how to reproduce/solve it. Though any additional information you can provide will go a long way. We'll hopefully have something additional later this week.

**Comment by benthecarman** [comment]
@bronco1 as @TonyGiorgio said, this seems to a weird bug where multiple versions of the channel manager were spun up. It seems the one that has the channel is not the one that is saved to your local storage. This should be fixable.

In your state file you'll have something like this
```json
{"nodes":{"bd2d8dba-a5e1-4415-a58b-fc767b16d1db":{"child_index":0,"lsp": "..."},"archived":false}},"version":3}}
```

what you will need to do is replace the uuid (here in my case it's `bd2d8dba-a5e1-4415-a58b-fc767b16d1db`) with `4223775b-2702-4a65-88d8-8af82cc33e65` and you'll want to increase the version number.

If you edit that and import the new state file that should hopefully resolve the issue.

**Comment by bronco1** [comment]
Thank you both, this did resolve my issue.

**Comment by TonyGiorgio** [comment]
Great, thank you for reporting! The next version should prevent this from happening to other people, it is apparently a rare edge case.

**Comment by bronco1** [comment]
I've subscribed to Mutiny+.   looking forward to your future updates..

**Comment by TonyGiorgio** [comment]
> I've subscribed to Mutiny+. looking forward to your future updates..

Thank you for the support!
