### ISSUE TITLE
Node hangs with specific federation

### ISSUE THREAD

**Issue by lescuer97** [MutinyWallet/mutiny-web#890]
my current Version is v0.5.9 put it also the problem appears in previous versions. 
For some reason my node started hanging on Setup. 

I reinstalled the app and the setup ran perfectly. but when I restored with my words they hanged again. 

Logs:
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14322669/mutiny-logs.txt)

screenshot:
![signal-2024-02-18-144142](https://github.com/MutinyWallet/mutiny-web/assets/47948594/a8d724c5-edbb-47ed-a1d0-e0ca1d82d5f2)

**Comment by TonyGiorgio** [comment]
The logs are helpful, thank you. 

We made things less reliant during the startup phase so I'm wondering what's blocking here. The logs indicate fedimint related activity happening, there could be something blocking there but Ben would know more. 

Can you describe a little bit what your current wallet is? For instance, do you have channels? It looks like a federation is added, do you know if that is on mainnet (we had issues early on where people were adding signet federations). Do you know if you have funds on that federation?

**Comment by lescuer97** [comment]
> The logs are helpful, thank you.
> 
> We made things less reliant during the startup phase so I'm wondering what's blocking here. The logs indicate fedimint related activity happening, there could be something blocking there but Ben would know more.
> 
> Can you describe a little bit what your current wallet is? For instance, do you have channels? It looks like a federation is added, do you know if that is on mainnet (we had issues early on where people were adding signet federations). Do you know if you have funds on that federation?
> 
> Could you try different networks too, in case something is being blocked? VPN perhaps?

I have only one channel at this time. I did have a federation synced mainnet. I was running the ctrb.io fedimint. `fed11qgqpu8rhwden5te0vekjuem9dejhx6tn9e3hgunz9e5k7tmhwvhsqqfq5a2sy0f26k6ndld2qpassl0gd4cx2szmfv98zfn83ywp4mja3m4s7yz4zq`. I'm pretty sure I had sent a couple sats to the federation. 

I did try a VPN and multiple networks. Same results

**Comment by benthecarman** [comment]
Looks like this is a bug in fedimint, have a bug fix here: https://github.com/fedimint/fedimint/pull/4356

**Comment by lescuer97** [comment]
should the fedimint update to this release?

**Comment by benthecarman** [comment]
No it's a client side bug, we'll need to update on our side.
