### ISSUE TITLE
Wallet suck on 'Loading: Setup'

### ISSUE THREAD

**Issue by aChrisYouKnow** [MutinyWallet/mutiny-web#898]
After using Mutiny for a while, one day I opened it and it wouldn't fully load. I have tried restoring my seed phrase via an iOS PWA, the iOS safari browser, and a desktop Firefox browser. Same result for each (images below). 

Any suggestions for how to get my wallet running again? Apologies if this is a known issue I didn't find when searching. 

![IMG_4910](https://github.com/MutinyWallet/mutiny-web/assets/15918863/7c5a759d-63f3-46d9-b90a-e5eb297423b3)
![IMG_4911](https://github.com/MutinyWallet/mutiny-web/assets/15918863/07e78aef-d33c-444d-bf6b-c70c0534350c)
<img width="817" alt="image" src="https://github.com/MutinyWallet/mutiny-web/assets/15918863/89edca8e-13b7-49e3-8286-6cc913c4b6a5">

**Comment by aChrisYouKnow** [comment]
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14367581/mutiny-logs.txt)

Log file attached

**Comment by TonyGiorgio** [comment]
Do you have a federation added and which federation? I think it's the same issue as this: https://github.com/MutinyWallet/mutiny-web/issues/890

**Comment by aChrisYouKnow** [comment]
Ah yes, I did add the same federation as that issue to test it out (fed11qgqpu8rhwden5te0vekjuem9dejhx6tn9e3hgunz9e5k7tmhwvhsqqfq5a2sy0f26k6ndld2qpassl0gd4cx2szmfv98zfn83ywp4mja3m4s7yz4zq). I don’t think I have any sats in the federation though, so just removing it would be fine if possible.

**Comment by TonyGiorgio** [comment]
Our next version of mutiny should have it fixed but until then, yeah you can remove it. See if you can get to the federation settings screen to remove it.

If not, you should be able to download and then edit the state.json file if you wanted to replace: `"federations":{"federations":{},"version":2}` but instead of `2`, increment the number by one from what it is for you.

**Comment by aChrisYouKnow** [comment]
Thanks. Can't get to the federation settings to remove it, but I changed the state.json to version 48 from 47. Getting an error that Mutiny is running in another browser now. Everything is closed all all devices, but, I'll give it some time and try again later. Appreciate the help.

**Comment by aChrisYouKnow** [comment]
Update: even after hours of all instances being closed, whenever I try to load in the edited state file, I get stuck here: 
![IMG_4914](https://github.com/MutinyWallet/mutiny-web/assets/15918863/2c4b7599-43ed-400b-8872-1718d3ec40f2)

No immediate rush, just wanted to add the latest. Thanks!

**Comment by TonyGiorgio** [comment]
If mutiny is already running, it's already running. You need to make sure it's closed everywhere where it might be.
