### ISSUE TITLE
No ability to enter amount to receive on desktop

### ISSUE THREAD

**Issue by merlinoa** [MutinyWallet/mutiny-web#903]
When opening the receive page on a desktop, there is no input to enter the amount.  This is the screen that I see (with no way to enter an amount) on my desktop:

<img width="1175" alt="Screen Shot 2024-02-24 at 2 12 33 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/4030554/5883549c-9429-41aa-af7a-18429d3eecb1">

On mobile this page opens the keyboard for you to enter the amount, but on desktop I don't see a way to enter an amount.

**Comment by benthecarman** [comment]
You type with your keyboard

**Comment by merlinoa** [comment]
Got it. thanks.  Maybe I am an idiot, but it wasn't obvious to me what to do
