### ISSUE TITLE
12 mini UI mutiny iOS conflict

### ISSUE THREAD

**Issue by alltheseas** [MutinyWallet/mutiny-web#910]
Before scroll ![image](https://github.com/MutinyWallet/mutiny-web/assets/64376233/179d40fa-01f6-4b88-b1b3-21c903feea54)

After scroll

![image](https://github.com/MutinyWallet/mutiny-web/assets/64376233/081712b6-b81c-48a7-ba93-808cb41b5f28)

**Comment by futurepaul** [comment]
Can you test with the new design? (Just update to the latest version). Attempted to fix it there

**Comment by alltheseas** [comment]
Improved, and there remains overlap. Can you add a black color header row so that no overlap is possible with the clock in the top left corner?

Screenshots below: 

![image](https://github.com/MutinyWallet/mutiny-web/assets/64376233/adc00887-8a01-4c63-8ddb-a0651e79d9d2)

![image](https://github.com/MutinyWallet/mutiny-web/assets/64376233/3873f873-944f-4e3d-bc43-928a40fd3b4b)

![image](https://github.com/MutinyWallet/mutiny-web/assets/64376233/f25a43dc-ef53-4385-bbc7-fbd671b53bdc)
