### ISSUE TITLE
random close

### ISSUE THREAD

**Issue by umk0m1qk** [MutinyWallet/mutiny-web#913]
I keep being told this happens because I don't open the app for several days. Not buying it. I try to open every single day. Occasionally I might miss one, but not several. I'm a simple, non-technical user who just wants to zap devs.
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14503989/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
You're right, there was a payment that was attempted before the blocks were synced. Then when the block was synced, it noticed it was behind. There's a few issues where something needs to be opened up and worked on. Thank you for this report, sorry this happened but we'll fix it.
