### ISSUE TITLE
Failed to find route

### ISSUE THREAD

**Issue by unwired01** [MutinyWallet/mutiny-web#914]
Hi,
I’m trying to send sats from the wallet. I have more than 300K and the channel is online. I received an error message ’Failed to find route’

[mutiny-logs 3.txt](https://github.com/MutinyWallet/mutiny-web/files/14509872/mutiny-logs.3.txt)

**Comment by TonyGiorgio** [comment]
Seems to be happening against the coinos node. Have you tried others and have you tried different/lower amounts?

**Comment by unwired01** [comment]
@TonyGiorgio I split the amount into pieces and was able to send all of it. Thank you
