### ISSUE TITLE
unexpected channel closed 

### ISSUE THREAD

**Issue by chainiso** [MutinyWallet/mutiny-web#915]
Could you revert it ?

Channel closed because counterparty force-closed with message: Offered HTLC 17 SENT_ADD_ACK_REVOCATION cltv 833547 hit deadline

ID
1babc6f3185c73b6f2b227b104c77c82b9496bd8af3fe49d33731a40f19be0ee

#support

**Comment by benthecarman** [comment]
I'm guessing this is the same issue as 

https://github.com/MutinyWallet/mutiny-node/issues/1055

**Comment by TonyGiorgio** [comment]
We can't "revert" it but we can take a look at what happened. 

Please upload the logs from the emergency toolkit page of the settings.
