### ISSUE TITLE
Boltz swap liquid to lightning stock on 'Transaction received, paying invoice.'

### ISSUE THREAD

**Issue by Nopenotee** [MutinyWallet/mutiny-web#920]
Initiated a swap from Liquid (sideswap) to Lightning (mutiny). Unfortunatly my computer shutdown during the process (and therefore closing the browser with mutiny open on it). When rebooted, on Boltz I see the swap still trying to execute 'Transaction received, paying invoice.' I did the swap by doing an invoice request from Mutiny. But, after reboot, on the Mutiny page I can't go back on the same receive windows I was on (waiting for the invoice to process).  Which mutiny said to don't close while the transfert was being execute. It was the first transaction to this mutiny wallet, so this would involve an on-chain transaction. Also, if I try to refund the swap on Boltz, at the moment I download the file on the page, Boltz send me back to the swap page with the transaction still trying to go throught.
how can I recover these Satoshi ?

Thank

**Comment by TonyGiorgio** [comment]
It's okay if the invoice screen goes away, it would still be received if you keep mutiny open in general. Even on the home screen.

It's possible that boltz is attempting to pay but it's not finding a route and not going through. On the boltz side it will fail and allow you to refund if that's the case. 

You can also send on chain funds into mutiny and open a channel with it.

**Comment by TonyGiorgio** [comment]
Payment would have either completed or got refunded back. Let us know if there's anything we can do.
