### ISSUE TITLE
Amount input: DEL as backspace icon, clear button

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#93]
<img width="501" alt="Screenshot 2023-05-11 at 2 18 57 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/d77eea0b-b1b0-4985-a7af-811dc7b5b9fe">

**Comment by benalleng** [comment]
With the "." existing in fiat how should we adjust the clear button in that case?
