### ISSUE TITLE
Show the 100k minimum lightning deposit

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#930]
I think we either accidentally got rid of this changing the text or it's not popping up anymore.

Create a new wallet, select receive, type 1000

There should be some text warning that it needs to be 100k or more.

**Comment by futurepaul** [comment]
this got fixed in the social redesign

<img width="495" alt="Screenshot 2024-04-03 at 11 06 34 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/2ed028b0-4934-4c71-9b29-e86c1c00e68f">
