### ISSUE TITLE
nostr zap shows pending, then disappears

### ISSUE THREAD

**Issue by umk0m1qk** [MutinyWallet/mutiny-web#934]
Nostr zap shows pending, then disappears from Activity. No change in available balance. No explanation or error message.

[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14731847/mutiny-logs.txt)

**Comment by benthecarman** [comment]
Looks like the payment is timing out. We have been having some payment issues to alby which it seems where the payment was going.
