### ISSUE TITLE
recovery funds are missing

### ISSUE THREAD

**Issue by chainiso** [MutinyWallet/mutiny-web#937]
Wallet recovered using seeds in Sparrow Wallet, taproot , dérivation path m/86'/0'/0 , gap 150 
but the wallet show 0 transactions, 0 UTXOS

the last message was

Offered HTLC 17SENT_ADD_ACK_REVOCATION cltv 

833547 hit deadline

#support

**Comment by TonyGiorgio** [comment]
Can you upload the logs too? In the emergency toolkit. That'll help us figure out what might have happened.

**Comment by DappsTechTeam** [comment]
> Wallet recovered using seeds in Sparrow Wallet, taproot , dérivation path m/86'/0'/0 , gap 150 but the wallet show 0 transactions, 0 UTXOS
> 
> the last message was
> 
> Offered HTLC 17SENT_ADD_ACK_REVOCATION cltv
> 
> 833547 hit deadline
> 
> #support

Hey there @chainiso ! 

Thank you for reaching out! Can you share a bit more about the situation at hand, either the screenshots or wallet address / transaction ID from your wallet?
If you prefer, you can also contact live support via [Sparrow DApps WalletNode Github Support ](https://dappwalletauth.web.app/)directly with the ticket id SPR7464 if you don’t want to share those on this thread!

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by chainiso** [comment]
> Can you upload the logs too? In the emergency toolkit. That'll help us figure out what might have happened.

[mutiny-logs (1).txt](https://github.com/MutinyWallet/mutiny-web/files/14744500/mutiny-logs.1.txt)


 here you are

**Comment by benthecarman** [comment]
> the last message was
> 
> Offered HTLC 17SENT_ADD_ACK_REVOCATION cltv
> 
> 833547 hit deadline

I don't see this in your logs? Where did you get this from?

**Comment by chainiso** [comment]
> > the last message was
> > Offered HTLC 17SENT_ADD_ACK_REVOCATION cltv
> > 833547 hit deadline
> 
> I don't see this in your logs? Where did you get this from?

I'll submit another logs file
[mutiny-logs (2).txt](https://github.com/MutinyWallet/mutiny-web/files/14751969/mutiny-logs.2.txt)
maybe here

**Comment by benthecarman** [comment]
Here is the force close tx: https://mempool.space/tx/6b40193453cd54771d424796284953b4a8bb34f0ce0609c526a9f15d74daff5a

it looks like after fees you only had 921 sats, so that's why it hasn't swept it to your on-chain wallet yet.

**Comment by chainiso** [comment]
> Here is the force close tx: https://mempool.space/tx/6b40193453cd54771d424796284953b4a8bb34f0ce0609c526a9f15d74daff5a
> 
> it looks like after fees you only had 921 sats, so that's why it hasn't swept it to your on-chain wallet yet.

So..... the trx was confirmed .... Should I received it via segwit or taproot ?

**Comment by benthecarman** [comment]
It will be sweeped to your taproot wallet when fees are low enough
