### ISSUE TITLE
Send to Alby Fails

### ISSUE THREAD

**Issue by acronymy** [MutinyWallet/mutiny-web#942]
Mutiny PWA wallet consistently fails to send to Alby. 
Uploaded logs as requested by Tony. 
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-web/files/14751802/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Thanks for that. As indicated in the discord: 

"thanks for that. Doesnt look like there's anything out of the ordinary on your device specifically. Just a bunch of bad routes being taken, though our prober is still doing fine at making large payments. I've asked the LSP to open a channel to alby directly, it looks like it had been closed previoiusly. They will so hopefully it's better afterwards."

Hopefully that'll fix it, nothing wrong on mutiny itself.
