### ISSUE TITLE
How do we explain channel reserve?

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#95]
Sucks to receive your first lightning tx, you paid a big fee for the channel open, and now your actual channel balance is visibly smaller than what you thought you were getting

<img width="651" alt="Screenshot 2023-05-11 at 2 34 20 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/0249b913-3b1b-4230-b293-3b2bba0df46f">

Maybe something like this? idk it's visually noisy

**Comment by TonyGiorgio** [comment]
Voltage agreed to remove channel reserve limits so this should be way less of an issue.

**Comment by TonyGiorgio** [comment]
We have a channel page for this now.
