### ISSUE TITLE
Lightning transaction stuck since Feb 26

### ISSUE THREAD

**Issue by dtsadf** [MutinyWallet/mutiny-web#956]
Any possibility of getting some help with stuck lightning transaction?  It has been stuck in pending mode since Feb 26th - more than 30 days.  During this period, also had several forced  channel closures. Invoice for stuck transaction: 

lnbc1403590980p1pjaew2spp5suzkkl76hawuc057dkuul8j32s84rz5t8qhafl6qdgdmhwacw6qscqpjsp5tpyjahctc8kpzya75yau4p0tdqn5n8tsehrnm08dvwzpl0z673hq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqdqqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glclle0y7ejzawjhcqqqqlgqqqqqeqqjqmsn3lhs2at74tdjm30hv6aswmwddfasz4jwa5fy95qwf7wj0lnzxwes6wl6qlanhc8umex6l2pjrt7mn4eqgrcj2dht45vsyepv0f7sqrf2rcp

**Comment by TonyGiorgio** [comment]
If it's been that long, odds are there's just a bug with it not being marked as confirmed or failed. We don't have a delete transaction button there yet but you can always delete your state and restore from your seed words which will clean the transaction list.
