### ISSUE TITLE
First receive needs warnings about amounts / fee

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-web#96]
Help on the wording would be appreciated:

<img width="858" alt="Screenshot 2023-05-11 at 2 38 38 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/5a1b4dbc-be80-4bd1-82d4-b1bd9a0d1c4d">

**Comment by TonyGiorgio** [comment]
Got a few comments about this. We've added the reserve balance to show up in Lightning which should help but still need to do better about communicating LSP fees. Going to bump this one up in priority for up next.

**Comment by TonyGiorgio** [comment]
There's some info the bitcoin design guide about first time fees: https://bitcoin.design/guide/daily-spending-wallet/first-use/#receiving-the-deposit
