### ISSUE TITLE
Can't click on Lightning channel activties

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-web#967]
Can't click on lightning opens or closes

**Comment by futurepaul** [comment]
here's how it looks now. what's our ideal here?

<img width="340" alt="Screenshot 2024-04-03 at 11 25 08 AM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/743b6d8d-854e-493c-9381-482ed512ac2e">

**Comment by benthecarman** [comment]
The main thing is to be able to click on the close activity so we can see why channels were force closed
