### ISSUE TITLE
Onboareing new ppl: UX on screen user feedback improvement 

### ISSUE THREAD

**Issue by kimoraku** [MutinyWallet/mutiny-web#974]
Point of improvement for Mutiny Wallet:

Add a clear amount in satoshis + the waiting time on average (10 to 30 minutes) + an explanation that you'll only have to do this once during the "onboarding" process.

Background and Explanation:
Today, I attempted to onboard someone on Mutiny Wallet. They wanted to control their own keys but didn't know much about Bitcoin. They had about $170 worth of bitcoin on Wallet of Satoshi. After installing Mutiny Wallet, they made an initial transaction of the full amount at once. However, they only saw 'pending' on Wallet of Satoshi, while Mutiny Wallet didn't provide any on-screen feedback. The user I tried to onboard mentioned seeing a minimum requirement on-screen, but they didn't understand it.

User on-screen feedback is crucial: they are unaware that they need to wait for the first on-chain transaction to be completed before their channel is created. Therefore, it's essential to explain this to them clearly and succinctly, perhaps with a message like: "Creating your channel now. Please be patient as your funds are underway." Additionally, state the minimum amount required (the help ? mark indicated an initial fee was necessary, but the amount was not specified).

**Comment by TonyGiorgio** [comment]
The minimum amount used to be there but went away, it will be back on the next release. 

When the wallet gets the payment or sees it, it will indicate it. If we don't see it, then it'll sit on the QR page. There's nothing we can do if it hasn't been received.

**Comment by kimoraku** [comment]
It's more about the way the new user gets informed. Just display something '
We know as a bitcoiner there is nothing yiu can do than wait
The user doesn't know, and if mutiny wallet doesn't display a message, the user will not understand.
just ly 2 cents as a 10+ years software tester

-------- Original Message --------

**Comment by benthecarman** [comment]
We don't wait for confirmations for it to show something. The second it sees the payment it should show the success screen.

Mutiny needs to be open to be able to receive the payment, if they were sending from WoS, its possible they didn't open mutiny so WoS was attempting to send the payment and Mutiny could not receive it because it was not open.

**Comment by kimoraku** [comment]
I understand, but this tech explanation misses the point of onboarding going wrong.

The point is the on-screen displayed message to the end user should list
atht it's a 1 time payment
This wil cost x amount if sats
and it can take 10 to 30 mins or something along the lin.e
(yes, WE know that this is just like you described, but a new user doesn't know).
If you don't display a message on screen, they don't know.

That would improve the process, regardless who sends what and from where.

(sorry if this comes across too direct, I think mutiny is a super cool wallet'.' would be udeal for onboarding IF this is fixed somehow)

greetings
Manuel
AvBpodcast

-------- Original Message --------

**Comment by benthecarman** [comment]
We're just trying to convey the payment should be instant. It sounds like user error on why it was taking so long.

**Comment by kimoraku** [comment]
I give up :)

-------- Original Message --------
