### ISSUE TITLE
Cannot receive lightning funds

### ISSUE THREAD

**Issue by frettor** [MutinyWallet/mutiny-web#992]
Hi there.

I generate a Lightning invoice and see the sender trying to transfer the funds, but the attempts fail repeatedly.
He has increased the fee from 1000 ppm (standard) to 4000, but the payment still doesn't go through.

Any ideas?

**Comment by benthecarman** [comment]
Sorry about this, our LSP has been having some issues with the recent influx of users, this should hopefully be resolved in the next couple of days

**Comment by benthecarman** [comment]
Our LSP issues should be resolved now
