### ISSUE TITLE
same contact multiple times

### ISSUE THREAD

**Issue by elnosh** [MutinyWallet/mutiny-web#996]
seeing the same contact multiple times for some

![IMG_20240405_103655](https://github.com/MutinyWallet/mutiny-web/assets/49532260/523e3aec-43b3-4282-b6f7-133dfe51babe)

![IMG_20240405_103639](https://github.com/MutinyWallet/mutiny-web/assets/49532260/85f0b0f6-8754-4e16-a25e-c4fc28caace0)

**Comment by benthecarman** [comment]
did these appear after sending to them?

**Comment by elnosh** [comment]
no, I haven't sent to some that still show multiple times. It seemed very random

**Comment by futurepaul** [comment]
@elnosh have you been able to repro since the latest update?

**Comment by elnosh** [comment]
yeah still seeing the same contact multiple times. I'm on v0.6.3

**Comment by benthecarman** [comment]
can you try just restoring from seed. this should wipe out your current list and resync them

**Comment by elnosh** [comment]
restoring from seed worked. Thanks
